import Mathlib
import SendovNBdryEq10
import SendovNRows10
import Sendov911Capstone

set_option maxHeartbeats 4000000

/-!
# D10-8: the boundary reduction (generated by emit_assembly1011.py)

`9/10 ≤ a < 1` is driven into the boundary box: σ ≤ S_b (`sigma_boundary`),
the localization key gives `9a(1−u) ≤ (1−a)(S_b(1+a)−9)`, hence
`η² ≤ Y_b²(1−a)`; substituting `x = √(1−a)`, `Y = η/x` and pulling back
`U = (25/8)x`, `V = (20/31 : ℝ)·Y`, the boundary hEq turns the nonpositive
certificate value into `x²·(box polynomial) ≤ 0`, and `x² > 0` finishes.
-/

namespace SendovN.Red10Bdry

open Finset Sendov911Capstone

noncomputable def boxB10 : Box where
  nx := 28
  ny := 10
  A := Sendov911Box10Boundary.tab Sendov911Box10Boundary.Adata
  D := (Sendov911Box10Boundary.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10Boundary.Dscale]

theorem posB10 : ∀ U V : ℝ, 0 ≤ U → U ≤ 1 → 0 ≤ V → V ≤ 1 →
    0 < Box.poly boxB10 U V :=
  fun _ _ h1 h2 h3 h4 => Sendov911Box10Boundary.box_positive h1 h2 h3 h4

theorem red_bdry (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (9/10 : ℝ) ≤ a) (h1 : a < 1)
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hetau : eta ^ 2 ≤ 1 - mu.re ^ 2) (hmu1 : ‖mu‖ < 1)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k)
    (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly boxB10 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := h1.le
  have hsig : sig ≤ (469879173178970601607/48564147949218750000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_boundary rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_boundary h0 ha1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (469879173178970601607/48564147949218750000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (22/25 : ℝ) * a + ((9:ℕ):ℝ) - (469879173178970601607/48564147949218750000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (9/10 : ℝ)) (beta := (1:ℝ))
    (S := (469879173178970601607/48564147949218750000 : ℝ)) (lam := (22/25 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) le_rfl (by norm_num) Rows10.lam_boundary h0 ha1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  -- η² ≤ Y_b²(1−a)
  have hkeyP : (9:ℝ) - (469879173178970601607/48564147949218750000 : ℝ) + (469879173178970601607/48564147949218750000 : ℝ) * a ^ 2 ≤ 9 * a * mu.re := by
    push_cast at hkey
    linarith [hkey]
  have hu1 : mu.re < 1 := lt_of_le_of_lt (Complex.re_le_norm mu) hmu1
  have h9a : 9 * a * (1 - mu.re) ≤ (1 - a) * ((469879173178970601607/48564147949218750000 : ℝ) * (1 + a) - 9) := by
    nlinarith [hkeyP]
  have hA : 9 * a * eta ^ 2 ≤ 2 * ((1 - a) * ((469879173178970601607/48564147949218750000 : ℝ) * (1 + a) - 9)) := by
    nlinarith [h9a,
      mul_le_mul_of_nonneg_left hetau (by linarith : (0:ℝ) ≤ 9 * a),
      mul_nonneg (mul_nonneg (by linarith : (0:ℝ) ≤ 9 * a)
        (by linarith : (0:ℝ) ≤ 1 - mu.re)) (by linarith : (0:ℝ) ≤ 1 - mu.re),
      hlamu]
  have hxx : 9 * a * eta ^ 2 ≤ 9 * a * ((31/20 : ℝ) ^ 2 * (1 - a)) := by
    nlinarith [hA, mul_nonneg (sub_nonneg.mpr h0) (by linarith : (0:ℝ) ≤ 1 - a)]
  have heta2 : eta ^ 2 ≤ (31/20 : ℝ) ^ 2 * (1 - a) :=
    le_of_mul_le_mul_left (by linarith [hxx]) (by linarith : (0:ℝ) < 9 * a)
  -- the substitution x = √(1−a), Y = η/x
  set x := Real.sqrt (1 - a) with hxdef
  have hx2 : x ^ 2 = 1 - a := Real.sq_sqrt (by linarith)
  have hx0 : (0:ℝ) < x := Real.sqrt_pos.mpr (by linarith)
  have hxle : x ≤ 8/25 := by
    nlinarith [hx2, sq_nonneg (x - 8/25), h0]
  have hYle : eta / x ≤ (31/20 : ℝ) := by
    rw [div_le_iff₀ hx0]
    nlinarith [heta2, hx2, heta0,
      mul_nonneg (by norm_num : (0:ℝ) ≤ (31/20 : ℝ)) hx0.le]
  refine ⟨25/8 * x, (20/31 : ℝ) * (eta / x), by linarith, by linarith,
    mul_nonneg (by norm_num) (div_nonneg heta0 hx0.le), ?_, ?_⟩
  · nlinarith [hYle, div_nonneg heta0 hx0.le]
  have heq := BdryEq10.bdry10_eq (25/8 * x) ((20/31 : ℝ) * (eta / x))
  rw [show (8/25 : ℝ) * (25/8 * x) = x by ring] at heq
  rw [show ((31/20 : ℝ)) * ((20/31 : ℝ) * (eta / x)) = eta / x by ring] at heq
  rw [show (1:ℝ) - x ^ 2 = a by linarith [hx2]] at heq
  rw [show x * (eta / x) = eta by field_simp [hx0.ne']] at heq
  have heqq : Box.poly boxB10 (25/8 * x) ((20/31 : ℝ) * (eta / x))
      = ∑ k ∈ Finset.range 29, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10Boundary.tab Sendov911Box10Boundary.Adata k l : ℝ)
          / (Sendov911Box10Boundary.Dscale : ℝ)) * (25/8 * x) ^ k * ((20/31 : ℝ) * (eta / x)) ^ l := rfl
  have hs : x ^ 2 * Box.poly boxB10 (25/8 * x) ((20/31 : ℝ) * (eta / x)) ≤ 0 := by
    rw [heqq]
    exact le_of_eq_of_le heq.symm hP
  have hx2pos : (0:ℝ) < x ^ 2 := pow_pos hx0 2
  nlinarith [hs, hx2pos]

end SendovN.Red10Bdry

#print axioms SendovN.Red10Bdry.posB10
#print axioms SendovN.Red10Bdry.red_bdry
