import Mathlib
import SendovNRed11_37
import SendovNRed11_38
import SendovNRed11_39
import SendovNRed11_40
import SendovNRed11_41
import SendovNRed11_42
import SendovNRed11_43
import SendovNRed11_44
import SendovNRed11_45
import SendovNRed11_46
import SendovNRed11_47
import SendovNRed11_48
import SendovNRed11_49
import SendovNRed11_50
import SendovNRed11_51
import SendovNRed11_52
import SendovNRed11_53
import SendovNRed11_54
import SendovNRed11_55
import SendovNRed11_56
import SendovNRed11_57
import SendovNRed11_58
import SendovNRed11_59
import SendovNRed11_60
import SendovNRed11_61
import SendovNRed11_62
import SendovNRed11_63
import SendovNRed11_64
import SendovNRed11_65
import SendovNRed11_66
import SendovNRed11_67
import SendovNRed11_68
import SendovNRed11_69
import SendovNRed11_70
import SendovNRed11_71
import SendovNRed11_72
import SendovNRed11_73
import SendovNRed11_74
import SendovNRed11_75
import SendovNRed11_76
import SendovNRed11_77
import SendovNRed11_78
import SendovNRed11_79
import SendovNRed11_80
import SendovNRed11_81
import SendovNRed11_82
import SendovNRed11_83
import SendovNRed11_84
import SendovNRed11_85
import SendovNRed11_86
import SendovNRed11_87
import SendovNRed11_88
import SendovNRed11_89
import SendovNRed11Bdry
import SendovNCoverGrid

set_option maxHeartbeats 16000000

/-!
# D11-9: `CoveringPositive boxes11` (generated by emit_assembly1011.py)

The 531-box family (53 rows × 10 η-strips + boundary), assembled from the
per-row `CoveringPositive` proofs via `coveringPositive_append`, plus the
per-row membership lifts the reduction needs.
-/

namespace SendovN.Covering11

open Sendov911Capstone

noncomputable def boxes11 : List Box :=
  Red11_37.row_37 ++ (Red11_38.row_38 ++ (Red11_39.row_39 ++ (Red11_40.row_40 ++ (Red11_41.row_41 ++ (Red11_42.row_42 ++ (Red11_43.row_43 ++ (Red11_44.row_44 ++ (Red11_45.row_45 ++ (Red11_46.row_46 ++ (Red11_47.row_47 ++ (Red11_48.row_48 ++ (Red11_49.row_49 ++ (Red11_50.row_50 ++ (Red11_51.row_51 ++ (Red11_52.row_52 ++ (Red11_53.row_53 ++ (Red11_54.row_54 ++ (Red11_55.row_55 ++ (Red11_56.row_56 ++ (Red11_57.row_57 ++ (Red11_58.row_58 ++ (Red11_59.row_59 ++ (Red11_60.row_60 ++ (Red11_61.row_61 ++ (Red11_62.row_62 ++ (Red11_63.row_63 ++ (Red11_64.row_64 ++ (Red11_65.row_65 ++ (Red11_66.row_66 ++ (Red11_67.row_67 ++ (Red11_68.row_68 ++ (Red11_69.row_69 ++ (Red11_70.row_70 ++ (Red11_71.row_71 ++ (Red11_72.row_72 ++ (Red11_73.row_73 ++ (Red11_74.row_74 ++ (Red11_75.row_75 ++ (Red11_76.row_76 ++ (Red11_77.row_77 ++ (Red11_78.row_78 ++ (Red11_79.row_79 ++ (Red11_80.row_80 ++ (Red11_81.row_81 ++ (Red11_82.row_82 ++ (Red11_83.row_83 ++ (Red11_84.row_84 ++ (Red11_85.row_85 ++ (Red11_86.row_86 ++ (Red11_87.row_87 ++ (Red11_88.row_88 ++ (Red11_89.row_89 ++ ([Red11Bdry.boxB11])))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem covering11 : CoveringPositive boxes11 :=
  Cover.coveringPositive_append Red11_37.rowPos_37
    (Cover.coveringPositive_append Red11_38.rowPos_38
    (Cover.coveringPositive_append Red11_39.rowPos_39
    (Cover.coveringPositive_append Red11_40.rowPos_40
    (Cover.coveringPositive_append Red11_41.rowPos_41
    (Cover.coveringPositive_append Red11_42.rowPos_42
    (Cover.coveringPositive_append Red11_43.rowPos_43
    (Cover.coveringPositive_append Red11_44.rowPos_44
    (Cover.coveringPositive_append Red11_45.rowPos_45
    (Cover.coveringPositive_append Red11_46.rowPos_46
    (Cover.coveringPositive_append Red11_47.rowPos_47
    (Cover.coveringPositive_append Red11_48.rowPos_48
    (Cover.coveringPositive_append Red11_49.rowPos_49
    (Cover.coveringPositive_append Red11_50.rowPos_50
    (Cover.coveringPositive_append Red11_51.rowPos_51
    (Cover.coveringPositive_append Red11_52.rowPos_52
    (Cover.coveringPositive_append Red11_53.rowPos_53
    (Cover.coveringPositive_append Red11_54.rowPos_54
    (Cover.coveringPositive_append Red11_55.rowPos_55
    (Cover.coveringPositive_append Red11_56.rowPos_56
    (Cover.coveringPositive_append Red11_57.rowPos_57
    (Cover.coveringPositive_append Red11_58.rowPos_58
    (Cover.coveringPositive_append Red11_59.rowPos_59
    (Cover.coveringPositive_append Red11_60.rowPos_60
    (Cover.coveringPositive_append Red11_61.rowPos_61
    (Cover.coveringPositive_append Red11_62.rowPos_62
    (Cover.coveringPositive_append Red11_63.rowPos_63
    (Cover.coveringPositive_append Red11_64.rowPos_64
    (Cover.coveringPositive_append Red11_65.rowPos_65
    (Cover.coveringPositive_append Red11_66.rowPos_66
    (Cover.coveringPositive_append Red11_67.rowPos_67
    (Cover.coveringPositive_append Red11_68.rowPos_68
    (Cover.coveringPositive_append Red11_69.rowPos_69
    (Cover.coveringPositive_append Red11_70.rowPos_70
    (Cover.coveringPositive_append Red11_71.rowPos_71
    (Cover.coveringPositive_append Red11_72.rowPos_72
    (Cover.coveringPositive_append Red11_73.rowPos_73
    (Cover.coveringPositive_append Red11_74.rowPos_74
    (Cover.coveringPositive_append Red11_75.rowPos_75
    (Cover.coveringPositive_append Red11_76.rowPos_76
    (Cover.coveringPositive_append Red11_77.rowPos_77
    (Cover.coveringPositive_append Red11_78.rowPos_78
    (Cover.coveringPositive_append Red11_79.rowPos_79
    (Cover.coveringPositive_append Red11_80.rowPos_80
    (Cover.coveringPositive_append Red11_81.rowPos_81
    (Cover.coveringPositive_append Red11_82.rowPos_82
    (Cover.coveringPositive_append Red11_83.rowPos_83
    (Cover.coveringPositive_append Red11_84.rowPos_84
    (Cover.coveringPositive_append Red11_85.rowPos_85
    (Cover.coveringPositive_append Red11_86.rowPos_86
    (Cover.coveringPositive_append Red11_87.rowPos_87
    (Cover.coveringPositive_append Red11_88.rowPos_88
    (Cover.coveringPositive_append Red11_89.rowPos_89
    (coveringPositive_cons Red11Bdry.posB11 coveringPositive_nil)))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_37 {b : Box} (hb : b ∈ Red11_37.row_37) : b ∈ boxes11 :=
  List.mem_append_left _ hb

theorem lift_38 {b : Box} (hb : b ∈ Red11_38.row_38) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_left _ hb)

theorem lift_39 {b : Box} (hb : b ∈ Red11_39.row_39) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))

theorem lift_40 {b : Box} (hb : b ∈ Red11_40.row_40) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))

theorem lift_41 {b : Box} (hb : b ∈ Red11_41.row_41) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))

theorem lift_42 {b : Box} (hb : b ∈ Red11_42.row_42) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))

theorem lift_43 {b : Box} (hb : b ∈ Red11_43.row_43) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))

theorem lift_44 {b : Box} (hb : b ∈ Red11_44.row_44) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))

theorem lift_45 {b : Box} (hb : b ∈ Red11_45.row_45) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))

theorem lift_46 {b : Box} (hb : b ∈ Red11_46.row_46) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))

theorem lift_47 {b : Box} (hb : b ∈ Red11_47.row_47) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))

theorem lift_48 {b : Box} (hb : b ∈ Red11_48.row_48) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))

theorem lift_49 {b : Box} (hb : b ∈ Red11_49.row_49) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))

theorem lift_50 {b : Box} (hb : b ∈ Red11_50.row_50) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))

theorem lift_51 {b : Box} (hb : b ∈ Red11_51.row_51) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))

theorem lift_52 {b : Box} (hb : b ∈ Red11_52.row_52) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))

theorem lift_53 {b : Box} (hb : b ∈ Red11_53.row_53) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))

theorem lift_54 {b : Box} (hb : b ∈ Red11_54.row_54) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))

theorem lift_55 {b : Box} (hb : b ∈ Red11_55.row_55) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))

theorem lift_56 {b : Box} (hb : b ∈ Red11_56.row_56) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))

theorem lift_57 {b : Box} (hb : b ∈ Red11_57.row_57) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))

theorem lift_58 {b : Box} (hb : b ∈ Red11_58.row_58) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))

theorem lift_59 {b : Box} (hb : b ∈ Red11_59.row_59) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))

theorem lift_60 {b : Box} (hb : b ∈ Red11_60.row_60) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))

theorem lift_61 {b : Box} (hb : b ∈ Red11_61.row_61) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))

theorem lift_62 {b : Box} (hb : b ∈ Red11_62.row_62) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))

theorem lift_63 {b : Box} (hb : b ∈ Red11_63.row_63) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))

theorem lift_64 {b : Box} (hb : b ∈ Red11_64.row_64) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))

theorem lift_65 {b : Box} (hb : b ∈ Red11_65.row_65) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))

theorem lift_66 {b : Box} (hb : b ∈ Red11_66.row_66) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))

theorem lift_67 {b : Box} (hb : b ∈ Red11_67.row_67) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))

theorem lift_68 {b : Box} (hb : b ∈ Red11_68.row_68) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))

theorem lift_69 {b : Box} (hb : b ∈ Red11_69.row_69) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))

theorem lift_70 {b : Box} (hb : b ∈ Red11_70.row_70) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))

theorem lift_71 {b : Box} (hb : b ∈ Red11_71.row_71) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))

theorem lift_72 {b : Box} (hb : b ∈ Red11_72.row_72) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))

theorem lift_73 {b : Box} (hb : b ∈ Red11_73.row_73) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))

theorem lift_74 {b : Box} (hb : b ∈ Red11_74.row_74) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))

theorem lift_75 {b : Box} (hb : b ∈ Red11_75.row_75) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))

theorem lift_76 {b : Box} (hb : b ∈ Red11_76.row_76) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))

theorem lift_77 {b : Box} (hb : b ∈ Red11_77.row_77) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))

theorem lift_78 {b : Box} (hb : b ∈ Red11_78.row_78) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))

theorem lift_79 {b : Box} (hb : b ∈ Red11_79.row_79) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))

theorem lift_80 {b : Box} (hb : b ∈ Red11_80.row_80) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))))

theorem lift_81 {b : Box} (hb : b ∈ Red11_81.row_81) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))))

theorem lift_82 {b : Box} (hb : b ∈ Red11_82.row_82) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))))))

theorem lift_83 {b : Box} (hb : b ∈ Red11_83.row_83) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_84 {b : Box} (hb : b ∈ Red11_84.row_84) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_85 {b : Box} (hb : b ∈ Red11_85.row_85) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_86 {b : Box} (hb : b ∈ Red11_86.row_86) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_87 {b : Box} (hb : b ∈ Red11_87.row_87) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_88 {b : Box} (hb : b ∈ Red11_88.row_88) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb)))))))))))))))))))))))))))))))))))))))))))))))))))

theorem lift_89 {b : Box} (hb : b ∈ Red11_89.row_89) : b ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_left _ hb))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem mem_bdry : Red11Bdry.boxB11 ∈ boxes11 :=
  List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.mem_append_right _ (List.Mem.head _)))))))))))))))))))))))))))))))))))))))))))))))))))))

end SendovN.Covering11

#print axioms SendovN.Covering11.covering11
#print axioms SendovN.Covering11.lift_37
#print axioms SendovN.Covering11.lift_38
#print axioms SendovN.Covering11.lift_39
#print axioms SendovN.Covering11.lift_40
#print axioms SendovN.Covering11.lift_41
#print axioms SendovN.Covering11.lift_42
#print axioms SendovN.Covering11.lift_43
#print axioms SendovN.Covering11.lift_44
#print axioms SendovN.Covering11.lift_45
#print axioms SendovN.Covering11.lift_46
#print axioms SendovN.Covering11.lift_47
#print axioms SendovN.Covering11.lift_48
#print axioms SendovN.Covering11.lift_49
#print axioms SendovN.Covering11.lift_50
#print axioms SendovN.Covering11.lift_51
#print axioms SendovN.Covering11.lift_52
#print axioms SendovN.Covering11.lift_53
#print axioms SendovN.Covering11.lift_54
#print axioms SendovN.Covering11.lift_55
#print axioms SendovN.Covering11.lift_56
#print axioms SendovN.Covering11.lift_57
#print axioms SendovN.Covering11.lift_58
#print axioms SendovN.Covering11.lift_59
#print axioms SendovN.Covering11.lift_60
#print axioms SendovN.Covering11.lift_61
#print axioms SendovN.Covering11.lift_62
#print axioms SendovN.Covering11.lift_63
#print axioms SendovN.Covering11.lift_64
#print axioms SendovN.Covering11.lift_65
#print axioms SendovN.Covering11.lift_66
#print axioms SendovN.Covering11.lift_67
#print axioms SendovN.Covering11.lift_68
#print axioms SendovN.Covering11.lift_69
#print axioms SendovN.Covering11.lift_70
#print axioms SendovN.Covering11.lift_71
#print axioms SendovN.Covering11.lift_72
#print axioms SendovN.Covering11.lift_73
#print axioms SendovN.Covering11.lift_74
#print axioms SendovN.Covering11.lift_75
#print axioms SendovN.Covering11.lift_76
#print axioms SendovN.Covering11.lift_77
#print axioms SendovN.Covering11.lift_78
#print axioms SendovN.Covering11.lift_79
#print axioms SendovN.Covering11.lift_80
#print axioms SendovN.Covering11.lift_81
#print axioms SendovN.Covering11.lift_82
#print axioms SendovN.Covering11.lift_83
#print axioms SendovN.Covering11.lift_84
#print axioms SendovN.Covering11.lift_85
#print axioms SendovN.Covering11.lift_86
#print axioms SendovN.Covering11.lift_87
#print axioms SendovN.Covering11.lift_88
#print axioms SendovN.Covering11.lift_89
#print axioms SendovN.Covering11.mem_bdry
