import Mathlib
import SendovNMidChain
import SendovNSplit11
import SendovNEInt
import SendovNEsp10
import SendovNEsp11

set_option maxHeartbeats 16000000
set_option maxRecDepth 100000

/-!
# EmajEq folding for degrees 10 and 11 (generated)

Generated by `emit_emajeq1011.py`; do not hand-edit.  Rewrites the integral
majorants through the both-limits-free closed forms of `SendovN.EInt`
(`emit_eint1011.py`):

* `Emaj10_eq` : `MidChainN.Emaj 9 CTab10.c10 S a η` as an explicit polynomial
  in `(S, a, η)` — the degree-10 certificates' `E` term, with
  `Q1 = −2(9−S+Sa²)/9`, `Q2 = a²(1−η²)` spelled inline;
* `EmajTau11_eq` : `Split11.EmajTau CTab11.c11 S a η τ` as an explicit
  polynomial in `(S, a, η, τ)` — head integrals `(0,τ)`, τ-split tails `(τ,1)`
  (`q₀⁵` with `Q2 = a²(1−η²)`, `q₁⁵` with `Q2 = a²`).

Identities verified at 25 random rational points by two independent
computation routes before emission.  With these, each box `hEq` is a `rw`
followed by `ring`.
-/

namespace SendovN.EmajEq

open Finset intervalIntegral

/-- **`E_S(a,η)` at degree 10, evaluated** (the certificates' `E` term). -/
theorem Emaj10_eq (S a eta : ℝ) :
    MidChainN.Emaj 9 CTab10.c10 S a eta
      = (9/2 : ℝ) * eta ^ 2 * a ^ 3 *
        ((1/3 : ℝ)
          + (3/5 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (3/7 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (1/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3
          + (3/4 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9))
          + (1 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2))
          + (3/8 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (3/5 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2
          + (3/7 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2 * (a ^ 2 * (1 - eta ^ 2))
          + (1/6 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 3)
      + (9 : ℝ) * eta ^ 3 * a ^ 4 *
        ((1/4 : ℝ)
          + (1/2 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (3/8 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3
          + (3/5 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9))
          + (6/7 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2))
          + (1/3 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (1/2 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2
          + (3/8 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2 * (a ^ 2 * (1 - eta ^ 2))
          + (1/7 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 3)
      + (2201/100 : ℝ) * eta ^ 4 * a ^ 5 *
        ((1/5 : ℝ)
          + (2/7 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (1/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (1/3 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9))
          + (1/4 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2))
          + (1/7 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2)
      + (2201/100 : ℝ) * eta ^ 5 * a ^ 6 *
        ((1/6 : ℝ)
          + (1/4 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2
          + (2/7 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9))
          + (2/9 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) * (a ^ 2 * (1 - eta ^ 2))
          + (1/8 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)) ^ 2)
      + (877/50 : ℝ) * eta ^ 6 * a ^ 7 *
        ((1/7 : ℝ)
          + (1/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (1/8 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)))
      + (217/20 : ℝ) * eta ^ 7 * a ^ 8 *
        ((1/8 : ℝ)
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2))
          + (1/9 : ℝ) * (-(2 * (9 - S + S * a ^ 2) / 9)))
      + (481/100 : ℝ) * eta ^ 8 * a ^ 9 *
        ((1/9 : ℝ))
      + (1 : ℝ) * eta ^ 9 * a ^ 10 *
        ((1/10 : ℝ)) := by
  unfold MidChainN.Emaj
  have hIcc : (Finset.Icc 2 9 : Finset ℕ) = {2, 3, 4, 5, 6, 7, 8, 9} := by decide
  rw [hIcc, Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_singleton]
  have c2 : CTab10.c10 2 = (9/2 : ℝ) := by norm_num [CTab10.c10]
  have c3 : CTab10.c10 3 = (9 : ℝ) := by norm_num [CTab10.c10]
  have c4 : CTab10.c10 4 = (2201/100 : ℝ) := by norm_num [CTab10.c10]
  have c5 : CTab10.c10 5 = (2201/100 : ℝ) := by norm_num [CTab10.c10]
  have c6 : CTab10.c10 6 = (877/50 : ℝ) := by norm_num [CTab10.c10]
  have c7 : CTab10.c10 7 = (217/20 : ℝ) := by norm_num [CTab10.c10]
  have c8 : CTab10.c10 8 = (481/100 : ℝ) := by norm_num [CTab10.c10]
  have c9 : CTab10.c10 9 = (1 : ℝ) := by norm_num [CTab10.c10]
  have l2 : MidChainN.ell 9 2 = 3 := by norm_num [MidChainN.ell]
  have l3 : MidChainN.ell 9 3 = 3 := by norm_num [MidChainN.ell]
  have l4 : MidChainN.ell 9 4 = 2 := by norm_num [MidChainN.ell]
  have l5 : MidChainN.ell 9 5 = 2 := by norm_num [MidChainN.ell]
  have l6 : MidChainN.ell 9 6 = 1 := by norm_num [MidChainN.ell]
  have l7 : MidChainN.ell 9 7 = 1 := by norm_num [MidChainN.ell]
  have l8 : MidChainN.ell 9 8 = 0 := by norm_num [MidChainN.ell]
  have l9 : MidChainN.ell 9 9 = 0 := by norm_num [MidChainN.ell]
  rw [c2, l2, c3, l3, c4, l4, c5, l5, c6, l6, c7, l7, c8, l8, c9, l9]
  have hq : ∀ v : ℝ, MidChainN.q0 9 S a eta v
      = 1 + (-(2 * (9 - S + S * a ^ 2) / 9)) * v + (a ^ 2 * (1 - eta ^ 2)) * v ^ 2 := by
    intro v
    unfold MidChainN.q0
    push_cast
    ring
  simp only [hq]
  rw [EInt.int_2_3, EInt.int_3_3, EInt.int_4_2, EInt.int_5_2, EInt.int_6_1,
    EInt.int_7_1, EInt.int_8_0, EInt.int_9_0]
  norm_num
  ring

/-- **`E^{(τ)}_S(a,η)` at degree 11, evaluated** (the τ-split certificates'
`E` term; `τ = 1` degenerates to the unsplit form). -/
theorem EmajTau11_eq (S a eta tau : ℝ) :
    Split11.EmajTau CTab11.c11 S a eta tau
      = (5 : ℝ) * eta ^ 2 * a ^ 3 *
        ((1/3 : ℝ) * tau ^ 3
          + (4/5 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 5
          + (6/7 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 7
          + (4/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * tau ^ 9
          + (1/11 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 4 * tau ^ 11
          + (1 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 4
          + (2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 6
          + (3/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 8
          + (2/5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * tau ^ 10
          + (6/5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * tau ^ 5
          + (12/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 7
          + (2/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 9
          + (2/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * tau ^ 6
          + (1/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 8
          + (1/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 4 * tau ^ 7)
      + (10 : ℝ) * eta ^ 3 * a ^ 4 *
        ((1/4 : ℝ) * tau ^ 4
          + (1/2 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 6
          + (3/8 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 8
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * tau ^ 10
          + (3/5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 5
          + (6/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 7
          + (1/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 9
          + (1/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * tau ^ 6
          + (3/8 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 8
          + (1/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * tau ^ 7)
      + (1447/50 : ℝ) * eta ^ 4 * a ^ 5 *
        ((1/5 : ℝ) * tau ^ 5
          + (3/7 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 7
          + (1/3 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 9
          + (1/11 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * tau ^ 11
          + (1/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 6
          + (3/4 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 8
          + (3/10 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 10
          + (3/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * tau ^ 7
          + (1/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 9
          + (1/8 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * tau ^ 8)
      + (32 : ℝ) * eta ^ 5 * a ^ 6 *
        ((1/6 : ℝ) * tau ^ 6
          + (1/4 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 8
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 10
          + (2/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 7
          + (2/9 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 9
          + (1/8 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * tau ^ 8)
      + (3125/108 : ℝ) * eta ^ 6 * a ^ 7 *
        ((1/7 : ℝ) * tau ^ 7
          + (2/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 9
          + (1/11 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * tau ^ 11
          + (1/4 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 8
          + (1/5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 10
          + (1/9 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * tau ^ 9)
      + (2121/100 : ℝ) * eta ^ 7 * a ^ 8 *
        ((1/8 : ℝ) * tau ^ 8
          + (1/10 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 10
          + (1/9 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 9)
      + (3125/256 : ℝ) * eta ^ 8 * a ^ 9 *
        ((1/9 : ℝ) * tau ^ 9
          + (1/11 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * tau ^ 11
          + (1/10 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * tau ^ 10)
      + (509/100 : ℝ) * eta ^ 9 * a ^ 10 *
        ((1/10 : ℝ) * tau ^ 10)
      + (1 : ℝ) * eta ^ 10 * a ^ 11 *
        ((1/11 : ℝ) * tau ^ 11)
      + a *
        (((1 : ℝ) * (1 - tau ^ 1)
          + (5/3 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) * (1 - tau ^ 3)
          + (2 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * (1 - tau ^ 5)
          + (10/7 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * (1 - tau ^ 7)
          + (5/9 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 4 * (1 - tau ^ 9)
          + (1/11 : ℝ) * (a ^ 2 * (1 - eta ^ 2)) ^ 5 * (1 - tau ^ 11)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (1 - tau ^ 2)
          + (5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) * (1 - tau ^ 4)
          + (5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * (1 - tau ^ 6)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * (1 - tau ^ 8)
          + (1/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2 * (1 - eta ^ 2)) ^ 4 * (1 - tau ^ 10)
          + (10/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (1 - tau ^ 3)
          + (6 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) * (1 - tau ^ 5)
          + (30/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * (1 - tau ^ 7)
          + (10/9 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2 * (1 - eta ^ 2)) ^ 3 * (1 - tau ^ 9)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (1 - tau ^ 4)
          + (10/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (a ^ 2 * (1 - eta ^ 2)) * (1 - tau ^ 6)
          + (5/4 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (a ^ 2 * (1 - eta ^ 2)) ^ 2 * (1 - tau ^ 8)
          + (1 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 4 * (1 - tau ^ 5)
          + (5/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 4 * (a ^ 2 * (1 - eta ^ 2)) * (1 - tau ^ 7)
          + (1/6 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 5 * (1 - tau ^ 6))
        + ((1 : ℝ) * (1 - tau ^ 1)
          + (5/3 : ℝ) * (a ^ 2) * (1 - tau ^ 3)
          + (2 : ℝ) * (a ^ 2) ^ 2 * (1 - tau ^ 5)
          + (10/7 : ℝ) * (a ^ 2) ^ 3 * (1 - tau ^ 7)
          + (5/9 : ℝ) * (a ^ 2) ^ 4 * (1 - tau ^ 9)
          + (1/11 : ℝ) * (a ^ 2) ^ 5 * (1 - tau ^ 11)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (1 - tau ^ 2)
          + (5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2) * (1 - tau ^ 4)
          + (5 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2) ^ 2 * (1 - tau ^ 6)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2) ^ 3 * (1 - tau ^ 8)
          + (1/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) * (a ^ 2) ^ 4 * (1 - tau ^ 10)
          + (10/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (1 - tau ^ 3)
          + (6 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2) * (1 - tau ^ 5)
          + (30/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2) ^ 2 * (1 - tau ^ 7)
          + (10/9 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 2 * (a ^ 2) ^ 3 * (1 - tau ^ 9)
          + (5/2 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (1 - tau ^ 4)
          + (10/3 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (a ^ 2) * (1 - tau ^ 6)
          + (5/4 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 3 * (a ^ 2) ^ 2 * (1 - tau ^ 8)
          + (1 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 4 * (1 - tau ^ 5)
          + (5/7 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 4 * (a ^ 2) * (1 - tau ^ 7)
          + (1/6 : ℝ) * (-(2 * (10 - S + S * a ^ 2) / 10)) ^ 5 * (1 - tau ^ 6))) := by
  unfold Split11.EmajTau
  have hIcc : (Finset.Icc 2 10 : Finset ℕ) = {2, 3, 4, 5, 6, 7, 8, 9, 10} := by
    decide
  rw [hIcc, Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_insert (by decide), Finset.sum_insert (by decide),
    Finset.sum_singleton]
  have c2 : CTab11.c11 2 = (5 : ℝ) := by norm_num [CTab11.c11]
  have c3 : CTab11.c11 3 = (10 : ℝ) := by norm_num [CTab11.c11]
  have c4 : CTab11.c11 4 = (1447/50 : ℝ) := by norm_num [CTab11.c11]
  have c5 : CTab11.c11 5 = (32 : ℝ) := by norm_num [CTab11.c11]
  have c6 : CTab11.c11 6 = (3125/108 : ℝ) := by norm_num [CTab11.c11]
  have c7 : CTab11.c11 7 = (2121/100 : ℝ) := by norm_num [CTab11.c11]
  have c8 : CTab11.c11 8 = (3125/256 : ℝ) := by norm_num [CTab11.c11]
  have c9 : CTab11.c11 9 = (509/100 : ℝ) := by norm_num [CTab11.c11]
  have c10 : CTab11.c11 10 = (1 : ℝ) := by norm_num [CTab11.c11]
  have l2 : MidChainN.ell 10 2 = 4 := by norm_num [MidChainN.ell]
  have l3 : MidChainN.ell 10 3 = 3 := by norm_num [MidChainN.ell]
  have l4 : MidChainN.ell 10 4 = 3 := by norm_num [MidChainN.ell]
  have l5 : MidChainN.ell 10 5 = 2 := by norm_num [MidChainN.ell]
  have l6 : MidChainN.ell 10 6 = 2 := by norm_num [MidChainN.ell]
  have l7 : MidChainN.ell 10 7 = 1 := by norm_num [MidChainN.ell]
  have l8 : MidChainN.ell 10 8 = 1 := by norm_num [MidChainN.ell]
  have l9 : MidChainN.ell 10 9 = 0 := by norm_num [MidChainN.ell]
  have l10 : MidChainN.ell 10 10 = 0 := by norm_num [MidChainN.ell]
  rw [c2, l2, c3, l3, c4, l4, c5, l5, c6, l6, c7, l7, c8, l8, c9, l9, c10, l10]
  have hq0 : ∀ v : ℝ, MidChainN.q0 10 S a eta v
      = 1 + (-(2 * (10 - S + S * a ^ 2) / 10)) * v + (a ^ 2 * (1 - eta ^ 2)) * v ^ 2 := by
    intro v
    unfold MidChainN.q0
    push_cast
    ring
  have hq1 : ∀ v : ℝ, Split11.q1 S a v
      = 1 + (-(2 * (10 - S + S * a ^ 2) / 10)) * v + (a ^ 2) * v ^ 2 := by
    intro v
    unfold Split11.q1
    ring
  simp only [hq0, hq1]
  rw [EInt.int_2_4, EInt.int_3_3, EInt.int_4_3, EInt.int_5_2, EInt.int_6_2,
    EInt.int_7_1, EInt.int_8_1, EInt.int_9_0, EInt.int_10_0]
  have hi0 : IntervalIntegrable
      (fun v : ℝ => (1 + (-(2 * (10 - S + S * a ^ 2) / 10)) * v + (a ^ 2 * (1 - eta ^ 2)) * v ^ 2) ^ 5)
      MeasureTheory.volume tau 1 := by
    apply Continuous.intervalIntegrable
    fun_prop
  have hi1 : IntervalIntegrable
      (fun v : ℝ => (1 + (-(2 * (10 - S + S * a ^ 2) / 10)) * v + (a ^ 2) * v ^ 2) ^ 5)
      MeasureTheory.volume tau 1 := by
    apply Continuous.intervalIntegrable
    fun_prop
  have h0 := EInt.int_0_5 tau 1 (-(2 * (10 - S + S * a ^ 2) / 10)) (a ^ 2 * (1 - eta ^ 2))
  have h1 := EInt.int_0_5 tau 1 (-(2 * (10 - S + S * a ^ 2) / 10)) (a ^ 2)
  simp only [pow_zero, one_mul] at h0 h1
  rw [intervalIntegral.integral_add hi0 hi1, h0, h1]
  norm_num
  ring

end SendovN.EmajEq

#print axioms SendovN.EmajEq.Emaj10_eq
#print axioms SendovN.EmajEq.EmajTau11_eq
