import Mathlib
import SendovNEmajEq
import Sendov911Box10_40

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D10-6 PROTOTYPE: the box-40 `hEq` identity (generated; perf probe)

Generated by `emit_emajeq1011.py`; do not hand-edit.  The degree-10 certificate
closed form `P(S₄₀, λ₄₀)(a, η)` — exactly the quantity `row_nonpos` proves
nonpositive — under the affine pullback `a = 2/5 + U/100`, `η = (3819/20000)V`
of box 40, equals the shipped monomial table `Adata/Dscale` of
`Sendov911Box10_40` (whose Bernstein positivity is kernel-checked).

The full Adata table was REGENERATED from `certificate_polynomial(S₄₀, λ₄₀)`
by the emitter and matched the shipped file integer-for-integer before this
file was written, so the identity below is known-true; the only question this
file answers is elaboration cost (`ring` at bidegree (10,10) with ~200-digit
rationals).

Row-40 constants (verifier arithmetic):
`S₄₀ = 1285225959841307509678415398809438905321/198810000000000000000000000000000000000`, `λ₄₀ = 1227/1250`, `Y₄₀ = 3819/20000`.
-/

namespace SendovN.BoxEq10

theorem box10_40_eq (U V : ℝ) :
    (1 - (2/5 + (1/100) * U)) / 10 + ((3819/20000) * V) ^ 2 / 20
      - MidChainN.hh 9 (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) (2/5 + (1/100) * U) ((3819/20000) * V) ^ 5
          / (10 * (1227/1250 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) (2/5 + (1/100) * U)
          ((3819/20000) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_40.tab Sendov911Box10_40.Adata k l : ℝ)
          / (Sendov911Box10_40.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_40.tab, Sendov911Box10_40.Adata, Sendov911Box10_40.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

end SendovN.BoxEq10

#print axioms SendovN.BoxEq10.box10_40_eq
