import Mathlib
import SendovNEmajEq
import SendovNRows10
import SendovNCoverGrid
import Sendov911Box10_40
import Sendov911Box10_41
import Sendov911Box10_42
import Sendov911Box10_43
import Sendov911Box10_44
import Sendov911Box10_45
import Sendov911Box10_46
import Sendov911Box10_47
import Sendov911Box10_48
import Sendov911Box10_49

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D10-6/7 assembly chunk A (rows 40–49; generated by
emit_assembly1011.py, do not hand-edit)

Per row: the `Box` value, the hEq identity against the shipped monomial table
(regenerated from the verifier arithmetic and matched integer-for-integer
before emission), and the row reduction `red_i` (`row_nonpos` → pullback).
-/

namespace SendovN.Red10A

open Finset Sendov911Capstone

/-! ### Row 40: `a ∈ [2/5, 41/100]`, S = 1285225959841307509678415398809438905321/198810000000000000000000000000000000000, λ = 1227/1250, Y = 3819/20000 -/

noncomputable def box_40 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_40.tab Sendov911Box10_40.Adata
  D := (Sendov911Box10_40.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_40.Dscale]

theorem eq_40 (U V : ℝ) :
    (1 - ((2/5 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((3819/20000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) ((2/5 : ℝ) + (1/100) * U) ((3819/20000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (1227/1250 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) ((2/5 : ℝ) + (1/100) * U) ((3819/20000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_40.tab Sendov911Box10_40.Adata k l : ℝ)
          / (Sendov911Box10_40.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_40.tab, Sendov911Box10_40.Adata, Sendov911Box10_40.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_40 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (2/5 : ℝ) ≤ a) (h1 : a ≤ (41/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_40 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_40 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_40 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (1227/1250 : ℝ) * a + ((9:ℕ):ℝ) - (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (3819/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_40
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (2/5 : ℝ)) (beta := (41/100 : ℝ))
    (S := (1285225959841307509678415398809438905321/198810000000000000000000000000000000000 : ℝ)) (lam := (1227/1250 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_40 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (2/5 : ℝ)), eta / (3819/20000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_40 (100 * (a - (2/5 : ℝ))) (eta / (3819/20000 : ℝ))
  rw [show (2/5 : ℝ) + (1/100) * (100 * (a - (2/5 : ℝ))) = a by ring] at heq
  rw [show (3819/20000 : ℝ) * (eta / (3819/20000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 41: `a ∈ [41/100, 21/50]`, S = 48527676027744395137180721073951909493681/7344356094360351562500000000000000000000, λ = 94129/100000, Y = 211/625 -/

noncomputable def box_41 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_41.tab Sendov911Box10_41.Adata
  D := (Sendov911Box10_41.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_41.Dscale]

theorem eq_41 (U V : ℝ) :
    (1 - ((41/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((211/625 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ) ((41/100 : ℝ) + (1/100) * U) ((211/625 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (94129/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ) ((41/100 : ℝ) + (1/100) * U) ((211/625 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_41.tab Sendov911Box10_41.Adata k l : ℝ)
          / (Sendov911Box10_41.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_41.tab, Sendov911Box10_41.Adata, Sendov911Box10_41.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_41 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (41/100 : ℝ) ≤ a) (h1 : a ≤ (21/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_41 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_41 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_41 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (94129/100000 : ℝ) * a + ((9:ℕ):ℝ) - (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (211/625 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_41
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (41/100 : ℝ)) (beta := (21/50 : ℝ))
    (S := (48527676027744395137180721073951909493681/7344356094360351562500000000000000000000 : ℝ)) (lam := (94129/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_41 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (41/100 : ℝ)), eta / (211/625 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_41 (100 * (a - (41/100 : ℝ))) (eta / (211/625 : ℝ))
  rw [show (41/100 : ℝ) + (1/100) * (100 * (a - (41/100 : ℝ))) = a by ring] at heq
  rw [show (211/625 : ℝ) * (eta / (211/625 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 42: `a ∈ [21/50, 43/100]`, S = 3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000, λ = 23321/25000, Y = 3603/10000 -/

noncomputable def box_42 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_42.tab Sendov911Box10_42.Adata
  D := (Sendov911Box10_42.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_42.Dscale]

theorem eq_42 (U V : ℝ) :
    (1 - ((21/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((3603/10000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ) ((21/50 : ℝ) + (1/100) * U) ((3603/10000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (23321/25000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ) ((21/50 : ℝ) + (1/100) * U) ((3603/10000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_42.tab Sendov911Box10_42.Adata k l : ℝ)
          / (Sendov911Box10_42.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_42.tab, Sendov911Box10_42.Adata, Sendov911Box10_42.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_42 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (21/50 : ℝ) ≤ a) (h1 : a ≤ (43/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_42 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_42 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_42 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (23321/25000 : ℝ) * a + ((9:ℕ):ℝ) - (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (3603/10000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_42
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (21/50 : ℝ)) (beta := (43/100 : ℝ))
    (S := (3227727202263078891725414844139898620477331761/488122742250000000000000000000000000000000000 : ℝ)) (lam := (23321/25000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_42 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (21/50 : ℝ)), eta / (3603/10000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_42 (100 * (a - (21/50 : ℝ))) (eta / (3603/10000 : ℝ))
  rw [show (21/50 : ℝ) + (1/100) * (100 * (a - (21/50 : ℝ))) = a by ring] at heq
  rw [show (3603/10000 : ℝ) * (eta / (3603/10000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 43: `a ∈ [43/100, 11/25]`, S = 1325252449779213667687805207654071/200078124180436134338378906250000, λ = 9239/10000, Y = 4783/12500 -/

noncomputable def box_43 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_43.tab Sendov911Box10_43.Adata
  D := (Sendov911Box10_43.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_43.Dscale]

theorem eq_43 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((4783/12500 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((4783/12500 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (9239/10000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((4783/12500 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_43.tab Sendov911Box10_43.Adata k l : ℝ)
          / (Sendov911Box10_43.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_43.tab, Sendov911Box10_43.Adata, Sendov911Box10_43.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_43 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (43/100 : ℝ) ≤ a) (h1 : a ≤ (11/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_43 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_43 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_43 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (9239/10000 : ℝ) * a + ((9:ℕ):ℝ) - (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (4783/12500 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_43
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
    (S := (1325252449779213667687805207654071/200078124180436134338378906250000 : ℝ)) (lam := (9239/10000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_43 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (43/100 : ℝ)), eta / (4783/12500 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_43 (100 * (a - (43/100 : ℝ))) (eta / (4783/12500 : ℝ))
  rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
  rw [show (4783/12500 : ℝ) * (eta / (4783/12500 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 44: `a ∈ [11/25, 9/20]`, S = 21843767275469178925856031398836081/3289068380160000000000000000000000, λ = 18289/20000, Y = 4047/10000 -/

noncomputable def box_44 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_44.tab Sendov911Box10_44.Adata
  D := (Sendov911Box10_44.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_44.Dscale]

theorem eq_44 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((4047/10000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((4047/10000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (18289/20000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((4047/10000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_44.tab Sendov911Box10_44.Adata k l : ℝ)
          / (Sendov911Box10_44.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_44.tab, Sendov911Box10_44.Adata, Sendov911Box10_44.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_44 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (11/25 : ℝ) ≤ a) (h1 : a ≤ (9/20 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_44 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_44 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_44 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (18289/20000 : ℝ) * a + ((9:ℕ):ℝ) - (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (4047/10000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_44
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
    (S := (21843767275469178925856031398836081/3289068380160000000000000000000000 : ℝ)) (lam := (18289/20000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_44 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (11/25 : ℝ)), eta / (4047/10000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_44 (100 * (a - (11/25 : ℝ))) (eta / (4047/10000 : ℝ))
  rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
  rw [show (4047/10000 : ℝ) * (eta / (4047/10000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 45: `a ∈ [9/20, 23/50]`, S = 51753948273724402273592864064344681657521/7763950332641601562500000000000000000000, λ = 5653/6250, Y = 10663/25000 -/

noncomputable def box_45 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_45.tab Sendov911Box10_45.Adata
  D := (Sendov911Box10_45.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_45.Dscale]

theorem eq_45 (U V : ℝ) :
    (1 - ((9/20 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((10663/25000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ) ((9/20 : ℝ) + (1/100) * U) ((10663/25000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (5653/6250 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ) ((9/20 : ℝ) + (1/100) * U) ((10663/25000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_45.tab Sendov911Box10_45.Adata k l : ℝ)
          / (Sendov911Box10_45.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_45.tab, Sendov911Box10_45.Adata, Sendov911Box10_45.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_45 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (9/20 : ℝ) ≤ a) (h1 : a ≤ (23/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_45 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_45 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_45 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (5653/6250 : ℝ) * a + ((9:ℕ):ℝ) - (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (10663/25000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_45
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (9/20 : ℝ)) (beta := (23/50 : ℝ))
    (S := (51753948273724402273592864064344681657521/7763950332641601562500000000000000000000 : ℝ)) (lam := (5653/6250 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_45 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (9/20 : ℝ)), eta / (10663/25000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_45 (100 * (a - (9/20 : ℝ))) (eta / (10663/25000 : ℝ))
  rw [show (9/20 : ℝ) + (1/100) * (100 * (a - (9/20 : ℝ))) = a by ring] at heq
  rw [show (10663/25000 : ℝ) * (eta / (10663/25000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 46: `a ∈ [23/50, 47/100]`, S = 54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000, λ = 89399/100000, Y = 44809/100000 -/

noncomputable def box_46 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_46.tab Sendov911Box10_46.Adata
  D := (Sendov911Box10_46.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_46.Dscale]

theorem eq_46 (U V : ℝ) :
    (1 - ((23/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((44809/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ) ((23/50 : ℝ) + (1/100) * U) ((44809/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (89399/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ) ((23/50 : ℝ) + (1/100) * U) ((44809/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_46.tab Sendov911Box10_46.Adata k l : ℝ)
          / (Sendov911Box10_46.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_46.tab, Sendov911Box10_46.Adata, Sendov911Box10_46.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_46 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (23/50 : ℝ) ≤ a) (h1 : a ≤ (47/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_46 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_46 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_46 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (89399/100000 : ℝ) * a + ((9:ℕ):ℝ) - (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (44809/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_46
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (23/50 : ℝ)) (beta := (47/100 : ℝ))
    (S := (54839719384035651600357763797498830688779087/8187495750000000000000000000000000000000000 : ℝ)) (lam := (89399/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_46 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (23/50 : ℝ)), eta / (44809/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_46 (100 * (a - (23/50 : ℝ))) (eta / (44809/100000 : ℝ))
  rw [show (23/50 : ℝ) + (1/100) * (100 * (a - (23/50 : ℝ))) = a by ring] at heq
  rw [show (44809/100000 : ℝ) * (eta / (44809/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 47: `a ∈ [47/100, 12/25]`, S = 820262372838406446081815244415662001/121736423112452030181884765625000000, λ = 11037/12500, Y = 9389/20000 -/

noncomputable def box_47 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_47.tab Sendov911Box10_47.Adata
  D := (Sendov911Box10_47.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_47.Dscale]

theorem eq_47 (U V : ℝ) :
    (1 - ((47/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((9389/20000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ) ((47/100 : ℝ) + (1/100) * U) ((9389/20000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (11037/12500 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ) ((47/100 : ℝ) + (1/100) * U) ((9389/20000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_47.tab Sendov911Box10_47.Adata k l : ℝ)
          / (Sendov911Box10_47.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_47.tab, Sendov911Box10_47.Adata, Sendov911Box10_47.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_47 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (47/100 : ℝ) ≤ a) (h1 : a ≤ (12/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_47 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_47 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_47 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (11037/12500 : ℝ) * a + ((9:ℕ):ℝ) - (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (9389/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_47
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (47/100 : ℝ)) (beta := (12/25 : ℝ))
    (S := (820262372838406446081815244415662001/121736423112452030181884765625000000 : ℝ)) (lam := (11037/12500 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_47 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (47/100 : ℝ)), eta / (9389/20000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_47 (100 * (a - (47/100 : ℝ))) (eta / (9389/20000 : ℝ))
  rw [show (47/100 : ℝ) + (1/100) * (100 * (a - (47/100 : ℝ))) = a by ring] at heq
  rw [show (9389/20000 : ℝ) * (eta / (9389/20000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 48: `a ∈ [12/25, 49/100]`, S = 3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000, λ = 87139/100000, Y = 2453/5000 -/

noncomputable def box_48 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_48.tab Sendov911Box10_48.Adata
  D := (Sendov911Box10_48.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_48.Dscale]

theorem eq_48 (U V : ℝ) :
    (1 - ((12/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((2453/5000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ) ((12/25 : ℝ) + (1/100) * U) ((2453/5000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (87139/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ) ((12/25 : ℝ) + (1/100) * U) ((2453/5000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_48.tab Sendov911Box10_48.Adata k l : ℝ)
          / (Sendov911Box10_48.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_48.tab, Sendov911Box10_48.Adata, Sendov911Box10_48.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_48 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (12/25 : ℝ) ≤ a) (h1 : a ≤ (49/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_48 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_48 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_48 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (87139/100000 : ℝ) * a + ((9:ℕ):ℝ) - (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (2453/5000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_48
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (12/25 : ℝ)) (beta := (49/100 : ℝ))
    (S := (3596519564256660945047147216294166230985054961/529943420250000000000000000000000000000000000 : ℝ)) (lam := (87139/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_48 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (12/25 : ℝ)), eta / (2453/5000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_48 (100 * (a - (12/25 : ℝ))) (eta / (2453/5000 : ℝ))
  rw [show (12/25 : ℝ) + (1/100) * (100 * (a - (12/25 : ℝ))) = a by ring] at heq
  rw [show (2453/5000 : ℝ) * (eta / (2453/5000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 49: `a ∈ [49/100, 1/2]`, S = 267677016554400809/39109017600000000, λ = 42963/50000, Y = 25577/50000 -/

noncomputable def box_49 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_49.tab Sendov911Box10_49.Adata
  D := (Sendov911Box10_49.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_49.Dscale]

theorem eq_49 (U V : ℝ) :
    (1 - ((49/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((25577/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (267677016554400809/39109017600000000 : ℝ) ((49/100 : ℝ) + (1/100) * U) ((25577/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (42963/50000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (267677016554400809/39109017600000000 : ℝ) ((49/100 : ℝ) + (1/100) * U) ((25577/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_49.tab Sendov911Box10_49.Adata k l : ℝ)
          / (Sendov911Box10_49.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_49.tab, Sendov911Box10_49.Adata, Sendov911Box10_49.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_49 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (49/100 : ℝ) ≤ a) (h1 : a ≤ (1/2 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_49 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (267677016554400809/39109017600000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_49 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_49 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (267677016554400809/39109017600000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (42963/50000 : ℝ) * a + ((9:ℕ):ℝ) - (267677016554400809/39109017600000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (25577/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_49
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (49/100 : ℝ)) (beta := (1/2 : ℝ))
    (S := (267677016554400809/39109017600000000 : ℝ)) (lam := (42963/50000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_49 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (49/100 : ℝ)), eta / (25577/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_49 (100 * (a - (49/100 : ℝ))) (eta / (25577/50000 : ℝ))
  rw [show (49/100 : ℝ) + (1/100) * (100 * (a - (49/100 : ℝ))) = a by ring] at heq
  rw [show (25577/50000 : ℝ) * (eta / (25577/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

noncomputable def chunk : List Box :=
  [box_40, box_41, box_42, box_43, box_44, box_45, box_46, box_47, box_48, box_49]

theorem chunkPos : CoveringPositive chunk := by
  unfold chunk
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_40.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_41.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_42.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_43.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_44.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_45.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_46.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_47.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_48.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_49.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

end SendovN.Red10A

#print axioms SendovN.Red10A.eq_40
#print axioms SendovN.Red10A.red_40
#print axioms SendovN.Red10A.eq_41
#print axioms SendovN.Red10A.red_41
#print axioms SendovN.Red10A.eq_42
#print axioms SendovN.Red10A.red_42
#print axioms SendovN.Red10A.eq_43
#print axioms SendovN.Red10A.red_43
#print axioms SendovN.Red10A.eq_44
#print axioms SendovN.Red10A.red_44
#print axioms SendovN.Red10A.eq_45
#print axioms SendovN.Red10A.red_45
#print axioms SendovN.Red10A.eq_46
#print axioms SendovN.Red10A.red_46
#print axioms SendovN.Red10A.eq_47
#print axioms SendovN.Red10A.red_47
#print axioms SendovN.Red10A.eq_48
#print axioms SendovN.Red10A.red_48
#print axioms SendovN.Red10A.eq_49
#print axioms SendovN.Red10A.red_49
#print axioms SendovN.Red10A.chunkPos
