import Mathlib
import SendovNEmajEq
import SendovNRows11
import SendovNCoverGrid
import Sendov911Box11_39_0
import Sendov911Box11_39_1
import Sendov911Box11_39_2
import Sendov911Box11_39_3
import Sendov911Box11_39_4
import Sendov911Box11_39_5
import Sendov911Box11_39_6
import Sendov911Box11_39_7
import Sendov911Box11_39_8
import Sendov911Box11_39_9

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D11-6/7 assembly for row 39 (generated by emit_assembly1011.py; do not
hand-edit)

`a ∈ [39/100, 2/5]`, S = 2238747526985178370188295489/286759826812744140625000000, λ = 21513/25000, Y = 25471/50000.  Per η-strip j: the `Box`
value, the hEq identity against the shipped `boxes11v2` table (regenerated
from the verifier arithmetic — `split_cert` at the box's recorded τ — and
matched integer-for-integer before emission), the strip membership, and the
row reduction `red_39` (strip cover → `split_row_nonpos` → pullback).
-/

namespace SendovN.Red11_39

open Finset Sendov911Capstone

/-- Stage 1: the τ = 1 certificate closed form, evaluated
(coefficients from the verifier's own `split_cert` arithmetic). -/
theorem Peq_39_t0 (a eta : ℝ) :
    (1 - a) / 11 + eta ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) a eta ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) a eta (1 : ℝ)
    = (4876437860923833515624484532509638735114761781570982327849279089810450133044573824198977143322403114329628884828750316895246292730583551/57358161507518778670864401404771211172077777977660667479864483358684666691740261512677534483373165130615234375000000000000000000000000000 : ℝ)
      + (1/22 : ℝ) * eta ^ 2
      + (-1/11 : ℝ) * a
      + (337940457941509999908642867924107735074127125489078352138401215524519566204540858771707809711520988453574240171249683104753707269416449/11471632301503755734172880280954242234415555595532133495972896671736933338348052302535506896674633026123046875000000000000000000000000000 : ℝ) * a ^ 2
      + (419828725559657496512253840726127389012265141992043052431074292658233387806223988025739684276014279516272641/8000864297490875061115117502078544009370364930265606684400836456916294991970062255859375000000000000000000000 : ℝ) * a ^ 2 * eta ^ 2
      + (-6622375322592392464215500825195883357139464556024887346626901651310184597514085233119073863924234244798817923/17750171170001687804352702968569683468006412986606168402659022831358015537261962890625000000000000000000000000 : ℝ) * a ^ 3 * eta ^ 2
      + (-337940457941509999908642867924107735074127125489078352138401215524519566204540858771707809711520988453574240171249683104753707269416449/5735816150751877867086440140477121117207777797766066747986448335868466669174026151267753448337316513061523437500000000000000000000000000 : ℝ) * a ^ 4
      + (-419828725559657496512253840726127389012265141992043052431074292658233387806223988025739684276014279516272641/2000216074372718765278779375519636002342591232566401671100209114229073747992515563964843750000000000000000000 : ℝ) * a ^ 4 * eta ^ 2
      + (-1464407212506356068801418603132337616674038061414178498967902065319489308845515169/2063302865361803781122548660276194709695118945091962814331054687500000000000000000 : ℝ) * a ^ 4 * eta ^ 3
      + (-521559803400492061405155743665034649594995307954648551852971980709503957283015169/2790092456958933326721047329221368826779325900133699178695678710937500000000000000 : ℝ) * a ^ 4 * eta ^ 4
      + (1722356226153919090736855738722741517620897549965301501897841258652361375483343902914727210692792843969397641/1479180930833473983696058580714140289000534415550514033554918569279834628105163574218750000000000000000000000 : ℝ) * a ^ 5 * eta ^ 2
      + (-554425988396168718921422736268444502500238592252566149202788392768353102889882780543/1179030208778173589212884948729254119825782254338264465332031250000000000000000000000 : ℝ) * a ^ 5 * eta ^ 4
      + (337940457941509999908642867924107735074127125489078352138401215524519566204540858771707809711520988453574240171249683104753707269416449/5735816150751877867086440140477121117207777797766066747986448335868466669174026151267753448337316513061523437500000000000000000000000000 : ℝ) * a ^ 6
      + (419828725559657496512253840726127389012265141992043052431074292658233387806223988025739684276014279516272641/1333477382915145843519186250346424001561727488377601114066806076152715831995010375976562500000000000000000000 : ℝ) * a ^ 6 * eta ^ 2
      + (3807806637875011466107555720486325815456273373583282925123981853516909088645920507/2063302865361803781122548660276194709695118945091962814331054687500000000000000000 : ℝ) * a ^ 6 * eta ^ 3
      + (521559803400492061405155743665034649594995307954648551852971980709503957283015169/930030818986311108907015776407122942259775300044566392898559570312500000000000000 : ℝ) * a ^ 6 * eta ^ 4
      + (-3226766575695154055753121553126723418965110966033247363/24669359482102504007052630186080932617187500000000000000 : ℝ) * a ^ 6 * eta ^ 5
      + (647941915266837399646426364372538492255134644927749121/1945943745307727618580318521708250045776367187500000000 : ℝ) * a ^ 6 * eta ^ 6
      + (-4306069351947681003241611369933005320218803291012397455578880511185989266715783290293895723474710319017567923/2958361861666947967392117161428280578001068831101028067109837138559669256210327148437500000000000000000000000 : ℝ) * a ^ 7 * eta ^ 2
      + (1503088255130668051127800640444949295221682183005832299970958826762395734450898341629/1179030208778173589212884948729254119825782254338264465332031250000000000000000000000 : ℝ) * a ^ 7 * eta ^ 4
      + (8448230599217239166721055042795419231785358514456648313441/5550605883473063401586841791868209838867187500000000000000 : ℝ) * a ^ 7 * eta ^ 6
      + (-337940457941509999908642867924107735074127125489078352138401215524519566204540858771707809711520988453574240171249683104753707269416449/11471632301503755734172880280954242234415555595532133495972896671736933338348052302535506896674633026123046875000000000000000000000000000 : ℝ) * a ^ 8
      + (-419828725559657496512253840726127389012265141992043052431074292658233387806223988025739684276014279516272641/2000216074372718765278779375519636002342591232566401671100209114229073747992515563964843750000000000000000000 : ℝ) * a ^ 8 * eta ^ 2
      + (-3400367177394014846398238180669907863896718762768938322580631412442537750755295507/2063302865361803781122548660276194709695118945091962814331054687500000000000000000 : ℝ) * a ^ 8 * eta ^ 3
      + (-521559803400492061405155743665034649594995307954648551852971980709503957283015169/930030818986311108907015776407122942259775300044566392898559570312500000000000000 : ℝ) * a ^ 8 * eta ^ 4
      + (3018954738822991457887423104696925889363060184783247363/12334679741051252003526315093040466308593750000000000000 : ℝ) * a ^ 8 * eta ^ 5
      + (-647941915266837399646426364372538492255134644927749121/972971872653863809290159260854125022888183593750000000 : ℝ) * a ^ 8 * eta ^ 6
      + (419585877034993901195354768477/430139740219116210937500000000 : ℝ) * a ^ 8 * eta ^ 7
      + (-804948392921457667063295489/2714388227857928466796875000 : ℝ) * a ^ 8 * eta ^ 8
      + (11200593100278408691156933131337083682842236004171513540304218738894976106492574105820517554964688818380828769/13312628377501265853264527226427262601004809739954626301994267123518511652946472167968750000000000000000000000 : ℝ) * a ^ 9 * eta ^ 2
      + (-1382084457750910592550198791147477712150038494446622594856555099731450910232148341629/1179030208778173589212884948729254119825782254338264465332031250000000000000000000000 : ℝ) * a ^ 9 * eta ^ 4
      + (-72203403331150215405670081566795963131910950476545381695969/24977726475628785307140788063406944274902343750000000000000 : ℝ) * a ^ 9 * eta ^ 6
      + (-31726872049652129935353511158993271/22298444132958984375000000000000000 : ℝ) * a ^ 9 * eta ^ 8
      + (337940457941509999908642867924107735074127125489078352138401215524519566204540858771707809711520988453574240171249683104753707269416449/57358161507518778670864401404771211172077777977660667479864483358684666691740261512677534483373165130615234375000000000000000000000000000 : ℝ) * a ^ 10
      + (419828725559657496512253840726127389012265141992043052431074292658233387806223988025739684276014279516272641/8000864297490875061115117502078544009370364930265606684400836456916294991970062255859375000000000000000000000 : ℝ) * a ^ 10 * eta ^ 2
      + (3097213868027442497950497880652180612854338960903360160190402919610353912864670507/6189908596085411343367645980828584129085356835275888442993164062500000000000000000 : ℝ) * a ^ 10 * eta ^ 3
      + (521559803400492061405155743665034649594995307954648551852971980709503957283015169/2790092456958933326721047329221368826779325900133699178695678710937500000000000000 : ℝ) * a ^ 10 * eta ^ 4
      + (-8550901846243450884860662683973199044126778210599742089/74008078446307512021157890558242797851562500000000000000 : ℝ) * a ^ 10 * eta ^ 5
      + (647941915266837399646426364372538492255134644927749121/1945943745307727618580318521708250045776367187500000000 : ℝ) * a ^ 10 * eta ^ 6
      + (-1212911903793294234103642430431/1290419220657348632812500000000 : ℝ) * a ^ 10 * eta ^ 7
      + (804948392921457667063295489/2714388227857928466796875000 : ℝ) * a ^ 10 * eta ^ 8
      + (-147/250 : ℝ) * a ^ 10 * eta ^ 9
      + (25000/236643 : ℝ) * a ^ 10 * eta ^ 10
      + (-3322902071555940858076775338111959999697289989779759636843767924447618950357824131396635063493936393236317923/17750171170001687804352702968569683468006412986606168402659022831358015537261962890625000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 2
      + (428859190987633393725828163403163598289528889254488875118658103237408278671132780543/1179030208778173589212884948729254119825782254338264465332031250000000000000000000000 : ℝ) * a ^ 11 * eta ^ 4
      + (68975760946633595007015273421835701014057385260480928570969/49955452951257570614281576126813888549804687500000000000000 : ℝ) * a ^ 11 * eta ^ 6
      + (126641235764338231181286954357997/91763144580078125000000000000000 : ℝ) * a ^ 11 * eta ^ 8
      + (1073407/1900800 : ℝ) * a ^ 11 * eta ^ 10 := by
  rw [EmajEq.EmajTau11_eq]
  unfold MidChainN.hh
  push_cast
  norm_num
  ring

/-! ### Strip 0: `η ∈ [0, 25471/500000]`, τ = 1 -/

noncomputable def box_39_0 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_0.tab Sendov911Box11_39_0.Adata
  D := (Sendov911Box11_39_0.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_0.Dscale]

theorem eq_39_0 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((0 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_0.tab Sendov911Box11_39_0.Adata k l : ℝ)
          / (Sendov911Box11_39_0.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_0.tab, Sendov911Box11_39_0.Adata, Sendov911Box11_39_0.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 1: `η ∈ [25471/500000, 25471/250000]`, τ = 1 -/

noncomputable def box_39_1 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_1.tab Sendov911Box11_39_1.Adata
  D := (Sendov911Box11_39_1.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_1.Dscale]

theorem eq_39_1 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((25471/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/500000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_1.tab Sendov911Box11_39_1.Adata k l : ℝ)
          / (Sendov911Box11_39_1.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_1.tab, Sendov911Box11_39_1.Adata, Sendov911Box11_39_1.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 2: `η ∈ [25471/250000, 76413/500000]`, τ = 1 -/

noncomputable def box_39_2 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_2.tab Sendov911Box11_39_2.Adata
  D := (Sendov911Box11_39_2.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_2.Dscale]

theorem eq_39_2 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((25471/250000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/250000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/250000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_2.tab Sendov911Box11_39_2.Adata k l : ℝ)
          / (Sendov911Box11_39_2.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_2.tab, Sendov911Box11_39_2.Adata, Sendov911Box11_39_2.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 3: `η ∈ [76413/500000, 25471/125000]`, τ = 1 -/

noncomputable def box_39_3 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_3.tab Sendov911Box11_39_3.Adata
  D := (Sendov911Box11_39_3.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_3.Dscale]

theorem eq_39_3 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((76413/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((76413/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((76413/500000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_3.tab Sendov911Box11_39_3.Adata k l : ℝ)
          / (Sendov911Box11_39_3.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_3.tab, Sendov911Box11_39_3.Adata, Sendov911Box11_39_3.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 4: `η ∈ [25471/125000, 25471/100000]`, τ = 1 -/

noncomputable def box_39_4 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_4.tab Sendov911Box11_39_4.Adata
  D := (Sendov911Box11_39_4.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_4.Dscale]

theorem eq_39_4 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((25471/125000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/125000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/125000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_4.tab Sendov911Box11_39_4.Adata k l : ℝ)
          / (Sendov911Box11_39_4.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_4.tab, Sendov911Box11_39_4.Adata, Sendov911Box11_39_4.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 5: `η ∈ [25471/100000, 76413/250000]`, τ = 1 -/

noncomputable def box_39_5 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_5.tab Sendov911Box11_39_5.Adata
  D := (Sendov911Box11_39_5.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_5.Dscale]

theorem eq_39_5 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((25471/100000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/100000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/100000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_5.tab Sendov911Box11_39_5.Adata k l : ℝ)
          / (Sendov911Box11_39_5.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_5.tab, Sendov911Box11_39_5.Adata, Sendov911Box11_39_5.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 6: `η ∈ [76413/250000, 178297/500000]`, τ = 1 -/

noncomputable def box_39_6 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_6.tab Sendov911Box11_39_6.Adata
  D := (Sendov911Box11_39_6.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_6.Dscale]

theorem eq_39_6 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((76413/250000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((76413/250000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((76413/250000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_6.tab Sendov911Box11_39_6.Adata k l : ℝ)
          / (Sendov911Box11_39_6.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_6.tab, Sendov911Box11_39_6.Adata, Sendov911Box11_39_6.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 7: `η ∈ [178297/500000, 25471/62500]`, τ = 1 -/

noncomputable def box_39_7 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_7.tab Sendov911Box11_39_7.Adata
  D := (Sendov911Box11_39_7.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_7.Dscale]

theorem eq_39_7 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((178297/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((178297/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((178297/500000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_7.tab Sendov911Box11_39_7.Adata k l : ℝ)
          / (Sendov911Box11_39_7.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_7.tab, Sendov911Box11_39_7.Adata, Sendov911Box11_39_7.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 8: `η ∈ [25471/62500, 229239/500000]`, τ = 1 -/

noncomputable def box_39_8 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_8.tab Sendov911Box11_39_8.Adata
  D := (Sendov911Box11_39_8.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_8.Dscale]

theorem eq_39_8 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((25471/62500 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/62500 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((25471/62500 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_8.tab Sendov911Box11_39_8.Adata k l : ℝ)
          / (Sendov911Box11_39_8.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_8.tab, Sendov911Box11_39_8.Adata, Sendov911Box11_39_8.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 9: `η ∈ [229239/500000, 25471/50000]`, τ = 1 -/

noncomputable def box_39_9 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_39_9.tab Sendov911Box11_39_9.Adata
  D := (Sendov911Box11_39_9.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_39_9.Dscale]

theorem eq_39_9 (U V : ℝ) :
    (1 - ((39/100 : ℝ) + (1/100) * U)) / 11 + ((229239/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((229239/500000 : ℝ) + (25471/500000 : ℝ) * V) ^ 5 / (11 * (21513/25000 : ℝ))
      - Split11.EmajTau CTab11.c11 (2238747526985178370188295489/286759826812744140625000000 : ℝ) ((39/100 : ℝ) + (1/100) * U) ((229239/500000 : ℝ) + (25471/500000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_39_9.tab Sendov911Box11_39_9.Adata k l : ℝ)
          / (Sendov911Box11_39_9.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_39_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_39_9.tab, Sendov911Box11_39_9.Adata, Sendov911Box11_39_9.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

noncomputable def row_39 : List Box :=
  [box_39_0, box_39_1, box_39_2, box_39_3, box_39_4, box_39_5, box_39_6, box_39_7, box_39_8, box_39_9]

theorem mem_39_0 : box_39_0 ∈ row_39 :=
  List.Mem.head _

theorem mem_39_1 : box_39_1 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.head _)

theorem mem_39_2 : box_39_2 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))

theorem mem_39_3 : box_39_3 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))

theorem mem_39_4 : box_39_4 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))

theorem mem_39_5 : box_39_5 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))

theorem mem_39_6 : box_39_6 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))

theorem mem_39_7 : box_39_7 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))

theorem mem_39_8 : box_39_8 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))))

theorem mem_39_9 : box_39_9 ∈ row_39 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))))

theorem rowPos_39 : CoveringPositive row_39 := by
  unfold row_39
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_0.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_1.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_2.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_3.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_4.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_5.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_6.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_7.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_8.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_39_9.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

theorem red_39 (mu : ℂ) (Df : Fin 10 → ℂ) (rr : Fin 10 → ℝ) (a eta sig : ℝ)
    (h0 : (39/100 : ℝ) ≤ a) (h1 : a ≤ (2/5 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (10:ℝ) ≤ 10 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (563/1000 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (11:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0) (hY1 : ∀ j, ‖mu + Df j‖ ≤ 1)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 10 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 11) :
    ∃ b ∈ row_39, ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly b U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (2238747526985178370188295489/286759826812744140625000000 : ℝ) := by
    rw [hsigeq]
    exact Rows11.sigma_row_39 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows11.L_row_39 h0 h1
  have hc := CTab11.cTable11 Df eta heta0 hz hD2
  have hloc' : ((10:ℕ):ℝ) ≤ ((10:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (2238747526985178370188295489/286759826812744140625000000 : ℝ) * a ^ 2 - ((10:ℕ):ℝ) * (21513/25000 : ℝ) * a + ((10:ℕ):ℝ) - (2238747526985178370188295489/286759826812744140625000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (25471/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows11.Y_row_39
  obtain ⟨j, hj, hja, hjb⟩ := Cover.cover_grid (by norm_num : (0:ℝ) < (25471/500000 : ℝ)) 0 10
    (by norm_num) eta heta0 (by push_cast; linarith)
  interval_cases j
  · -- strip j = 0, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_0, mem_39_0, 100 * (a - (39/100 : ℝ)), (eta - (0 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_0 (100 * (a - (39/100 : ℝ))) ((eta - (0 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (0 : ℝ) + (25471/500000 : ℝ) * ((eta - (0 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 1, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_1, mem_39_1, 100 * (a - (39/100 : ℝ)), (eta - (25471/500000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_1 (100 * (a - (39/100 : ℝ))) ((eta - (25471/500000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (25471/500000 : ℝ) + (25471/500000 : ℝ) * ((eta - (25471/500000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 2, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_2, mem_39_2, 100 * (a - (39/100 : ℝ)), (eta - (25471/250000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_2 (100 * (a - (39/100 : ℝ))) ((eta - (25471/250000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (25471/250000 : ℝ) + (25471/500000 : ℝ) * ((eta - (25471/250000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 3, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_3, mem_39_3, 100 * (a - (39/100 : ℝ)), (eta - (76413/500000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_3 (100 * (a - (39/100 : ℝ))) ((eta - (76413/500000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (76413/500000 : ℝ) + (25471/500000 : ℝ) * ((eta - (76413/500000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 4, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_4, mem_39_4, 100 * (a - (39/100 : ℝ)), (eta - (25471/125000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_4 (100 * (a - (39/100 : ℝ))) ((eta - (25471/125000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (25471/125000 : ℝ) + (25471/500000 : ℝ) * ((eta - (25471/125000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 5, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_5, mem_39_5, 100 * (a - (39/100 : ℝ)), (eta - (25471/100000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_5 (100 * (a - (39/100 : ℝ))) ((eta - (25471/100000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (25471/100000 : ℝ) + (25471/500000 : ℝ) * ((eta - (25471/100000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 6, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_6, mem_39_6, 100 * (a - (39/100 : ℝ)), (eta - (76413/250000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_6 (100 * (a - (39/100 : ℝ))) ((eta - (76413/250000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (76413/250000 : ℝ) + (25471/500000 : ℝ) * ((eta - (76413/250000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 7, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_7, mem_39_7, 100 * (a - (39/100 : ℝ)), (eta - (178297/500000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_7 (100 * (a - (39/100 : ℝ))) ((eta - (178297/500000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (178297/500000 : ℝ) + (25471/500000 : ℝ) * ((eta - (178297/500000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 8, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_8, mem_39_8, 100 * (a - (39/100 : ℝ)), (eta - (25471/62500 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_8 (100 * (a - (39/100 : ℝ))) ((eta - (25471/62500 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (25471/62500 : ℝ) + (25471/500000 : ℝ) * ((eta - (25471/62500 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 9, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (39/100 : ℝ)) (beta := (2/5 : ℝ))
      (S := (2238747526985178370188295489/286759826812744140625000000 : ℝ)) (lam := (21513/25000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_39
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_39_9, mem_39_9, 100 * (a - (39/100 : ℝ)), (eta - (229239/500000 : ℝ)) / (25471/500000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_39_9 (100 * (a - (39/100 : ℝ))) ((eta - (229239/500000 : ℝ)) / (25471/500000 : ℝ))
    rw [show (39/100 : ℝ) + (1/100) * (100 * (a - (39/100 : ℝ))) = a by ring] at heq
    rw [show (229239/500000 : ℝ) + (25471/500000 : ℝ) * ((eta - (229239/500000 : ℝ)) / (25471/500000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP

end SendovN.Red11_39

#print axioms SendovN.Red11_39.Peq_39_t0
#print axioms SendovN.Red11_39.eq_39_0
#print axioms SendovN.Red11_39.eq_39_1
#print axioms SendovN.Red11_39.eq_39_2
#print axioms SendovN.Red11_39.eq_39_3
#print axioms SendovN.Red11_39.eq_39_4
#print axioms SendovN.Red11_39.eq_39_5
#print axioms SendovN.Red11_39.eq_39_6
#print axioms SendovN.Red11_39.eq_39_7
#print axioms SendovN.Red11_39.eq_39_8
#print axioms SendovN.Red11_39.eq_39_9
#print axioms SendovN.Red11_39.rowPos_39
#print axioms SendovN.Red11_39.red_39
