import Mathlib
import SendovNBdryEq11
import SendovNRows11
import Sendov911Capstone

set_option maxHeartbeats 4000000

/-!
# D11-8: the boundary reduction (generated by emit_assembly1011.py)

`9/10 ≤ a < 1` is driven into the boundary box: σ ≤ S_b (`sigma_boundary`),
the localization key gives `10a(1−u) ≤ (1−a)(S_b(1+a)−10)`, hence
`η² ≤ Y_b²(1−a)`; substituting `x = √(1−a)`, `Y = η/x` and pulling back
`U = (25/8)x`, `V = (10/17 : ℝ)·Y`, the boundary hEq turns the nonpositive
certificate value into `x²·(box polynomial) ≤ 0`, and `x² > 0` finishes.
-/

namespace SendovN.Red11Bdry

open Finset Sendov911Capstone

noncomputable def boxB11 : Box where
  nx := 30
  ny := 10
  A := Sendov911Box11Boundary.tab Sendov911Box11Boundary.Adata
  D := (Sendov911Box11Boundary.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11Boundary.Dscale]

theorem posB11 : ∀ U V : ℝ, 0 ≤ U → U ≤ 1 → 0 ≤ V → V ≤ 1 →
    0 < Box.poly boxB11 U V :=
  fun _ _ h1 h2 h3 h4 => Sendov911Box11Boundary.box_positive h1 h2 h3 h4

theorem red_bdry (mu : ℂ) (Df : Fin 10 → ℂ) (rr : Fin 10 → ℝ) (a eta sig : ℝ)
    (h0 : (9/10 : ℝ) ≤ a) (h1 : a < 1)
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hetau : eta ^ 2 ≤ 1 - mu.re ^ 2) (hmu1 : ‖mu‖ < 1)
    (hloc : (10:ℝ) ≤ 10 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (563/1000 : ℝ) ≤ rr k)
    (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (11:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hY1 : ∀ j, ‖mu + Df j‖ ≤ 1)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 10 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 11) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly boxB11 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := h1.le
  have hsig : sig ≤ (112762515826230737435521/9363586181640625000000 : ℝ) := by
    rw [hsigeq]
    exact Rows11.sigma_boundary rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows11.L_boundary h0 ha1
  have hloc' : ((10:ℕ):ℝ) ≤ ((10:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (112762515826230737435521/9363586181640625000000 : ℝ) * a ^ 2 - ((10:ℕ):ℝ) * (17/20 : ℝ) * a + ((10:ℕ):ℝ) - (112762515826230737435521/9363586181640625000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hc := CTab11.cTable11 Df eta heta0 hz hD2
  have hP := Split11.split_row_nonpos (alpha := (9/10 : ℝ)) (beta := (1:ℝ))
    (S := (112762515826230737435521/9363586181640625000000 : ℝ)) (lam := (17/20 : ℝ)) (sigma := sig) (tau := 1) CTab11.c11
    (fun m _ => CTab11.c11_nonneg m) mu Df a eta
    (by norm_num) le_rfl (by norm_num) Rows11.lam_boundary
    (by norm_num) (by norm_num) h0 ha1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
  -- η² ≤ Y_b²(1−a)
  have hkeyP : (10:ℝ) - (112762515826230737435521/9363586181640625000000 : ℝ) + (112762515826230737435521/9363586181640625000000 : ℝ) * a ^ 2 ≤ 10 * a * mu.re := by
    push_cast at hkey
    linarith [hkey]
  have hu1 : mu.re < 1 := lt_of_le_of_lt (Complex.re_le_norm mu) hmu1
  have h9a : 10 * a * (1 - mu.re) ≤ (1 - a) * ((112762515826230737435521/9363586181640625000000 : ℝ) * (1 + a) - 10) := by
    nlinarith [hkeyP]
  have hA : 10 * a * eta ^ 2 ≤ 2 * ((1 - a) * ((112762515826230737435521/9363586181640625000000 : ℝ) * (1 + a) - 10)) := by
    nlinarith [h9a,
      mul_le_mul_of_nonneg_left hetau (by linarith : (0:ℝ) ≤ 10 * a),
      mul_nonneg (mul_nonneg (by linarith : (0:ℝ) ≤ 10 * a)
        (by linarith : (0:ℝ) ≤ 1 - mu.re)) (by linarith : (0:ℝ) ≤ 1 - mu.re),
      hlamu]
  have hxx : 10 * a * eta ^ 2 ≤ 10 * a * ((17/10 : ℝ) ^ 2 * (1 - a)) := by
    nlinarith [hA, mul_nonneg (sub_nonneg.mpr h0) (by linarith : (0:ℝ) ≤ 1 - a)]
  have heta2 : eta ^ 2 ≤ (17/10 : ℝ) ^ 2 * (1 - a) :=
    le_of_mul_le_mul_left (by linarith [hxx]) (by linarith : (0:ℝ) < 10 * a)
  -- the substitution x = √(1−a), Y = η/x
  set x := Real.sqrt (1 - a) with hxdef
  have hx2 : x ^ 2 = 1 - a := Real.sq_sqrt (by linarith)
  have hx0 : (0:ℝ) < x := Real.sqrt_pos.mpr (by linarith)
  have hxle : x ≤ 8/25 := by
    nlinarith [hx2, sq_nonneg (x - 8/25), h0]
  have hYle : eta / x ≤ (17/10 : ℝ) := by
    rw [div_le_iff₀ hx0]
    nlinarith [heta2, hx2, heta0,
      mul_nonneg (by norm_num : (0:ℝ) ≤ (17/10 : ℝ)) hx0.le]
  refine ⟨25/8 * x, (10/17 : ℝ) * (eta / x), by linarith, by linarith,
    mul_nonneg (by norm_num) (div_nonneg heta0 hx0.le), ?_, ?_⟩
  · nlinarith [hYle, div_nonneg heta0 hx0.le]
  have heq := BdryEq11.bdry11_eq (25/8 * x) ((10/17 : ℝ) * (eta / x))
  rw [show (8/25 : ℝ) * (25/8 * x) = x by ring] at heq
  rw [show ((17/10 : ℝ)) * ((10/17 : ℝ) * (eta / x)) = eta / x by ring] at heq
  rw [show (1:ℝ) - x ^ 2 = a by linarith [hx2]] at heq
  rw [show x * (eta / x) = eta by field_simp [hx0.ne']] at heq
  have heqq : Box.poly boxB11 (25/8 * x) ((10/17 : ℝ) * (eta / x))
      = ∑ k ∈ Finset.range 31, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11Boundary.tab Sendov911Box11Boundary.Adata k l : ℝ)
          / (Sendov911Box11Boundary.Dscale : ℝ)) * (25/8 * x) ^ k * ((10/17 : ℝ) * (eta / x)) ^ l := rfl
  have hs : x ^ 2 * Box.poly boxB11 (25/8 * x) ((10/17 : ℝ) * (eta / x)) ≤ 0 := by
    rw [heqq]
    exact le_of_eq_of_le heq.symm hP
  have hx2pos : (0:ℝ) < x ^ 2 := pow_pos hx0 2
  nlinarith [hs, hx2pos]

end SendovN.Red11Bdry

#print axioms SendovN.Red11Bdry.posB11
#print axioms SendovN.Red11Bdry.red_bdry
