import Mathlib
import SendovNEmajEq
import SendovNRows10
import SendovNCoverGrid
import Sendov911Box10_60
import Sendov911Box10_61
import Sendov911Box10_62
import Sendov911Box10_63
import Sendov911Box10_64
import Sendov911Box10_65
import Sendov911Box10_66
import Sendov911Box10_67
import Sendov911Box10_68
import Sendov911Box10_69

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D10-6/7 assembly chunk C (rows 60–69; generated by
emit_assembly1011.py, do not hand-edit)

Per row: the `Box` value, the hEq identity against the shipped monomial table
(regenerated from the verifier arithmetic and matched integer-for-integer
before emission), and the row reduction `red_i` (`row_nonpos` → pullback).
-/

namespace SendovN.Red10C

open Finset Sendov911Capstone

/-! ### Row 60: `a ∈ [3/5, 61/100]`, S = 123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000, λ = 2877/4000, Y = 17369/25000 -/

noncomputable def box_60 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_60.tab Sendov911Box10_60.Adata
  D := (Sendov911Box10_60.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_60.Dscale]

theorem eq_60 (U V : ℝ) :
    (1 - ((3/5 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((17369/25000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ) ((3/5 : ℝ) + (1/100) * U) ((17369/25000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (2877/4000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ) ((3/5 : ℝ) + (1/100) * U) ((17369/25000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_60.tab Sendov911Box10_60.Adata k l : ℝ)
          / (Sendov911Box10_60.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_60.tab, Sendov911Box10_60.Adata, Sendov911Box10_60.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_60 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (3/5 : ℝ) ≤ a) (h1 : a ≤ (61/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_60 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_60 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_60 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (2877/4000 : ℝ) * a + ((9:ℕ):ℝ) - (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (17369/25000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_60
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (3/5 : ℝ)) (beta := (61/100 : ℝ))
    (S := (123652549485084077170023520154852688708107903081/15468518756250000000000000000000000000000000000 : ℝ)) (lam := (2877/4000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_60 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (3/5 : ℝ)), eta / (17369/25000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_60 (100 * (a - (3/5 : ℝ))) (eta / (17369/25000 : ℝ))
  rw [show (3/5 : ℝ) + (1/100) * (100 * (a - (3/5 : ℝ))) = a by ring] at heq
  rw [show (17369/25000 : ℝ) * (eta / (17369/25000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 61: `a ∈ [61/100, 31/50]`, S = 283206953655088326810078636147578144886443/35403263854980468750000000000000000000000, λ = 72443/100000, Y = 13787/20000 -/

noncomputable def box_61 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_61.tab Sendov911Box10_61.Adata
  D := (Sendov911Box10_61.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_61.Dscale]

theorem eq_61 (U V : ℝ) :
    (1 - ((61/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((13787/20000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ) ((61/100 : ℝ) + (1/100) * U) ((13787/20000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (72443/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ) ((61/100 : ℝ) + (1/100) * U) ((13787/20000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_61.tab Sendov911Box10_61.Adata k l : ℝ)
          / (Sendov911Box10_61.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_61.tab, Sendov911Box10_61.Adata, Sendov911Box10_61.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_61 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (61/100 : ℝ) ≤ a) (h1 : a ≤ (31/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_61 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_61 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_61 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (72443/100000 : ℝ) * a + ((9:ℕ):ℝ) - (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (13787/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_61
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (61/100 : ℝ)) (beta := (31/50 : ℝ))
    (S := (283206953655088326810078636147578144886443/35403263854980468750000000000000000000000 : ℝ)) (lam := (72443/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_61 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (61/100 : ℝ)), eta / (13787/20000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_61 (100 * (a - (61/100 : ℝ))) (eta / (13787/20000 : ℝ))
  rw [show (61/100 : ℝ) + (1/100) * (100 * (a - (61/100 : ℝ))) = a by ring] at heq
  rw [show (13787/20000 : ℝ) * (eta / (13787/20000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 62: `a ∈ [31/50, 63/100]`, S = 126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000, λ = 72943/100000, Y = 34203/50000 -/

noncomputable def box_62 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_62.tab Sendov911Box10_62.Adata
  D := (Sendov911Box10_62.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_62.Dscale]

theorem eq_62 (U V : ℝ) :
    (1 - ((31/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((34203/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ) ((31/50 : ℝ) + (1/100) * U) ((34203/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (72943/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ) ((31/50 : ℝ) + (1/100) * U) ((34203/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_62.tab Sendov911Box10_62.Adata k l : ℝ)
          / (Sendov911Box10_62.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_62.tab, Sendov911Box10_62.Adata, Sendov911Box10_62.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_62 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (31/50 : ℝ) ≤ a) (h1 : a ≤ (63/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_62 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_62 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_62 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (72943/100000 : ℝ) * a + ((9:ℕ):ℝ) - (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (34203/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_62
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (31/50 : ℝ)) (beta := (63/100 : ℝ))
    (S := (126968870535545629049162617140662720288121046049/15855216806250000000000000000000000000000000000 : ℝ)) (lam := (72943/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_62 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (31/50 : ℝ)), eta / (34203/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_62 (100 * (a - (31/50 : ℝ))) (eta / (34203/50000 : ℝ))
  rw [show (31/50 : ℝ) + (1/100) * (100 * (a - (31/50 : ℝ))) = a by ring] at heq
  rw [show (34203/50000 : ℝ) * (eta / (34203/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 63: `a ∈ [63/100, 16/25]`, S = 479512097236668134355977171982721394201/59792235866189002990722656250000000000, λ = 73427/100000, Y = 33943/50000 -/

noncomputable def box_63 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_63.tab Sendov911Box10_63.Adata
  D := (Sendov911Box10_63.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_63.Dscale]

theorem eq_63 (U V : ℝ) :
    (1 - ((63/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((33943/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ) ((63/100 : ℝ) + (1/100) * U) ((33943/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (73427/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ) ((63/100 : ℝ) + (1/100) * U) ((33943/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_63.tab Sendov911Box10_63.Adata k l : ℝ)
          / (Sendov911Box10_63.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_63.tab, Sendov911Box10_63.Adata, Sendov911Box10_63.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_63 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (63/100 : ℝ) ≤ a) (h1 : a ≤ (16/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_63 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_63 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_63 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (73427/100000 : ℝ) * a + ((9:ℕ):ℝ) - (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (33943/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_63
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (63/100 : ℝ)) (beta := (16/25 : ℝ))
    (S := (479512097236668134355977171982721394201/59792235866189002990722656250000000000 : ℝ)) (lam := (73427/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_63 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (63/100 : ℝ)), eta / (33943/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_63 (100 * (a - (63/100 : ℝ))) (eta / (33943/50000 : ℝ))
  rw [show (63/100 : ℝ) + (1/100) * (100 * (a - (63/100 : ℝ))) = a by ring] at heq
  rw [show (33943/50000 : ℝ) * (eta / (33943/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 64: `a ∈ [16/25, 13/20]`, S = 2376289356287278565456649596778049121/295761945600000000000000000000000000, λ = 9237/12500, Y = 539/800 -/

noncomputable def box_64 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_64.tab Sendov911Box10_64.Adata
  D := (Sendov911Box10_64.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_64.Dscale]

theorem eq_64 (U V : ℝ) :
    (1 - ((16/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((539/800 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ) ((16/25 : ℝ) + (1/100) * U) ((539/800 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (9237/12500 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ) ((16/25 : ℝ) + (1/100) * U) ((539/800 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_64.tab Sendov911Box10_64.Adata k l : ℝ)
          / (Sendov911Box10_64.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_64.tab, Sendov911Box10_64.Adata, Sendov911Box10_64.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_64 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (16/25 : ℝ) ≤ a) (h1 : a ≤ (13/20 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_64 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_64 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_64 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (9237/12500 : ℝ) * a + ((9:ℕ):ℝ) - (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (539/800 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_64
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (16/25 : ℝ)) (beta := (13/20 : ℝ))
    (S := (2376289356287278565456649596778049121/295761945600000000000000000000000000 : ℝ)) (lam := (9237/12500 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_64 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (16/25 : ℝ)), eta / (539/800 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_64 (100 * (a - (16/25 : ℝ))) (eta / (539/800 : ℝ))
  rw [show (16/25 : ℝ) + (1/100) * (100 * (a - (16/25 : ℝ))) = a by ring] at heq
  rw [show (539/800 : ℝ) * (eta / (539/800 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 65: `a ∈ [13/20, 33/50]`, S = 8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000, λ = 74351/100000, Y = 66873/100000 -/

noncomputable def box_65 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_65.tab Sendov911Box10_65.Adata
  D := (Sendov911Box10_65.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_65.Dscale]

theorem eq_65 (U V : ℝ) :
    (1 - ((13/20 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((66873/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ) ((13/20 : ℝ) + (1/100) * U) ((66873/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (74351/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ) ((13/20 : ℝ) + (1/100) * U) ((66873/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_65.tab Sendov911Box10_65.Adata k l : ℝ)
          / (Sendov911Box10_65.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_65.tab, Sendov911Box10_65.Adata, Sendov911Box10_65.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_65 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (13/20 : ℝ) ≤ a) (h1 : a ≤ (33/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_65 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_65 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_65 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (74351/100000 : ℝ) * a + ((9:ℕ):ℝ) - (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (66873/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_65
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (13/20 : ℝ)) (beta := (33/50 : ℝ))
    (S := (8082256094290479482479497420996123733842689/1003675245666503906250000000000000000000000 : ℝ)) (lam := (74351/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_65 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (13/20 : ℝ)), eta / (66873/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_65 (100 * (a - (13/20 : ℝ))) (eta / (66873/100000 : ℝ))
  rw [show (13/20 : ℝ) + (1/100) * (100 * (a - (13/20 : ℝ))) = a by ring] at heq
  rw [show (66873/100000 : ℝ) * (eta / (66873/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 66: `a ∈ [33/50, 67/100]`, S = 134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000, λ = 37397/50000, Y = 66377/100000 -/

noncomputable def box_66 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_66.tab Sendov911Box10_66.Adata
  D := (Sendov911Box10_66.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_66.Dscale]

theorem eq_66 (U V : ℝ) :
    (1 - ((33/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((66377/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ) ((33/50 : ℝ) + (1/100) * U) ((66377/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (37397/50000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ) ((33/50 : ℝ) + (1/100) * U) ((66377/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_66.tab Sendov911Box10_66.Adata k l : ℝ)
          / (Sendov911Box10_66.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_66.tab, Sendov911Box10_66.Adata, Sendov911Box10_66.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_66 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (33/50 : ℝ) ≤ a) (h1 : a ≤ (67/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_66 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_66 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_66 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (37397/50000 : ℝ) * a + ((9:ℕ):ℝ) - (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (66377/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_66
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (33/50 : ℝ)) (beta := (67/100 : ℝ))
    (S := (134381534083280637218025619086386659285846389689/16642935056250000000000000000000000000000000000 : ℝ)) (lam := (37397/50000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_66 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (33/50 : ℝ)), eta / (66377/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_66 (100 * (a - (33/50 : ℝ))) (eta / (66377/100000 : ℝ))
  rw [show (33/50 : ℝ) + (1/100) * (100 * (a - (33/50 : ℝ))) = a by ring] at heq
  rw [show (66377/100000 : ℝ) * (eta / (66377/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 67: `a ∈ [67/100, 17/25]`, S = 27572687832360052208110089750572227/3404106973903253674507141113281250, λ = 37613/50000, Y = 65887/100000 -/

noncomputable def box_67 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_67.tab Sendov911Box10_67.Adata
  D := (Sendov911Box10_67.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_67.Dscale]

theorem eq_67 (U V : ℝ) :
    (1 - ((67/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((65887/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ) ((67/100 : ℝ) + (1/100) * U) ((65887/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (37613/50000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ) ((67/100 : ℝ) + (1/100) * U) ((65887/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_67.tab Sendov911Box10_67.Adata k l : ℝ)
          / (Sendov911Box10_67.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_67.tab, Sendov911Box10_67.Adata, Sendov911Box10_67.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_67 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (67/100 : ℝ) ≤ a) (h1 : a ≤ (17/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_67 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_67 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_67 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (37613/50000 : ℝ) * a + ((9:ℕ):ℝ) - (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (65887/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_67
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (67/100 : ℝ)) (beta := (17/25 : ℝ))
    (S := (27572687832360052208110089750572227/3404106973903253674507141113281250 : ℝ)) (lam := (37613/50000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_67 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (67/100 : ℝ)), eta / (65887/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_67 (100 * (a - (67/100 : ℝ))) (eta / (65887/100000 : ℝ))
  rw [show (67/100 : ℝ) + (1/100) * (100 * (a - (67/100 : ℝ))) = a by ring] at heq
  rw [show (65887/100000 : ℝ) * (eta / (65887/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 68: `a ∈ [17/25, 69/100]`, S = 138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000, λ = 75649/100000, Y = 65401/100000 -/

noncomputable def box_68 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_68.tab Sendov911Box10_68.Adata
  D := (Sendov911Box10_68.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_68.Dscale]

theorem eq_68 (U V : ℝ) :
    (1 - ((17/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((65401/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ) ((17/25 : ℝ) + (1/100) * U) ((65401/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (75649/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ) ((17/25 : ℝ) + (1/100) * U) ((65401/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_68.tab Sendov911Box10_68.Adata k l : ℝ)
          / (Sendov911Box10_68.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_68.tab, Sendov911Box10_68.Adata, Sendov911Box10_68.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_68 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (17/25 : ℝ) ≤ a) (h1 : a ≤ (69/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_68 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_68 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_68 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (75649/100000 : ℝ) * a + ((9:ℕ):ℝ) - (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (65401/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_68
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (17/25 : ℝ)) (beta := (69/100 : ℝ))
    (S := (138553246824130320612841962855869124033439687961/17043955256250000000000000000000000000000000000 : ℝ)) (lam := (75649/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_68 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (17/25 : ℝ)), eta / (65401/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_68 (100 * (a - (17/25 : ℝ))) (eta / (65401/100000 : ℝ))
  rw [show (17/25 : ℝ) + (1/100) * (100 * (a - (17/25 : ℝ))) = a by ring] at heq
  rw [show (65401/100000 : ℝ) * (eta / (65401/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 69: `a ∈ [69/100, 7/10]`, S = 1407745607325616646502134528996489/172462556250000000000000000000000, λ = 2377/3125, Y = 32459/50000 -/

noncomputable def box_69 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_69.tab Sendov911Box10_69.Adata
  D := (Sendov911Box10_69.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_69.Dscale]

theorem eq_69 (U V : ℝ) :
    (1 - ((69/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((32459/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ) ((69/100 : ℝ) + (1/100) * U) ((32459/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (2377/3125 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ) ((69/100 : ℝ) + (1/100) * U) ((32459/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_69.tab Sendov911Box10_69.Adata k l : ℝ)
          / (Sendov911Box10_69.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_69.tab, Sendov911Box10_69.Adata, Sendov911Box10_69.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_69 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (69/100 : ℝ) ≤ a) (h1 : a ≤ (7/10 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_69 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_69 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_69 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (2377/3125 : ℝ) * a + ((9:ℕ):ℝ) - (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (32459/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_69
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (69/100 : ℝ)) (beta := (7/10 : ℝ))
    (S := (1407745607325616646502134528996489/172462556250000000000000000000000 : ℝ)) (lam := (2377/3125 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_69 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (69/100 : ℝ)), eta / (32459/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_69 (100 * (a - (69/100 : ℝ))) (eta / (32459/50000 : ℝ))
  rw [show (69/100 : ℝ) + (1/100) * (100 * (a - (69/100 : ℝ))) = a by ring] at heq
  rw [show (32459/50000 : ℝ) * (eta / (32459/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

noncomputable def chunk : List Box :=
  [box_60, box_61, box_62, box_63, box_64, box_65, box_66, box_67, box_68, box_69]

theorem chunkPos : CoveringPositive chunk := by
  unfold chunk
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_60.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_61.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_62.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_63.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_64.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_65.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_66.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_67.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_68.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_69.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

end SendovN.Red10C

#print axioms SendovN.Red10C.eq_60
#print axioms SendovN.Red10C.red_60
#print axioms SendovN.Red10C.eq_61
#print axioms SendovN.Red10C.red_61
#print axioms SendovN.Red10C.eq_62
#print axioms SendovN.Red10C.red_62
#print axioms SendovN.Red10C.eq_63
#print axioms SendovN.Red10C.red_63
#print axioms SendovN.Red10C.eq_64
#print axioms SendovN.Red10C.red_64
#print axioms SendovN.Red10C.eq_65
#print axioms SendovN.Red10C.red_65
#print axioms SendovN.Red10C.eq_66
#print axioms SendovN.Red10C.red_66
#print axioms SendovN.Red10C.eq_67
#print axioms SendovN.Red10C.red_67
#print axioms SendovN.Red10C.eq_68
#print axioms SendovN.Red10C.red_68
#print axioms SendovN.Red10C.eq_69
#print axioms SendovN.Red10C.red_69
#print axioms SendovN.Red10C.chunkPos
