import Mathlib
import SendovNEmajEq
import SendovNRows11
import SendovNCoverGrid
import Sendov911Box11_43_0
import Sendov911Box11_43_1
import Sendov911Box11_43_2
import Sendov911Box11_43_3
import Sendov911Box11_43_4
import Sendov911Box11_43_5
import Sendov911Box11_43_6
import Sendov911Box11_43_7
import Sendov911Box11_43_8
import Sendov911Box11_43_9

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D11-6/7 assembly for row 43 (generated by emit_assembly1011.py; do not
hand-edit)

`a ∈ [43/100, 11/25]`, S = 17875676505368703013689072535542735193/2260358574130805209279060363769531250, λ = 41167/50000, Y = 11351/20000.  Per η-strip j: the `Box`
value, the hEq identity against the shipped `boxes11v2` table (regenerated
from the verifier arithmetic — `split_cert` at the box's recorded τ — and
matched integer-for-integer before emission), the strip membership, and the
row reduction `red_43` (strip cover → `split_row_nonpos` → pullback).
-/

namespace SendovN.Red11_43

open Finset Sendov911Capstone

/-- Stage 1: the τ = 1 certificate closed form, evaluated
(coefficients from the verifier's own `split_cert` arithmetic). -/
theorem Peq_43_t0 (a eta : ℝ) :
    (1 - a) / 11 + eta ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) a eta ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) a eta (1 : ℝ)
    = (139537933428237542508708101961615950373118080632074172918122385563710176788377267361003250211717743435432520593861692917020415941963833692799310452636903129616135381345217528361054265807/1669969804626063883274272262138672487016990524689846788466479656412645261860753830024648086578562811872598993695144568898782353212768054507398685429309104222284076968207955360412597656250 : ℝ)
      + (1/22 : ℝ) * eta ^ 2
      + (-1/11 : ℝ) * a
      + (12277503355950083243498467323717912082971967067002807851557583201075756108054899004873848568151603098440115196605995164687070713742353080600570040936651799682417070310051140767363702943/333993960925212776654854452427734497403398104937969357693295931282529052372150766004929617315712562374519798739028913779756470642553610901479737085861820844456815393641591072082519531250 : ℝ) * a ^ 2
      + (1867617992371560692071580973031892852586184788260052788724021688478560654534867532221815962921203572220999423372539748403084832146233080263003568001/29552298891661142560724443314266681415071885288375627817452688295010842217584303530338045120730629591120183947972055449326944653876125812530517578125 : ℝ) * a ^ 2 * eta ^ 2
      + (-9201813026872412924606649270365297574903929182348431181672039858838222878138984979858405276343588048777885098218848694263158268197840212221011380501/22841120783154644819777436826039697496616133069805404010954142226129478766431422864338196287528890874403073030229904816224006935954093933105468750000 : ℝ) * a ^ 3 * eta ^ 2
      + (-12277503355950083243498467323717912082971967067002807851557583201075756108054899004873848568151603098440115196605995164687070713742353080600570040936651799682417070310051140767363702943/166996980462606388327427226213867248701699052468984678846647965641264526186075383002464808657856281187259899369514456889878235321276805450739868542930910422228407696820795536041259765625 : ℝ) * a ^ 4
      + (-7470471969486242768286323892127571410344739153040211154896086753914242618139470128887263851684814288883997693490158993612339328584932321052014272004/29552298891661142560724443314266681415071885288375627817452688295010842217584303530338045120730629591120183947972055449326944653876125812530517578125 : ℝ) * a ^ 4 * eta ^ 2
      + (-384210874427061861751456732212888825958508842681761393157521387581365771869845146029014629271478174266407812341/505254366377200442293959284592456664221135217627982933776665602575812671903854322863480774685740470886230468750 : ℝ) * a ^ 4 * eta ^ 3
      + (-1136386401797098433546153212383114116049994563481957064885169102768951785208476153554615284924512848354895311228/5229665634449195809990163212731298250420713338171495035031403919397103609301158400057829567231237888336181640625 : ℝ) * a ^ 4 * eta ^ 4
      + (4149993312473872999423776969991554891732889201189895852799393951973278366765447355098590320284477902378881486709484186450903663755224295136511246447/3263017254736377831396776689434242499516590438543629144422020318018496966633060409191170898218412982057581861461414973746286705136299133300781250000 : ℝ) * a ^ 5 * eta ^ 2
      + (-682767406226804506730940438710415688767195602665575616661817788151750615004850584668984288055964408352154675058951/1347344977005867846117224758913217771256360580341287823404441606868833791743611527635948732495307922363281250000000 : ℝ) * a ^ 5 * eta ^ 4
      + (12277503355950083243498467323717912082971967067002807851557583201075756108054899004873848568151603098440115196605995164687070713742353080600570040936651799682417070310051140767363702943/166996980462606388327427226213867248701699052468984678846647965641264526186075383002464808657856281187259899369514456889878235321276805450739868542930910422228407696820795536041259765625 : ℝ) * a ^ 6
      + (3735235984743121384143161946063785705172369576520105577448043376957121309069735064443631925842407144441998846745079496806169664292466160526007136002/9850766297220380853574814438088893805023961762791875939150896098336947405861434510112681706910209863706727982657351816442314884625375270843505859375 : ℝ) * a ^ 6 * eta ^ 2
      + (2679988542109816480719293069676113935142954222316847109407902972610731653512504557239767000687426075436194139353/1347344977005867846117224758913217771256360580341287823404441606868833791743611527635948732495307922363281250000 : ℝ) * a ^ 6 * eta ^ 3
      + (1136386401797098433546153212383114116049994563481957064885169102768951785208476153554615284924512848354895311228/1743221878149731936663387737577099416806904446057165011677134639799034536433719466685943189077079296112060546875 : ℝ) * a ^ 6 * eta ^ 4
      + (-493681805387096580511575904754455314106805564265981586157850319265623355743/3576454618552652780056880834616203634901410168822621926665306091308593750000 : ℝ) * a ^ 6 * eta ^ 5
      + (345727568342155619154314466694725451857118796188841216768051208904015977992/925457702915158643978638712288627317381628500925216940231621265411376953125 : ℝ) * a ^ 6 * eta ^ 6
      + (-12202606967760030853545780271320922718602645292375242681403682782020155927190276004432689904521435183848398596623958285641378643727731224765509089127/7613706927718214939925812275346565832205377689935134670318047408709826255477140954779398762509630291467691010076634938741335645318031311035156250000 : ℝ) * a ^ 7 * eta ^ 2
      + (619672964810845152843061546484006502715198226693070293572851864905565812931797017325454566799618897869366589121451/449114992335289282039074919637739257085453526780429274468147202289611263914537175878649577498435974121093750000000 : ℝ) * a ^ 7 * eta ^ 4
      + (69937973973145420746115216915356440955734586755882085798700391424393529510678829/43453923615414731277691102140586874164052133551194856408983469009399414062500000 : ℝ) * a ^ 7 * eta ^ 6
      + (-12277503355950083243498467323717912082971967067002807851557583201075756108054899004873848568151603098440115196605995164687070713742353080600570040936651799682417070310051140767363702943/333993960925212776654854452427734497403398104937969357693295931282529052372150766004929617315712562374519798739028913779756470642553610901479737085861820844456815393641591072082519531250 : ℝ) * a ^ 8
      + (-7470471969486242768286323892127571410344739153040211154896086753914242618139470128887263851684814288883997693490158993612339328584932321052014272004/29552298891661142560724443314266681415071885288375627817452688295010842217584303530338045120730629591120183947972055449326944653876125812530517578125 : ℝ) * a ^ 8 * eta ^ 2
      + (-1201904277040396851846757782429473072450200515705442844564521431852170892444454621294114249596896641004840233739/673672488502933923058612379456608885628180290170643911702220803434416895871805763817974366247653961181640625000 : ℝ) * a ^ 8 * eta ^ 3
      + (-1136386401797098433546153212383114116049994563481957064885169102768951785208476153554615284924512848354895311228/1743221878149731936663387737577099416806904446057165011677134639799034536433719466685943189077079296112060546875 : ℝ) * a ^ 8 * eta ^ 4
      + (462979153778005336708343068290772334023106812657373295604757362722654605743/1788227309276326390028440417308101817450705084411310963332653045654296875000 : ℝ) * a ^ 8 * eta ^ 5
      + (-691455136684311238308628933389450903714237592377682433536102417808031955984/925457702915158643978638712288627317381628500925216940231621265411376953125 : ℝ) * a ^ 8 * eta ^ 6
      + (40859485215983537021344726499765100044263/40686454334354493767023086547851562500000 : ℝ) * a ^ 8 * eta ^ 7
      + (-52591069077717415738350165733560631544/163771839301387430168688297271728515625 : ℝ) * a ^ 8 * eta ^ 8
      + (3041107349156900715271322712899971875439766068167991322757156257560087552737927418200105843157793467479218537622886433537100103095934935090124527697/3263017254736377831396776689434242499516590438543629144422020318018496966633060409191170898218412982057581861461414973746286705136299133300781250000 : ℝ) * a ^ 9 * eta ^ 2
      + (-571698841369186556508052771919218136219526623216658795850903953183848187046346196022208664272495208217877331308951/449114992335289282039074919637739257085453526780429274468147202289611263914537175878649577498435974121093750000000 : ℝ) * a ^ 9 * eta ^ 4
      + (-19010761644090969917324777626304473273546616150559817235845954055643046133910469/6207703373630675896813014591512410594864590507313550915569067001342773437500000 : ℝ) * a ^ 9 * eta ^ 6
      + (-28624147960175848005348493561122799384018103/19529498080490157008171081542968750000000000 : ℝ) * a ^ 9 * eta ^ 8
      + (12277503355950083243498467323717912082971967067002807851557583201075756108054899004873848568151603098440115196605995164687070713742353080600570040936651799682417070310051140767363702943/1669969804626063883274272262138672487016990524689846788466479656412645261860753830024648086578562811872598993695144568898782353212768054507398685429309104222284076968207955360412597656250 : ℝ) * a ^ 10
      + (1867617992371560692071580973031892852586184788260052788724021688478560654534867532221815962921203572220999423372539748403084832146233080263003568001/29552298891661142560724443314266681415071885288375627817452688295010842217584303530338045120730629591120183947972055449326944653876125812530517578125 : ℝ) * a ^ 10 * eta ^ 2
      + (2197027567864931282715849030433278030824112576581160890730575002257869647954274812576217646387523159481604295603/4042034931017603538351674276739653313769081741023863470213324820606501375230834582907846197485923767089843750000 : ℝ) * a ^ 10 * eta ^ 3
      + (1136386401797098433546153212383114116049994563481957064885169102768951785208476153554615284924512848354895311228/5229665634449195809990163212731298250420713338171495035031403919397103609301158400057829567231237888336181640625 : ℝ) * a ^ 10 * eta ^ 4
      + (-62564773465979258800516173896980157962976981548649563516828544667689497249/510922088364664682865268690659457662128772881260374560952186584472656250000 : ℝ) * a ^ 10 * eta ^ 5
      + (345727568342155619154314466694725451857118796188841216768051208904015977992/925457702915158643978638712288627317381628500925216940231621265411376953125 : ℝ) * a ^ 10 * eta ^ 6
      + (-1231687059619590221562836481160452650309/1271451697948577930219471454620361328125 : ℝ) * a ^ 10 * eta ^ 7
      + (52591069077717415738350165733560631544/163771839301387430168688297271728515625 : ℝ) * a ^ 10 * eta ^ 8
      + (-147/250 : ℝ) * a ^ 10 * eta ^ 9
      + (50000/452837 : ℝ) * a ^ 10 * eta ^ 10
      + (-2379394546505973666991547973340349695993896938620603299541503561352432755914134618372947543192633756333744353391823802527113594066086291489534010563/11420560391577322409888718413019848748308066534902702005477071113064739383215711432169098143764445437201536515114952408112003467977046966552734375000 : ℝ) * a ^ 11 * eta ^ 2
      + (76232947980135552220319951536326078810277412892869318623034282896328596114832577111737428523673627778771119874493/192477853857981120873889251273316824465194368620183974772063086695547684534801646805135533213615417480468750000000 : ℝ) * a ^ 11 * eta ^ 4
      + (4547278927643104813785564761845341413887084198032369054690672292077532468536211/3103851686815337948406507295756205297432295253656775457784533500671386718750000 : ℝ) * a ^ 11 * eta ^ 6
      + (27789442974239872149666448339794064032455603/19529498080490157008171081542968750000000000 : ℝ) * a ^ 11 * eta ^ 8
      + (1073407/1900800 : ℝ) * a ^ 11 * eta ^ 10 := by
  rw [EmajEq.EmajTau11_eq]
  unfold MidChainN.hh
  push_cast
  norm_num
  ring

/-! ### Strip 0: `η ∈ [0, 11351/200000]`, τ = 1 -/

noncomputable def box_43_0 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_0.tab Sendov911Box11_43_0.Adata
  D := (Sendov911Box11_43_0.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_0.Dscale]

theorem eq_43_0 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((0 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_0.tab Sendov911Box11_43_0.Adata k l : ℝ)
          / (Sendov911Box11_43_0.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_0.tab, Sendov911Box11_43_0.Adata, Sendov911Box11_43_0.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 1: `η ∈ [11351/200000, 11351/100000]`, τ = 1 -/

noncomputable def box_43_1 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_1.tab Sendov911Box11_43_1.Adata
  D := (Sendov911Box11_43_1.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_1.Dscale]

theorem eq_43_1 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((11351/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/200000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_1.tab Sendov911Box11_43_1.Adata k l : ℝ)
          / (Sendov911Box11_43_1.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_1.tab, Sendov911Box11_43_1.Adata, Sendov911Box11_43_1.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 2: `η ∈ [11351/100000, 34053/200000]`, τ = 1 -/

noncomputable def box_43_2 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_2.tab Sendov911Box11_43_2.Adata
  D := (Sendov911Box11_43_2.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_2.Dscale]

theorem eq_43_2 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((11351/100000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/100000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/100000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_2.tab Sendov911Box11_43_2.Adata k l : ℝ)
          / (Sendov911Box11_43_2.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_2.tab, Sendov911Box11_43_2.Adata, Sendov911Box11_43_2.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 3: `η ∈ [34053/200000, 11351/50000]`, τ = 1 -/

noncomputable def box_43_3 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_3.tab Sendov911Box11_43_3.Adata
  D := (Sendov911Box11_43_3.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_3.Dscale]

theorem eq_43_3 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((34053/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((34053/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((34053/200000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_3.tab Sendov911Box11_43_3.Adata k l : ℝ)
          / (Sendov911Box11_43_3.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_3.tab, Sendov911Box11_43_3.Adata, Sendov911Box11_43_3.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 4: `η ∈ [11351/50000, 11351/40000]`, τ = 1 -/

noncomputable def box_43_4 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_4.tab Sendov911Box11_43_4.Adata
  D := (Sendov911Box11_43_4.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_4.Dscale]

theorem eq_43_4 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((11351/50000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/50000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/50000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_4.tab Sendov911Box11_43_4.Adata k l : ℝ)
          / (Sendov911Box11_43_4.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_4.tab, Sendov911Box11_43_4.Adata, Sendov911Box11_43_4.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 5: `η ∈ [11351/40000, 34053/100000]`, τ = 1 -/

noncomputable def box_43_5 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_5.tab Sendov911Box11_43_5.Adata
  D := (Sendov911Box11_43_5.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_5.Dscale]

theorem eq_43_5 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((11351/40000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/40000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/40000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_5.tab Sendov911Box11_43_5.Adata k l : ℝ)
          / (Sendov911Box11_43_5.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_5.tab, Sendov911Box11_43_5.Adata, Sendov911Box11_43_5.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 6: `η ∈ [34053/100000, 79457/200000]`, τ = 1 -/

noncomputable def box_43_6 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_6.tab Sendov911Box11_43_6.Adata
  D := (Sendov911Box11_43_6.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_6.Dscale]

theorem eq_43_6 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((34053/100000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((34053/100000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((34053/100000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_6.tab Sendov911Box11_43_6.Adata k l : ℝ)
          / (Sendov911Box11_43_6.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_6.tab, Sendov911Box11_43_6.Adata, Sendov911Box11_43_6.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 7: `η ∈ [79457/200000, 11351/25000]`, τ = 1 -/

noncomputable def box_43_7 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_7.tab Sendov911Box11_43_7.Adata
  D := (Sendov911Box11_43_7.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_7.Dscale]

theorem eq_43_7 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((79457/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((79457/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((79457/200000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_7.tab Sendov911Box11_43_7.Adata k l : ℝ)
          / (Sendov911Box11_43_7.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_7.tab, Sendov911Box11_43_7.Adata, Sendov911Box11_43_7.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 8: `η ∈ [11351/25000, 102159/200000]`, τ = 1 -/

noncomputable def box_43_8 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_8.tab Sendov911Box11_43_8.Adata
  D := (Sendov911Box11_43_8.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_8.Dscale]

theorem eq_43_8 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((11351/25000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/25000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((11351/25000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_8.tab Sendov911Box11_43_8.Adata k l : ℝ)
          / (Sendov911Box11_43_8.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_8.tab, Sendov911Box11_43_8.Adata, Sendov911Box11_43_8.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 9: `η ∈ [102159/200000, 11351/20000]`, τ = 1 -/

noncomputable def box_43_9 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_43_9.tab Sendov911Box11_43_9.Adata
  D := (Sendov911Box11_43_9.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_43_9.Dscale]

theorem eq_43_9 (U V : ℝ) :
    (1 - ((43/100 : ℝ) + (1/100) * U)) / 11 + ((102159/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((102159/200000 : ℝ) + (11351/200000 : ℝ) * V) ^ 5 / (11 * (41167/50000 : ℝ))
      - Split11.EmajTau CTab11.c11 (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) ((43/100 : ℝ) + (1/100) * U) ((102159/200000 : ℝ) + (11351/200000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_43_9.tab Sendov911Box11_43_9.Adata k l : ℝ)
          / (Sendov911Box11_43_9.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_43_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_43_9.tab, Sendov911Box11_43_9.Adata, Sendov911Box11_43_9.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

noncomputable def row_43 : List Box :=
  [box_43_0, box_43_1, box_43_2, box_43_3, box_43_4, box_43_5, box_43_6, box_43_7, box_43_8, box_43_9]

theorem mem_43_0 : box_43_0 ∈ row_43 :=
  List.Mem.head _

theorem mem_43_1 : box_43_1 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.head _)

theorem mem_43_2 : box_43_2 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))

theorem mem_43_3 : box_43_3 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))

theorem mem_43_4 : box_43_4 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))

theorem mem_43_5 : box_43_5 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))

theorem mem_43_6 : box_43_6 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))

theorem mem_43_7 : box_43_7 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))

theorem mem_43_8 : box_43_8 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))))

theorem mem_43_9 : box_43_9 ∈ row_43 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))))

theorem rowPos_43 : CoveringPositive row_43 := by
  unfold row_43
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_0.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_1.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_2.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_3.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_4.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_5.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_6.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_7.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_8.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_43_9.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

theorem red_43 (mu : ℂ) (Df : Fin 10 → ℂ) (rr : Fin 10 → ℝ) (a eta sig : ℝ)
    (h0 : (43/100 : ℝ) ≤ a) (h1 : a ≤ (11/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (10:ℝ) ≤ 10 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (563/1000 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (11:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0) (hY1 : ∀ j, ‖mu + Df j‖ ≤ 1)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 10 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 11) :
    ∃ b ∈ row_43, ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly b U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) := by
    rw [hsigeq]
    exact Rows11.sigma_row_43 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows11.L_row_43 h0 h1
  have hc := CTab11.cTable11 Df eta heta0 hz hD2
  have hloc' : ((10:ℕ):ℝ) ≤ ((10:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) * a ^ 2 - ((10:ℕ):ℝ) * (41167/50000 : ℝ) * a + ((10:ℕ):ℝ) - (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (11351/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows11.Y_row_43
  obtain ⟨j, hj, hja, hjb⟩ := Cover.cover_grid (by norm_num : (0:ℝ) < (11351/200000 : ℝ)) 0 10
    (by norm_num) eta heta0 (by push_cast; linarith)
  interval_cases j
  · -- strip j = 0, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_0, mem_43_0, 100 * (a - (43/100 : ℝ)), (eta - (0 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_0 (100 * (a - (43/100 : ℝ))) ((eta - (0 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (0 : ℝ) + (11351/200000 : ℝ) * ((eta - (0 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 1, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_1, mem_43_1, 100 * (a - (43/100 : ℝ)), (eta - (11351/200000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_1 (100 * (a - (43/100 : ℝ))) ((eta - (11351/200000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (11351/200000 : ℝ) + (11351/200000 : ℝ) * ((eta - (11351/200000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 2, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_2, mem_43_2, 100 * (a - (43/100 : ℝ)), (eta - (11351/100000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_2 (100 * (a - (43/100 : ℝ))) ((eta - (11351/100000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (11351/100000 : ℝ) + (11351/200000 : ℝ) * ((eta - (11351/100000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 3, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_3, mem_43_3, 100 * (a - (43/100 : ℝ)), (eta - (34053/200000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_3 (100 * (a - (43/100 : ℝ))) ((eta - (34053/200000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (34053/200000 : ℝ) + (11351/200000 : ℝ) * ((eta - (34053/200000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 4, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_4, mem_43_4, 100 * (a - (43/100 : ℝ)), (eta - (11351/50000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_4 (100 * (a - (43/100 : ℝ))) ((eta - (11351/50000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (11351/50000 : ℝ) + (11351/200000 : ℝ) * ((eta - (11351/50000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 5, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_5, mem_43_5, 100 * (a - (43/100 : ℝ)), (eta - (11351/40000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_5 (100 * (a - (43/100 : ℝ))) ((eta - (11351/40000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (11351/40000 : ℝ) + (11351/200000 : ℝ) * ((eta - (11351/40000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 6, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_6, mem_43_6, 100 * (a - (43/100 : ℝ)), (eta - (34053/100000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_6 (100 * (a - (43/100 : ℝ))) ((eta - (34053/100000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (34053/100000 : ℝ) + (11351/200000 : ℝ) * ((eta - (34053/100000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 7, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_7, mem_43_7, 100 * (a - (43/100 : ℝ)), (eta - (79457/200000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_7 (100 * (a - (43/100 : ℝ))) ((eta - (79457/200000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (79457/200000 : ℝ) + (11351/200000 : ℝ) * ((eta - (79457/200000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 8, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_8, mem_43_8, 100 * (a - (43/100 : ℝ)), (eta - (11351/25000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_8 (100 * (a - (43/100 : ℝ))) ((eta - (11351/25000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (11351/25000 : ℝ) + (11351/200000 : ℝ) * ((eta - (11351/25000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 9, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (43/100 : ℝ)) (beta := (11/25 : ℝ))
      (S := (17875676505368703013689072535542735193/2260358574130805209279060363769531250 : ℝ)) (lam := (41167/50000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_43
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_43_9, mem_43_9, 100 * (a - (43/100 : ℝ)), (eta - (102159/200000 : ℝ)) / (11351/200000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_43_9 (100 * (a - (43/100 : ℝ))) ((eta - (102159/200000 : ℝ)) / (11351/200000 : ℝ))
    rw [show (43/100 : ℝ) + (1/100) * (100 * (a - (43/100 : ℝ))) = a by ring] at heq
    rw [show (102159/200000 : ℝ) + (11351/200000 : ℝ) * ((eta - (102159/200000 : ℝ)) / (11351/200000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP

end SendovN.Red11_43

#print axioms SendovN.Red11_43.Peq_43_t0
#print axioms SendovN.Red11_43.eq_43_0
#print axioms SendovN.Red11_43.eq_43_1
#print axioms SendovN.Red11_43.eq_43_2
#print axioms SendovN.Red11_43.eq_43_3
#print axioms SendovN.Red11_43.eq_43_4
#print axioms SendovN.Red11_43.eq_43_5
#print axioms SendovN.Red11_43.eq_43_6
#print axioms SendovN.Red11_43.eq_43_7
#print axioms SendovN.Red11_43.eq_43_8
#print axioms SendovN.Red11_43.eq_43_9
#print axioms SendovN.Red11_43.rowPos_43
#print axioms SendovN.Red11_43.red_43
