import Mathlib
import SendovNEmajEq
import Sendov911Box10Boundary

set_option maxHeartbeats 4000000000
set_option maxRecDepth 1000000

/-!
# D10-6 boundary hEq (generated by emit_assembly1011.py; do not hand-edit)

The degree-10 certificate closed form at `S_b, λ_b = 22/25` under the boundary
substitution `a = 1 − x²`, `η = x·Y` and the pullback `x = (8/25)U`,
`Y = (31/20)V`, equals `x²` times the shipped bidegree-(28,10) boundary table.
Adata/Dscale regenerated from `boundary_sub ∘ certificate_polynomial` and
matched integer-for-integer before emission.
-/

namespace SendovN.BdryEq10

theorem bdry10_eq (U V : ℝ) :
    (1 - (1 - ((8/25 : ℝ) * U) ^ 2)) / (((9:ℕ):ℝ) + 1) + (((8/25 : ℝ) * U) * ((31/20 : ℝ) * V)) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (469879173178970601607/48564147949218750000 : ℝ) (1 - ((8/25 : ℝ) * U) ^ 2) (((8/25 : ℝ) * U) * ((31/20 : ℝ) * V)) ^ 5 / ((((9:ℕ):ℝ) + 1) * (22/25 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (469879173178970601607/48564147949218750000 : ℝ) (1 - ((8/25 : ℝ) * U) ^ 2) (((8/25 : ℝ) * U) * ((31/20 : ℝ) * V))
    = ((8/25 : ℝ) * U) ^ 2 * (∑ k ∈ Finset.range 29, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10Boundary.tab Sendov911Box10Boundary.Adata k l : ℝ)
          / (Sendov911Box10Boundary.Dscale : ℝ)) * U ^ k * V ^ l) := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10Boundary.tab, Sendov911Box10Boundary.Adata, Sendov911Box10Boundary.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

end SendovN.BdryEq10

#print axioms SendovN.BdryEq10.bdry10_eq
