import Mathlib
import SendovNEmajEq
import SendovNRows10
import SendovNCoverGrid
import Sendov911Box10_80
import Sendov911Box10_81
import Sendov911Box10_82
import Sendov911Box10_83
import Sendov911Box10_84
import Sendov911Box10_85
import Sendov911Box10_86
import Sendov911Box10_87
import Sendov911Box10_88
import Sendov911Box10_89

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D10-6/7 assembly chunk E (rows 80–89; generated by
emit_assembly1011.py, do not hand-edit)

Per row: the `Box` value, the hEq identity against the shipped monomial table
(regenerated from the verifier arithmetic and matched integer-for-integer
before emission), and the row reduction `red_i` (`row_nonpos` → pullback).
-/

namespace SendovN.Red10E

open Finset Sendov911Capstone

/-! ### Row 80: `a ∈ [4/5, 81/100]`, S = 173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000, λ = 40321/50000, Y = 11827/20000 -/

noncomputable def box_80 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_80.tab Sendov911Box10_80.Adata
  D := (Sendov911Box10_80.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_80.Dscale]

theorem eq_80 (U V : ℝ) :
    (1 - ((4/5 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((11827/20000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ) ((4/5 : ℝ) + (1/100) * U) ((11827/20000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (40321/50000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ) ((4/5 : ℝ) + (1/100) * U) ((11827/20000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_80.tab Sendov911Box10_80.Adata k l : ℝ)
          / (Sendov911Box10_80.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_80.tab, Sendov911Box10_80.Adata, Sendov911Box10_80.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_80 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (4/5 : ℝ) ≤ a) (h1 : a ≤ (81/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_80 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_80 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_80 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (40321/50000 : ℝ) * a + ((9:ℕ):ℝ) - (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (11827/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_80
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (4/5 : ℝ)) (beta := (81/100 : ℝ))
    (S := (173440952113004060805172930100233146689364517361/19550331506250000000000000000000000000000000000 : ℝ)) (lam := (40321/50000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_80 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (4/5 : ℝ)), eta / (11827/20000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_80 (100 * (a - (4/5 : ℝ))) (eta / (11827/20000 : ℝ))
  rw [show (4/5 : ℝ) + (1/100) * (100 * (a - (4/5 : ℝ))) = a by ring] at heq
  rw [show (11827/20000 : ℝ) * (eta / (11827/20000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 81: `a ∈ [81/100, 41/50]`, S = 10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000, λ = 81119/100000, Y = 58479/100000 -/

noncomputable def box_81 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_81.tab Sendov911Box10_81.Adata
  D := (Sendov911Box10_81.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_81.Dscale]

theorem eq_81 (U V : ℝ) :
    (1 - ((81/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((58479/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ) ((81/100 : ℝ) + (1/100) * U) ((58479/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (81119/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ) ((81/100 : ℝ) + (1/100) * U) ((58479/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_81.tab Sendov911Box10_81.Adata k l : ℝ)
          / (Sendov911Box10_81.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_81.tab, Sendov911Box10_81.Adata, Sendov911Box10_81.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_81 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (81/100 : ℝ) ≤ a) (h1 : a ≤ (41/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_81 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_81 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_81 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (81119/100000 : ℝ) * a + ((9:ℕ):ℝ) - (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (58479/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_81
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (81/100 : ℝ)) (beta := (41/50 : ℝ))
    (S := (10827792650087924269017950070572624138304401/1206479127502441406250000000000000000000000 : ℝ)) (lam := (81119/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_81 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (81/100 : ℝ)), eta / (58479/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_81 (100 * (a - (81/100 : ℝ))) (eta / (58479/100000 : ℝ))
  rw [show (81/100 : ℝ) + (1/100) * (100 * (a - (81/100 : ℝ))) = a by ring] at heq
  rw [show (58479/100000 : ℝ) * (eta / (58479/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 82: `a ∈ [41/50, 83/100]`, S = 20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000, λ = 40809/50000, Y = 2889/5000 -/

noncomputable def box_82 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_82.tab Sendov911Box10_82.Adata
  D := (Sendov911Box10_82.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_82.Dscale]

theorem eq_82 (U V : ℝ) :
    (1 - ((41/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((2889/5000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ) ((41/50 : ℝ) + (1/100) * U) ((2889/5000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (40809/50000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ) ((41/50 : ℝ) + (1/100) * U) ((2889/5000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_82.tab Sendov911Box10_82.Adata k l : ℝ)
          / (Sendov911Box10_82.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_82.tab, Sendov911Box10_82.Adata, Sendov911Box10_82.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_82 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (41/50 : ℝ) ≤ a) (h1 : a ≤ (83/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_82 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_82 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_82 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (40809/50000 : ℝ) * a + ((9:ℕ):ℝ) - (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (2889/5000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_82
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (41/50 : ℝ)) (beta := (83/100 : ℝ))
    (S := (20175525936079586660255805508782353050793834321/2220530006250000000000000000000000000000000000 : ℝ)) (lam := (40809/50000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_82 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (41/50 : ℝ)), eta / (2889/5000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_82 (100 * (a - (41/50 : ℝ))) (eta / (2889/5000 : ℝ))
  rw [show (41/50 : ℝ) + (1/100) * (100 * (a - (41/50 : ℝ))) = a by ring] at heq
  rw [show (2889/5000 : ℝ) * (eta / (2889/5000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 83: `a ∈ [83/100, 21/25]`, S = 338307861553190319183916092148710427/36750461003975942730903625488281250, λ = 82143/100000, Y = 57031/100000 -/

noncomputable def box_83 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_83.tab Sendov911Box10_83.Adata
  D := (Sendov911Box10_83.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_83.Dscale]

theorem eq_83 (U V : ℝ) :
    (1 - ((83/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((57031/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ) ((83/100 : ℝ) + (1/100) * U) ((57031/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (82143/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ) ((83/100 : ℝ) + (1/100) * U) ((57031/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_83.tab Sendov911Box10_83.Adata k l : ℝ)
          / (Sendov911Box10_83.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_83.tab, Sendov911Box10_83.Adata, Sendov911Box10_83.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_83 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (83/100 : ℝ) ≤ a) (h1 : a ≤ (21/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_83 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_83 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_83 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (82143/100000 : ℝ) * a + ((9:ℕ):ℝ) - (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (57031/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_83
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (83/100 : ℝ)) (beta := (21/25 : ℝ))
    (S := (338307861553190319183916092148710427/36750461003975942730903625488281250 : ℝ)) (lam := (82143/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_83 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (83/100 : ℝ)), eta / (57031/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_83 (100 * (a - (83/100 : ℝ))) (eta / (57031/100000 : ℝ))
  rw [show (83/100 : ℝ) + (1/100) * (100 * (a - (83/100 : ℝ))) = a by ring] at heq
  rw [show (57031/100000 : ℝ) * (eta / (57031/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 84: `a ∈ [21/25, 17/20]`, S = 31234228682981414698275404060403541649/3346265318400000000000000000000000000, λ = 82699/100000, Y = 28111/50000 -/

noncomputable def box_84 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_84.tab Sendov911Box10_84.Adata
  D := (Sendov911Box10_84.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_84.Dscale]

theorem eq_84 (U V : ℝ) :
    (1 - ((21/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((28111/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ) ((21/25 : ℝ) + (1/100) * U) ((28111/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (82699/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ) ((21/25 : ℝ) + (1/100) * U) ((28111/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_84.tab Sendov911Box10_84.Adata k l : ℝ)
          / (Sendov911Box10_84.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_84.tab, Sendov911Box10_84.Adata, Sendov911Box10_84.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_84 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (21/25 : ℝ) ≤ a) (h1 : a ≤ (17/20 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_84 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_84 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_84 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (82699/100000 : ℝ) * a + ((9:ℕ):ℝ) - (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (28111/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_84
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (21/25 : ℝ)) (beta := (17/20 : ℝ))
    (S := (31234228682981414698275404060403541649/3346265318400000000000000000000000000 : ℝ)) (lam := (82699/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_84 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (21/25 : ℝ)), eta / (28111/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_84 (100 * (a - (21/25 : ℝ))) (eta / (28111/50000 : ℝ))
  rw [show (21/25 : ℝ) + (1/100) * (100 * (a - (21/25 : ℝ))) = a by ring] at heq
  rw [show (28111/50000 : ℝ) * (eta / (28111/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 85: `a ∈ [17/20, 43/50]`, S = 1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000, λ = 10411/12500, Y = 27673/50000 -/

noncomputable def box_85 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_85.tab Sendov911Box10_85.Adata
  D := (Sendov911Box10_85.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_85.Dscale]

theorem eq_85 (U V : ℝ) :
    (1 - ((17/20 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((27673/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ) ((17/20 : ℝ) + (1/100) * U) ((27673/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (10411/12500 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ) ((17/20 : ℝ) + (1/100) * U) ((27673/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_85.tab Sendov911Box10_85.Adata k l : ℝ)
          / (Sendov911Box10_85.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_85.tab, Sendov911Box10_85.Adata, Sendov911Box10_85.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_85 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (17/20 : ℝ) ≤ a) (h1 : a ≤ (43/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_85 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_85 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_85 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (10411/12500 : ℝ) * a + ((9:ℕ):ℝ) - (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (27673/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_85
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (17/20 : ℝ)) (beta := (43/50 : ℝ))
    (S := (1326168064346078284970619789427173590560601/140010438537597656250000000000000000000000 : ℝ)) (lam := (10411/12500 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_85 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (17/20 : ℝ)), eta / (27673/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_85 (100 * (a - (17/20 : ℝ))) (eta / (27673/50000 : ℝ))
  rw [show (17/20 : ℝ) + (1/100) * (100 * (a - (17/20 : ℝ))) = a by ring] at heq
  rw [show (27673/50000 : ℝ) * (eta / (27673/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 86: `a ∈ [43/50, 87/100]`, S = 1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000, λ = 84061/100000, Y = 10833/20000 -/

noncomputable def box_86 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_86.tab Sendov911Box10_86.Adata
  D := (Sendov911Box10_86.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_86.Dscale]

theorem eq_86 (U V : ℝ) :
    (1 - ((43/50 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((10833/20000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ) ((43/50 : ℝ) + (1/100) * U) ((10833/20000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (84061/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ) ((43/50 : ℝ) + (1/100) * U) ((10833/20000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_86.tab Sendov911Box10_86.Adata k l : ℝ)
          / (Sendov911Box10_86.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_86.tab, Sendov911Box10_86.Adata, Sendov911Box10_86.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_86 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (43/50 : ℝ) ≤ a) (h1 : a ≤ (87/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_86 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_86 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_86 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (84061/100000 : ℝ) * a + ((9:ℕ):ℝ) - (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (10833/20000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_86
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (43/50 : ℝ)) (beta := (87/100 : ℝ))
    (S := (1665282745652971409710523428833280185129135607867/173899744218750000000000000000000000000000000000 : ℝ)) (lam := (84061/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_86 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (43/50 : ℝ)), eta / (10833/20000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_86 (100 * (a - (43/50 : ℝ))) (eta / (10833/20000 : ℝ))
  rw [show (43/50 : ℝ) + (1/100) * (100 * (a - (43/50 : ℝ))) = a by ring] at heq
  rw [show (10833/20000 : ℝ) * (eta / (10833/20000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 87: `a ∈ [87/100, 22/25]`, S = 100331263737198571279506999890457556395787/10476386994123458862304687500000000000000, λ = 10651/12500, Y = 26171/50000 -/

noncomputable def box_87 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_87.tab Sendov911Box10_87.Adata
  D := (Sendov911Box10_87.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_87.Dscale]

theorem eq_87 (U V : ℝ) :
    (1 - ((87/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((26171/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ) ((87/100 : ℝ) + (1/100) * U) ((26171/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (10651/12500 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ) ((87/100 : ℝ) + (1/100) * U) ((26171/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_87.tab Sendov911Box10_87.Adata k l : ℝ)
          / (Sendov911Box10_87.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_87.tab, Sendov911Box10_87.Adata, Sendov911Box10_87.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_87 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (87/100 : ℝ) ≤ a) (h1 : a ≤ (22/25 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_87 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_87 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_87 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (10651/12500 : ℝ) * a + ((9:ℕ):ℝ) - (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (26171/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_87
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (87/100 : ℝ)) (beta := (22/25 : ℝ))
    (S := (100331263737198571279506999890457556395787/10476386994123458862304687500000000000000 : ℝ)) (lam := (10651/12500 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_87 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (87/100 : ℝ)), eta / (26171/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_87 (100 * (a - (87/100 : ℝ))) (eta / (26171/50000 : ℝ))
  rw [show (87/100 : ℝ) + (1/100) * (100 * (a - (87/100 : ℝ))) = a by ring] at heq
  rw [show (26171/50000 : ℝ) * (eta / (26171/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 88: `a ∈ [22/25, 89/100]`, S = 567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000, λ = 86351/100000, Y = 25217/50000 -/

noncomputable def box_88 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_88.tab Sendov911Box10_88.Adata
  D := (Sendov911Box10_88.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_88.Dscale]

theorem eq_88 (U V : ℝ) :
    (1 - ((22/25 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((25217/50000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ) ((22/25 : ℝ) + (1/100) * U) ((25217/50000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (86351/100000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ) ((22/25 : ℝ) + (1/100) * U) ((25217/50000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_88.tab Sendov911Box10_88.Adata k l : ℝ)
          / (Sendov911Box10_88.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_88.tab, Sendov911Box10_88.Adata, Sendov911Box10_88.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_88 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (22/25 : ℝ) ≤ a) (h1 : a ≤ (89/100 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_88 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_88 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_88 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (86351/100000 : ℝ) * a + ((9:ℕ):ℝ) - (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (25217/50000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_88
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (22/25 : ℝ)) (beta := (89/100 : ℝ))
    (S := (567185228497213998414469459100239140304744509449/59213138906250000000000000000000000000000000000 : ℝ)) (lam := (86351/100000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_88 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (22/25 : ℝ)), eta / (25217/50000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_88 (100 * (a - (22/25 : ℝ))) (eta / (25217/50000 : ℝ))
  rw [show (22/25 : ℝ) + (1/100) * (100 * (a - (22/25 : ℝ))) = a by ring] at heq
  rw [show (25217/50000 : ℝ) * (eta / (25217/50000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

/-! ### Row 89: `a ∈ [89/100, 9/10]`, S = 1720122943197940003106771396657483227/179524171875000000000000000000000000, λ = 8749/10000, Y = 48431/100000 -/

noncomputable def box_89 : Box where
  nx := 10
  ny := 10
  A := Sendov911Box10_89.tab Sendov911Box10_89.Adata
  D := (Sendov911Box10_89.Dscale : ℝ)
  hD := by norm_num [Sendov911Box10_89.Dscale]

theorem eq_89 (U V : ℝ) :
    (1 - ((89/100 : ℝ) + (1/100) * U)) / (((9:ℕ):ℝ) + 1) + ((48431/100000 : ℝ) * V) ^ 2 / (2 * (((9:ℕ):ℝ) + 1))
      - MidChainN.hh 9 (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ) ((89/100 : ℝ) + (1/100) * U) ((48431/100000 : ℝ) * V) ^ 5 / ((((9:ℕ):ℝ) + 1) * (8749/10000 : ℝ))
      - MidChainN.Emaj 9 CTab10.c10 (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ) ((89/100 : ℝ) + (1/100) * U) ((48431/100000 : ℝ) * V)
    = ∑ k ∈ Finset.range 11, ∑ l ∈ Finset.range 11,
        ((Sendov911Box10_89.tab Sendov911Box10_89.Adata k l : ℝ)
          / (Sendov911Box10_89.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [EmajEq.Emaj10_eq]
  unfold MidChainN.hh
  push_cast
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box10_89.tab, Sendov911Box10_89.Adata, Sendov911Box10_89.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

theorem red_89 (mu : ℂ) (Df : Fin 9 → ℂ) (rr : Fin 9 → ℝ) (a eta sig : ℝ)
    (h0 : (89/100 : ℝ) ≤ a) (h1 : a ≤ (9/10 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (9:ℝ) ≤ 9 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (309/500 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (10:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 9 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 10) :
    ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly box_89 U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows10.sigma_row_89 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows10.L_row_89 h0 h1
  have hloc' : ((9:ℕ):ℝ) ≤ ((9:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ) * a ^ 2 - ((9:ℕ):ℝ) * (8749/10000 : ℝ) * a + ((9:ℕ):ℝ) - (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hmu0 : mu ≠ 0 := by
    intro hcon
    rw [hcon] at hmunorm
    simp only [norm_zero] at hmunorm
    norm_num at hmunorm
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (48431/100000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows10.Y_row_89
  have hP := MidChainN.row_nonpos (N := 9) (alpha := (89/100 : ℝ)) (beta := (9/10 : ℝ))
    (S := (1720122943197940003106771396657483227/179524171875000000000000000000000000 : ℝ)) (lam := (8749/10000 : ℝ)) (sigma := sig) (by norm_num)
    CTab10.c10 (fun m _ => CTab10.c10_nonneg m) mu Df a eta
    (by norm_num) (by norm_num) (by norm_num) Rows10.lam_row_89 h0 h1
    heta0 hnormSq hloc' hsig hL' hz
    (CTab10.cTable10 Df eta heta0 hz hD2)
    (by push_cast; norm_num; exact JBoundN.J_closed_form_deg10 hmu0 a)
    (by push_cast; norm_num; exact hI)
  refine ⟨100 * (a - (89/100 : ℝ)), eta / (48431/100000 : ℝ), by linarith, by linarith,
    div_nonneg heta0 (by norm_num), (div_le_one (by norm_num)).mpr hetaY, ?_⟩
  have heq := eq_89 (100 * (a - (89/100 : ℝ))) (eta / (48431/100000 : ℝ))
  rw [show (89/100 : ℝ) + (1/100) * (100 * (a - (89/100 : ℝ))) = a by ring] at heq
  rw [show (48431/100000 : ℝ) * (eta / (48431/100000 : ℝ)) = eta by field_simp <;> ring] at heq
  exact le_of_eq_of_le heq.symm hP

noncomputable def chunk : List Box :=
  [box_80, box_81, box_82, box_83, box_84, box_85, box_86, box_87, box_88, box_89]

theorem chunkPos : CoveringPositive chunk := by
  unfold chunk
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_80.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_81.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_82.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_83.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_84.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_85.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_86.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_87.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_88.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box10_89.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

end SendovN.Red10E

#print axioms SendovN.Red10E.eq_80
#print axioms SendovN.Red10E.red_80
#print axioms SendovN.Red10E.eq_81
#print axioms SendovN.Red10E.red_81
#print axioms SendovN.Red10E.eq_82
#print axioms SendovN.Red10E.red_82
#print axioms SendovN.Red10E.eq_83
#print axioms SendovN.Red10E.red_83
#print axioms SendovN.Red10E.eq_84
#print axioms SendovN.Red10E.red_84
#print axioms SendovN.Red10E.eq_85
#print axioms SendovN.Red10E.red_85
#print axioms SendovN.Red10E.eq_86
#print axioms SendovN.Red10E.red_86
#print axioms SendovN.Red10E.eq_87
#print axioms SendovN.Red10E.red_87
#print axioms SendovN.Red10E.eq_88
#print axioms SendovN.Red10E.red_88
#print axioms SendovN.Red10E.eq_89
#print axioms SendovN.Red10E.red_89
#print axioms SendovN.Red10E.chunkPos
