import Mathlib
import SendovNEmajEq
import SendovNRows11
import SendovNCoverGrid
import Sendov911Box11_37_0
import Sendov911Box11_37_1
import Sendov911Box11_37_2
import Sendov911Box11_37_3
import Sendov911Box11_37_4
import Sendov911Box11_37_5
import Sendov911Box11_37_6
import Sendov911Box11_37_7
import Sendov911Box11_37_8
import Sendov911Box11_37_9

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D11-6/7 assembly for row 37 (generated by emit_assembly1011.py; do not
hand-edit)

`a ∈ [37/100, 19/50]`, S = 1818819854227409463588297168556173289/244174957275390625000000000000000000, λ = 95441/100000, Y = 597/2000.  Per η-strip j: the `Box`
value, the hEq identity against the shipped `boxes11v2` table (regenerated
from the verifier arithmetic — `split_cert` at the box's recorded τ — and
matched integer-for-integer before emission), the strip membership, and the
row reduction `red_37` (strip cover → `split_row_nonpos` → pullback).
-/

namespace SendovN.Red11_37

open Finset Sendov911Capstone

/-- Stage 1: the τ = 1 certificate closed form, evaluated
(coefficients from the verifier's own `split_cert` arithmetic). -/
theorem Peq_37_t0 (a eta : ℝ) :
    (1 - a) / 11 + eta ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) a eta ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) a eta (1 : ℝ)
    = (2512315443948678888143183268983186522234022709598717554001960830790562550804518483537605599561103694635023630805314332288658925257458384631396692114783923194028431410809791829634551/28476282316482538531253147038018118798777309166687709890072865981380800803890451788902282714843750000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ)
      + (1/22 : ℝ) * eta ^ 2
      + (-1/11 : ℝ) * a
      + (76437493913370069243466461745733368563914487372892436004663349334964795003704406362601919970146305364976369194685667711341074742541615368603307885216076805971568589190208170365449/5695256463296507706250629407603623759755461833337541978014573196276160160778090357780456542968750000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 2
      + (127833638946390272196527786884907228845677640210756826426384027380885203928909548992842429303775833519903400708118268496625255256708459683505441/4664898093438109378829117766023041593767550772042795870220288634300231933593750000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 2 * eta ^ 2
      + (-2642234314723199604322321255829207282173954431372871323605793711312536391462742883778230013907458571623817076404178108712532015770125379050516323/9331120317283147509066664992125918198784262358458363451063632965087890625000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 3 * eta ^ 2
      + (-76437493913370069243466461745733368563914487372892436004663349334964795003704406362601919970146305364976369194685667711341074742541615368603307885216076805971568589190208170365449/2847628231648253853125314703801811879877730916668770989007286598138080080389045178890228271484375000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4
      + (-127833638946390272196527786884907228845677640210756826426384027380885203928909548992842429303775833519903400708118268496625255256708459683505441/1166224523359527344707279441505760398441887693010698967555072158575057983398437500000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 2
      + (-701282500308315587469796279671513040489271596172141298161760761052064083889564292569100591440898597842536569/1273829828333449681876388126511301379650831222534179687500000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 3
      + (-213788265544086655453186038314455095121768627227614748847091150190328405772870795864999028940898597842536569/1910473598722429259953725644294308949611149728298187255859375000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 4
      + (655720913000333482514401303974411354783875491376041469934462297256184087586185919092349680496142652297261017670563050753705333381708459683505441/777593359773595625755555416010493183232021863204863620921969413757324218750000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 5 * eta ^ 2
      + (-1815381404334871178661222964213510171432757587849601536568886960775980248497284678421982352181071712649296924401/5095319313333798727505552506045205518603324890136718750000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 5 * eta ^ 4
      + (76437493913370069243466461745733368563914487372892436004663349334964795003704406362601919970146305364976369194685667711341074742541615368603307885216076805971568589190208170365449/2847628231648253853125314703801811879877730916668770989007286598138080080389045178890228271484375000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6
      + (383500916839170816589583360654721686537032920632270479279152082142655611786728646978527287911327500559710202124354805489875765770125379050516323/2332449046719054689414558883011520796883775386021397935110144317150115966796875000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 2
      + (1779113316371325014321807053350573046131327947638238708909992794869469269639519503531276383697695793527609707/1273829828333449681876388126511301379650831222534179687500000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 3
      + (641364796632259966359558114943365285365305881682844246541273450570985217318612387594997086822695793527609707/1910473598722429259953725644294308949611149728298187255859375000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 4
      + (-13378935973373866196674755709292285171676343526702829279605616459338627941/125204960496921557933092117309570312500000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 5
      + (357538304166686834438784055581475016707628049843921929981219831397077521/1564839916460161839495413005352020263671875000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 6
      + (-1585672775998371783250972563919002609296677179360236871420290010226380847470125911454341016398680102779866217119200195809699984520125379050516323/1555186719547191251511110832020986366464043726409727241843938827514648437500000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 2
      + (4833554416704657168661079554807625517501442175148216350643907505252881437584304711230302525293215137947890773203/5095319313333798727505552506045205518603324890136718750000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 4
      + (34741105530275891115871151557357217359179024850056412024717907689153554038887/28171116111807350534945726394653320312500000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 6
      + (-76437493913370069243466461745733368563914487372892436004663349334964795003704406362601919970146305364976369194685667711341074742541615368603307885216076805971568589190208170365449/5695256463296507706250629407603623759755461833337541978014573196276160160778090357780456542968750000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8
      + (-127833638946390272196527786884907228845677640210756826426384027380885203928909548992842429303775833519903400708118268496625255256708459683505441/1166224523359527344707279441505760398441887693010698967555072158575057983398437500000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 2
      + (-1559910942472291726079784656083867660568367164120921958687744001773175975110346129355250993072695793527609707/1273829828333449681876388126511301379650831222534179687500000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 3
      + (-641364796632259966359558114943365285365305881682844246541273450570985217318612387594997086822695793527609707/1910473598722429259953725644294308949611149728298187255859375000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 4
      + (4131804506906274490409729574987212054602627305938703509868538819779542647/20867493416153592988848686218261718750000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 5
      + (-357538304166686834438784055581475016707628049843921929981219831397077521/782419958230080919747706502676010131835937500000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 6
      + (106662122028083226434867453175927292959/122087478637695312500000000000000000000 : ℝ) * a ^ 8 * eta ^ 7
      + (-597945067850456338588297168556173289/2563473230705261230468750000000000000 : ℝ) * a ^ 8 * eta ^ 8
      + (4022887997637773765727704249807332088637641821237690269843154115991685340883759828389546331539645027864199706180133718074851906685376137151548969/6998340237962360631799998744094438649088196768843772588297724723815917968750000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 2
      + (-4382541120080578681456695856164710647509965627000633314929890891178310410926755387194657994043215137947890773203/5095319313333798727505552506045205518603324890136718750000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 4
      + (-42090714337657371154876744436985460328621325293820894875809184886054569478569/18110003214733296772465109825134277343750000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 6
      + (-24137451024474338983147104021159632184067471/18987044677734375000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 8
      + (76437493913370069243466461745733368563914487372892436004663349334964795003704406362601919970146305364976369194685667711341074742541615368603307885216076805971568589190208170365449/28476282316482538531253147038018118798777309166687709890072865981380800803890451788902282714843750000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10
      + (127833638946390272196527786884907228845677640210756826426384027380885203928909548992842429303775833519903400708118268496625255256708459683505441/4664898093438109378829117766023041593767550772042795870220288634300231933593750000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 2
      + (1400746456787366551902022071267590772648545608588252940693535903867312368081172755179225602447695793527609707/3821489485000349045629164379533904138952493667602539062500000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 3
      + (213788265544086655453186038314455095121768627227614748847091150190328405772870795864999028940898597842536569/1910473598722429259953725644294308949611149728298187255859375000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 4
      + (-4975983900256532944065832526467409673974037275255453619830978482573697689/53659268784394953399896621704101562500000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 5
      + (357538304166686834438784055581475016707628049843921929981219831397077521/1564839916460161839495413005352020263671875000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 6
      + (-920921626958345961741932078583345636631/1098787307739257812500000000000000000000 : ℝ) * a ^ 10 * eta ^ 7
      + (597945067850456338588297168556173289/2563473230705261230468750000000000000 : ℝ) * a ^ 10 * eta ^ 8
      + (-147/250 : ℝ) * a ^ 10 * eta ^ 9
      + (100000/1049851 : ℝ) * a ^ 10 * eta ^ 10
      + (-1170484389386220825588331997912276490148983164350260431231064059817431570929079114456648495707032676416384107834222282906867953270125379050516323/9331120317283147509066664992125918198784262358458363451063632965087890625000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 2
      + (192092651462629991134285656404701979529563727717615366193552906671629888834247907769476831561581673235613846343/727902759047685532500793215149315074086189270019531250000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 4
      + (39951517310361357590053871585018145799235690066140688576981059886054569478569/36220006429466593544930219650268554687500000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 6
      + (863923366386950615550587185968875266076573/703223876953125000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 8
      + (1073407/1900800 : ℝ) * a ^ 11 * eta ^ 10 := by
  rw [EmajEq.EmajTau11_eq]
  unfold MidChainN.hh
  push_cast
  norm_num
  ring

/-! ### Strip 0: `η ∈ [0, 597/20000]`, τ = 1 -/

noncomputable def box_37_0 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_0.tab Sendov911Box11_37_0.Adata
  D := (Sendov911Box11_37_0.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_0.Dscale]

theorem eq_37_0 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((0 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((0 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_0.tab Sendov911Box11_37_0.Adata k l : ℝ)
          / (Sendov911Box11_37_0.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_0.tab, Sendov911Box11_37_0.Adata, Sendov911Box11_37_0.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 1: `η ∈ [597/20000, 597/10000]`, τ = 1 -/

noncomputable def box_37_1 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_1.tab Sendov911Box11_37_1.Adata
  D := (Sendov911Box11_37_1.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_1.Dscale]

theorem eq_37_1 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((597/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/20000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_1.tab Sendov911Box11_37_1.Adata k l : ℝ)
          / (Sendov911Box11_37_1.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_1.tab, Sendov911Box11_37_1.Adata, Sendov911Box11_37_1.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 2: `η ∈ [597/10000, 1791/20000]`, τ = 1 -/

noncomputable def box_37_2 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_2.tab Sendov911Box11_37_2.Adata
  D := (Sendov911Box11_37_2.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_2.Dscale]

theorem eq_37_2 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((597/10000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/10000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/10000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_2.tab Sendov911Box11_37_2.Adata k l : ℝ)
          / (Sendov911Box11_37_2.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_2.tab, Sendov911Box11_37_2.Adata, Sendov911Box11_37_2.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 3: `η ∈ [1791/20000, 597/5000]`, τ = 1 -/

noncomputable def box_37_3 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_3.tab Sendov911Box11_37_3.Adata
  D := (Sendov911Box11_37_3.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_3.Dscale]

theorem eq_37_3 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((1791/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((1791/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((1791/20000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_3.tab Sendov911Box11_37_3.Adata k l : ℝ)
          / (Sendov911Box11_37_3.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_3.tab, Sendov911Box11_37_3.Adata, Sendov911Box11_37_3.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 4: `η ∈ [597/5000, 597/4000]`, τ = 1 -/

noncomputable def box_37_4 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_4.tab Sendov911Box11_37_4.Adata
  D := (Sendov911Box11_37_4.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_4.Dscale]

theorem eq_37_4 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((597/5000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/5000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/5000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_4.tab Sendov911Box11_37_4.Adata k l : ℝ)
          / (Sendov911Box11_37_4.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_4.tab, Sendov911Box11_37_4.Adata, Sendov911Box11_37_4.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 5: `η ∈ [597/4000, 1791/10000]`, τ = 1 -/

noncomputable def box_37_5 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_5.tab Sendov911Box11_37_5.Adata
  D := (Sendov911Box11_37_5.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_5.Dscale]

theorem eq_37_5 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((597/4000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/4000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/4000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_5.tab Sendov911Box11_37_5.Adata k l : ℝ)
          / (Sendov911Box11_37_5.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_5.tab, Sendov911Box11_37_5.Adata, Sendov911Box11_37_5.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 6: `η ∈ [1791/10000, 4179/20000]`, τ = 1 -/

noncomputable def box_37_6 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_6.tab Sendov911Box11_37_6.Adata
  D := (Sendov911Box11_37_6.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_6.Dscale]

theorem eq_37_6 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((1791/10000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((1791/10000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((1791/10000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_6.tab Sendov911Box11_37_6.Adata k l : ℝ)
          / (Sendov911Box11_37_6.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_6.tab, Sendov911Box11_37_6.Adata, Sendov911Box11_37_6.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 7: `η ∈ [4179/20000, 597/2500]`, τ = 1 -/

noncomputable def box_37_7 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_7.tab Sendov911Box11_37_7.Adata
  D := (Sendov911Box11_37_7.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_7.Dscale]

theorem eq_37_7 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((4179/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((4179/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((4179/20000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_7.tab Sendov911Box11_37_7.Adata k l : ℝ)
          / (Sendov911Box11_37_7.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_7.tab, Sendov911Box11_37_7.Adata, Sendov911Box11_37_7.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 8: `η ∈ [597/2500, 5373/20000]`, τ = 1 -/

noncomputable def box_37_8 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_8.tab Sendov911Box11_37_8.Adata
  D := (Sendov911Box11_37_8.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_8.Dscale]

theorem eq_37_8 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((597/2500 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/2500 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((597/2500 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_8.tab Sendov911Box11_37_8.Adata k l : ℝ)
          / (Sendov911Box11_37_8.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_8.tab, Sendov911Box11_37_8.Adata, Sendov911Box11_37_8.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 9: `η ∈ [5373/20000, 597/2000]`, τ = 1 -/

noncomputable def box_37_9 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_37_9.tab Sendov911Box11_37_9.Adata
  D := (Sendov911Box11_37_9.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_37_9.Dscale]

theorem eq_37_9 (U V : ℝ) :
    (1 - ((37/100 : ℝ) + (1/100) * U)) / 11 + ((5373/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((5373/20000 : ℝ) + (597/20000 : ℝ) * V) ^ 5 / (11 * (95441/100000 : ℝ))
      - Split11.EmajTau CTab11.c11 (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) ((37/100 : ℝ) + (1/100) * U) ((5373/20000 : ℝ) + (597/20000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_37_9.tab Sendov911Box11_37_9.Adata k l : ℝ)
          / (Sendov911Box11_37_9.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_37_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_37_9.tab, Sendov911Box11_37_9.Adata, Sendov911Box11_37_9.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

noncomputable def row_37 : List Box :=
  [box_37_0, box_37_1, box_37_2, box_37_3, box_37_4, box_37_5, box_37_6, box_37_7, box_37_8, box_37_9]

theorem mem_37_0 : box_37_0 ∈ row_37 :=
  List.Mem.head _

theorem mem_37_1 : box_37_1 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.head _)

theorem mem_37_2 : box_37_2 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))

theorem mem_37_3 : box_37_3 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))

theorem mem_37_4 : box_37_4 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))

theorem mem_37_5 : box_37_5 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))

theorem mem_37_6 : box_37_6 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))

theorem mem_37_7 : box_37_7 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))

theorem mem_37_8 : box_37_8 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))))

theorem mem_37_9 : box_37_9 ∈ row_37 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))))

theorem rowPos_37 : CoveringPositive row_37 := by
  unfold row_37
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_0.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_1.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_2.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_3.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_4.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_5.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_6.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_7.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_8.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_37_9.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

theorem red_37 (mu : ℂ) (Df : Fin 10 → ℂ) (rr : Fin 10 → ℝ) (a eta sig : ℝ)
    (h0 : (37/100 : ℝ) ≤ a) (h1 : a ≤ (19/50 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (10:ℝ) ≤ 10 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (563/1000 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (11:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0) (hY1 : ∀ j, ‖mu + Df j‖ ≤ 1)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 10 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 11) :
    ∃ b ∈ row_37, ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly b U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows11.sigma_row_37 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows11.L_row_37 h0 h1
  have hc := CTab11.cTable11 Df eta heta0 hz hD2
  have hloc' : ((10:ℕ):ℝ) ≤ ((10:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) * a ^ 2 - ((10:ℕ):ℝ) * (95441/100000 : ℝ) * a + ((10:ℕ):ℝ) - (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (597/2000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows11.Y_row_37
  obtain ⟨j, hj, hja, hjb⟩ := Cover.cover_grid (by norm_num : (0:ℝ) < (597/20000 : ℝ)) 0 10
    (by norm_num) eta heta0 (by push_cast; linarith)
  interval_cases j
  · -- strip j = 0, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_0, mem_37_0, 100 * (a - (37/100 : ℝ)), (eta - (0 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_0 (100 * (a - (37/100 : ℝ))) ((eta - (0 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (0 : ℝ) + (597/20000 : ℝ) * ((eta - (0 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 1, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_1, mem_37_1, 100 * (a - (37/100 : ℝ)), (eta - (597/20000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_1 (100 * (a - (37/100 : ℝ))) ((eta - (597/20000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (597/20000 : ℝ) + (597/20000 : ℝ) * ((eta - (597/20000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 2, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_2, mem_37_2, 100 * (a - (37/100 : ℝ)), (eta - (597/10000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_2 (100 * (a - (37/100 : ℝ))) ((eta - (597/10000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (597/10000 : ℝ) + (597/20000 : ℝ) * ((eta - (597/10000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 3, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_3, mem_37_3, 100 * (a - (37/100 : ℝ)), (eta - (1791/20000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_3 (100 * (a - (37/100 : ℝ))) ((eta - (1791/20000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (1791/20000 : ℝ) + (597/20000 : ℝ) * ((eta - (1791/20000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 4, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_4, mem_37_4, 100 * (a - (37/100 : ℝ)), (eta - (597/5000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_4 (100 * (a - (37/100 : ℝ))) ((eta - (597/5000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (597/5000 : ℝ) + (597/20000 : ℝ) * ((eta - (597/5000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 5, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_5, mem_37_5, 100 * (a - (37/100 : ℝ)), (eta - (597/4000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_5 (100 * (a - (37/100 : ℝ))) ((eta - (597/4000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (597/4000 : ℝ) + (597/20000 : ℝ) * ((eta - (597/4000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 6, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_6, mem_37_6, 100 * (a - (37/100 : ℝ)), (eta - (1791/10000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_6 (100 * (a - (37/100 : ℝ))) ((eta - (1791/10000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (1791/10000 : ℝ) + (597/20000 : ℝ) * ((eta - (1791/10000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 7, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_7, mem_37_7, 100 * (a - (37/100 : ℝ)), (eta - (4179/20000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_7 (100 * (a - (37/100 : ℝ))) ((eta - (4179/20000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (4179/20000 : ℝ) + (597/20000 : ℝ) * ((eta - (4179/20000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 8, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_8, mem_37_8, 100 * (a - (37/100 : ℝ)), (eta - (597/2500 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_8 (100 * (a - (37/100 : ℝ))) ((eta - (597/2500 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (597/2500 : ℝ) + (597/20000 : ℝ) * ((eta - (597/2500 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 9, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (37/100 : ℝ)) (beta := (19/50 : ℝ))
      (S := (1818819854227409463588297168556173289/244174957275390625000000000000000000 : ℝ)) (lam := (95441/100000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_37
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_37_9, mem_37_9, 100 * (a - (37/100 : ℝ)), (eta - (5373/20000 : ℝ)) / (597/20000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_37_9 (100 * (a - (37/100 : ℝ))) ((eta - (5373/20000 : ℝ)) / (597/20000 : ℝ))
    rw [show (37/100 : ℝ) + (1/100) * (100 * (a - (37/100 : ℝ))) = a by ring] at heq
    rw [show (5373/20000 : ℝ) + (597/20000 : ℝ) * ((eta - (5373/20000 : ℝ)) / (597/20000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP

end SendovN.Red11_37

#print axioms SendovN.Red11_37.Peq_37_t0
#print axioms SendovN.Red11_37.eq_37_0
#print axioms SendovN.Red11_37.eq_37_1
#print axioms SendovN.Red11_37.eq_37_2
#print axioms SendovN.Red11_37.eq_37_3
#print axioms SendovN.Red11_37.eq_37_4
#print axioms SendovN.Red11_37.eq_37_5
#print axioms SendovN.Red11_37.eq_37_6
#print axioms SendovN.Red11_37.eq_37_7
#print axioms SendovN.Red11_37.eq_37_8
#print axioms SendovN.Red11_37.eq_37_9
#print axioms SendovN.Red11_37.rowPos_37
#print axioms SendovN.Red11_37.red_37
