import Mathlib
import SendovNCovering11
import SendovNSmall11
import SendovNSep11
import SendovNRotData
import Sendov9.GWS

set_option maxHeartbeats 16000000

/-!
# D11-10: `CertificateReduction 11 boxes11` (generated by emit_assembly1011.py)

As at degree 10, with the 53-interval cover, the per-row η-strip covers (inside
each `red_i`), and the τ-split row machinery.
-/

namespace SendovN.Reduction11

open Finset Polynomial Sendov911Capstone

/-- **Lemma 2.1 at degree 11** — every other zero is farther than `563/1000`. -/
theorem separation11 (D : DataN 11) (k : Fin (11 - 1)) :
    (563/1000 : ℝ) < ‖(D.a : ℂ) - D.z k‖ := by
  obtain ⟨w, hw, heq⟩ := Sendov9.GWS.graceWalshSzegoPos (11 - 1)
    (SegmentN.uFam D k) ‖(D.a : ℂ) - D.z k‖ (by norm_num)
    (fun j => SegmentN.norm_u_lt D k j)
  rw [SegmentN.integral_uFam_zero D k] at heq
  exact lt_trans (RootUnity11.norm_gt_of_integral_zero11 heq.symm) hw

theorem certificateReduction11 : CertificateReduction 11 Covering11.boxes11 := by
  intro hbad
  unfold Sendov at hbad
  push_neg at hbad
  obtain ⟨p, hm, hdeg, hroots, a0, ha0mem, hno⟩ := hbad
  obtain ⟨D⟩ := RotDataN.exists_data (by norm_num) hm hdeg hroots ha0mem
    (fun z hz => hno z (isRoot_of_mem_roots hz))
  have hsep : ∀ k, (563/1000 : ℝ) ≤ D.r k := fun k => (separation11 D k).le
  have hprodgt : (11:ℝ) < ∏ k, D.r k := by
    have h := D.prod_r_gt_n
    norm_num at h
    exact h
  have hprod11 : (11:ℝ) ≤ ∏ k, D.r k := hprodgt.le
  have heta0 : 0 ≤ D.eta := D.eta_nonneg
  have hnormSq : Complex.normSq D.mu = 1 - D.eta ^ 2 := by
    have := D.eta_sq
    linarith
  have hloc10 : (10:ℝ) ≤ 10 * D.a * D.mu.re + (1 - D.a ^ 2) * D.sigma := by
    have h := D.localization
    simp only [DataN.u] at h
    norm_num at h
    exact h
  have hz : ∑ j, D.dev j = 0 := D.sum_dev_zero
  have hD2 : ∑ j, ‖D.dev j‖ ^ 2 ≤ 10 * D.eta ^ 2 := by
    have h := D.sum_normSq_dev_le
    norm_num at h
    exact h
  have hu1 : D.mu.re < 1 := lt_of_le_of_lt (Complex.re_le_norm D.mu) D.mu_norm_lt_one
  have hYd : ∀ j, D.mu + D.dev j = ((D.a : ℂ) - D.zeta j)⁻¹ := by
    intro j
    unfold DataN.dev DataN.Y
    ring
  have hY1 : ∀ j, ‖D.mu + D.dev j‖ ≤ 1 := by
    intro j
    rw [hYd j]
    exact (D.norm_Y_lt_one j).le
  rcases le_or_gt D.a (37/100) with hsm | hmid0
  · exfalso
    rcases le_or_gt D.a (27/100) with hpp | hqq
    · exact Small11.product_excluded D.ha0 hpp (fun k => (D.r_pos k).le)
        (fun k => by have := D.r_le k; linarith) hprodgt
    · have hsig' : D.sigma ≤ 36/5 := by
        rw [D.sigma_eq]
        exact Small11.sigma_small D.r hsep
          (fun k => by have := D.r_le k; linarith) hprod11
      exact Small11.quad_excluded hqq.le hsm hsig' hloc10 hu1
  have ha0 : 0 < D.a := by linarith
  have hI0 := D.norm_I_lt ha0
  have hI : ‖∫ t in (0:ℝ)..D.a, ∏ j, ((1:ℂ) - (t:ℂ) * (D.mu + D.dev j))‖
      < D.a / 11 := by
    simp only [hYd]
    push_cast at hI0
    exact hI0
  rcases le_or_gt D.a (9/10) with hmid | htop
  · obtain ⟨i, hi, hia, hib⟩ := Cover.cover_grid (by norm_num : (0:ℝ) < 1/100)
      (37/100) 53 (by norm_num) D.a (by linarith) (by push_cast; linarith)
    interval_cases i
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_37.red_37 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_37 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_38.red_38 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_38 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_39.red_39 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_39 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_40.red_40 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_40 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_41.red_41 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_41 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_42.red_42 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_42 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_43.red_43 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_43 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_44.red_44 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_44 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_45.red_45 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_45 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_46.red_46 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_46 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_47.red_47 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_47 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_48.red_48 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_48 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_49.red_49 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_49 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_50.red_50 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_50 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_51.red_51 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_51 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_52.red_52 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_52 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_53.red_53 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_53 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_54.red_54 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_54 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_55.red_55 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_55 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_56.red_56 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_56 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_57.red_57 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_57 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_58.red_58 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_58 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_59.red_59 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_59 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_60.red_60 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_60 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_61.red_61 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_61 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_62.red_62 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_62 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_63.red_63 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_63 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_64.red_64 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_64 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_65.red_65 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_65 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_66.red_66 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_66 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_67.red_67 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_67 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_68.red_68 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_68 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_69.red_69 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_69 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_70.red_70 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_70 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_71.red_71 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_71 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_72.red_72 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_72 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_73.red_73 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_73 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_74.red_74 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_74 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_75.red_75 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_75 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_76.red_76 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_76 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_77.red_77 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_77 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_78.red_78 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_78 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_79.red_79 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_79 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_80.red_80 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_80 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_81.red_81 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_81 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_82.red_82 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_82 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_83.red_83 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_83 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_84.red_84 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_84 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_85.red_85 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_85 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_86.red_86 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_86 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_87.red_87 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_87 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_88.red_88 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_88 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
    · push_cast at hia hib
      obtain ⟨b, hb, U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11_89.red_89 D.mu D.dev
        D.r D.a D.eta D.sigma (by linarith) (by linarith) heta0 hnormSq hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨b, Covering11.lift_89 hb, U, V, hu1', hu2, hv1, hv2, hle⟩
  · rcases lt_or_eq_of_le D.ha1 with hlt1 | hone
    · have hetau : D.eta ^ 2 ≤ 1 - D.mu.re ^ 2 := by
        have h := D.eta_sq_le_one_sub_u_sq
        simpa [DataN.u] using h
      obtain ⟨U, V, hu1', hu2, hv1, hv2, hle⟩ := Red11Bdry.red_bdry D.mu D.dev D.r
        D.a D.eta D.sigma htop.le hlt1 heta0 hnormSq hetau D.mu_norm_lt_one hloc10
        D.sigma_eq hsep D.r_le hprod11 hz hY1 hD2 hI
      exact ⟨Red11Bdry.boxB11, Covering11.mem_bdry, U, V, hu1', hu2, hv1, hv2, hle⟩
    · exact (D.one_excluded hone).elim

end SendovN.Reduction11

#print axioms SendovN.Reduction11.separation11
#print axioms SendovN.Reduction11.certificateReduction11
