import Mathlib
import SendovNEmajEq
import SendovNRows11
import SendovNCoverGrid
import Sendov911Box11_44_0
import Sendov911Box11_44_1
import Sendov911Box11_44_2
import Sendov911Box11_44_3
import Sendov911Box11_44_4
import Sendov911Box11_44_5
import Sendov911Box11_44_6
import Sendov911Box11_44_7
import Sendov911Box11_44_8
import Sendov911Box11_44_9

set_option maxHeartbeats 4000000000
set_option maxRecDepth 100000

/-!
# D11-6/7 assembly for row 44 (generated by emit_assembly1011.py; do not
hand-edit)

`a ∈ [11/25, 9/20]`, S = 168267187730202318381949471143517965721/21138690807562240000000000000000000000, λ = 1623/2000, Y = 14609/25000.  Per η-strip j: the `Box`
value, the hEq identity against the shipped `boxes11v2` table (regenerated
from the verifier arithmetic — `split_cert` at the box's recorded τ — and
matched integer-for-integer before emission), the strip membership, and the
row reduction `red_44` (strip cover → `split_row_nonpos` → pullback).
-/

namespace SendovN.Red11_44

open Finset Sendov911Capstone

/-- Stage 1: the τ = 1 certificate closed form, evaluated
(coefficients from the verifier's own `split_cert` arithmetic). -/
theorem Peq_44_t0 (a eta : ℝ) :
    (1 - a) / 11 + eta ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) a eta ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) a eta (1 : ℝ)
    = (9744264955830449000815253202746553359854201864594109644496640323677982638064444313664563349232613576601910486099914384440116376822842894555103357292903718803403680150647559068078912190507399/117739357948179402575614106723774808261815825241629546633776913135595046809108480000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ)
      + (1/22 : ℝ) * eta ^ 2
      + (-1/11 : ℝ) * a
      + (959313039458587596967847408505701936674509521008576413119442688648839799127235686335436650767386423398089513900085615559883623177157105444896642707096281196596319849352440931921087809492601/23547871589635880515122821344754961652363165048325909326755382627119009361821696000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 2
      + (15330922143379127920767954259242545879774278051076702149850977171949229727699608236439169378032138679076764802922991065130247502409696088565368826125281/222794039649908408926745875039186324841664111785700363839031214080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 2 * eta ^ 2
      + (-219559640541144693687474707764952937162534154601937184253461384050572191840714218399203339257904907032047417401978046592329242193629088265696106478375843/524133180154380394047125231145792059785464218618686791084933120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 3 * eta ^ 2
      + (-959313039458587596967847408505701936674509521008576413119442688648839799127235686335436650767386423398089513900085615559883623177157105444896642707096281196596319849352440931921087809492601/11773935794817940257561410672377480826181582524162954663377691313559504680910848000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4
      + (-15330922143379127920767954259242545879774278051076702149850977171949229727699608236439169378032138679076764802922991065130247502409696088565368826125281/55698509912477102231686468759796581210416027946425090959757803520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 2
      + (-650764804585592569859328131964813880727541429684067799930446429777632197608901675145112961000169163513962380500361/826498961747235057074620890595287997171210649600000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 3
      + (-245005711481834547699036801260587643488389450207291037820261603843573094402678390762238951400169163513962380500361/1053963283148099105282371911414119758106973123379200000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 4 * eta ^ 4
      + (58086201471850140658787493930564750659311569614721161546403785350131563681170772099808355367031203699778363738300826501673528654409696088565368826125281/43677765012865032837260435928816004982122018218223899257077760000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 5 * eta ^ 2
      + (-1739598703009347011465974149687129345706989486214605716567012591004182471185071533409913772678329312635188288585629569/3305995846988940228298483562381151988684842598400000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 5 * eta ^ 4
      + (959313039458587596967847408505701936674509521008576413119442688648839799127235686335436650767386423398089513900085615559883623177157105444896642707096281196596319849352440931921087809492601/11773935794817940257561410672377480826181582524162954663377691313559504680910848000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6
      + (15330922143379127920767954259242545879774278051076702149850977171949229727699608236439169378032138679076764802922991065130247502409696088565368826125281/37132339941651401487790979173197720806944018630950060639838535680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 2
      + (1707158307718549989967029118768734627936915907928956394104842668333157817025149204339620380600507490541887141501083/826498961747235057074620890595287997171210649600000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 3
      + (245005711481834547699036801260587643488389450207291037820261603843573094402678390762238951400169163513962380500361/351321094382699701760790637138039919368991041126400000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 4
      + (-133077825614720733279866108954433282088562897409145953526093047000576752046661/938372923021204327204740095016960000000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 5
      + (3915472148206283425812457267858162570481696970110795348861573666694131049841/9971887973034262412848943402582016000000000000000000000000000000000000000000 : ℝ) * a ^ 6 * eta ^ 6
      + (-146971842032520529695721897386186168830934957569309435382691956096783888793937782354793550435743040776741933027826912417711929732829088265696106478375843/87355530025730065674520871857632009964244036436447798514155520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 2
      + (4746423577695016645753962115149700881639260453994211765979164275600839676044305522737548408313387937905564865756888707/3305995846988940228298483562381151988684842598400000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 4
      + (349465949565540116644578126075098132885692639018964967391719237615793447586705927/211133907679770973621066521378816000000000000000000000000000000000000000000000000 : ℝ) * a ^ 7 * eta ^ 6
      + (-959313039458587596967847408505701936674509521008576413119442688648839799127235686335436650767386423398089513900085615559883623177157105444896642707096281196596319849352440931921087809492601/23547871589635880515122821344754961652363165048325909326755382627119009361821696000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8
      + (-15330922143379127920767954259242545879774278051076702149850977171949229727699608236439169378032138679076764802922991065130247502409696088565368826125281/55698509912477102231686468759796581210416027946425090959757803520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 2
      + (-1534519162653086051745017421060628003347562258223726993471329518838827041223593383243901878200507490541887141501083/826498961747235057074620890595287997171210649600000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 3
      + (-245005711481834547699036801260587643488389450207291037820261603843573094402678390762238951400169163513962380500361/351321094382699701760790637138039919368991041126400000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 4
      + (124945034175245777874065766729956407854290979516166036726093047000576752046661/469186461510602163602370047508480000000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 5
      + (-3915472148206283425812457267858162570481696970110795348861573666694131049841/4985943986517131206424471701291008000000000000000000000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 6
      + (32309848785621102003504457864186492719053/31708036211343360000000000000000000000000 : ℝ) * a ^ 8 * eta ^ 7
      + (-62573733692391118381949471143517965721/188694523493704335360000000000000000000 : ℝ) * a ^ 8 * eta ^ 8
      + (385718057034438686930673440902194620086260343911116761856981169972102185642682963014326376785559588192803828522254035991209820507287264797088319435127529/393099885115785295535343923359344044839098163964015093313699840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 2
      + (-4386082991824102752018558827994012092637613225292821860092025225240801442533396445245355498591787937905564865756888707/3305995846988940228298483562381151988684842598400000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 4
      + (-427853644063307706902669261787259929944629702040212343655319019791734432611479049/135728940651281340184971335172096000000000000000000000000000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 6
      + (-2445255118816287362706423955170317519725581919/1643744597196039782400000000000000000000000000 : ℝ) * a ^ 9 * eta ^ 8
      + (959313039458587596967847408505701936674509521008576413119442688648839799127235686335436650767386423398089513900085615559883623177157105444896642707096281196596319849352440931921087809492601/117739357948179402575614106723774808261815825241629546633776913135595046809108480000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10
      + (15330922143379127920767954259242545879774278051076702149850977171949229727699608236439169378032138679076764802922991065130247502409696088565368826125281/222794039649908408926745875039186324841664111785700363839031214080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 2
      + (1404859158497984642873569985248861482801305816736515197890799840849904265422037562148183375800507490541887141501083/2479496885241705171223862671785863991513631948800000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 3
      + (245005711481834547699036801260587643488389450207291037820261603843573094402678390762238951400169163513962380500361/1053963283148099105282371911414119758106973123379200000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 4
      + (-50700738671127090123953712607802085837151026409936908539754163000247179448569/402159824151944711659174326435840000000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 5
      + (3915472148206283425812457267858162570481696970110795348861573666694131049841/9971887973034262412848943402582016000000000000000000000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 6
      + (-93549998164004292890513373592559478157159/95124108634030080000000000000000000000000 : ℝ) * a ^ 10 * eta ^ 7
      + (62573733692391118381949471143517965721/188694523493704335360000000000000000000 : ℝ) * a ^ 10 * eta ^ 8
      + (-147/250 : ℝ) * a ^ 10 * eta ^ 9
      + (2000/17853 : ℝ) * a ^ 10 * eta ^ 10
      + (-115228742185532675325421809127489703330987153691042963787095410199772820426618970022170791579424076961913120653675778243094617272029088265696106478375843/524133180154380394047125231145792059785464218618686791084933120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 2
      + (195209069122925131497627102622136065999412376130230830097124791520592033953451779416817266136675616090741184083661367/472285120998420032614069080340164569812120371200000000000000000000000000000000000000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 4
      + (409670787061892381300849285272665113036226011056041157806999019791734432611479049/271457881302562680369942670344192000000000000000000000000000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 6
      + (29320991066179379630370666113213796539821999/20293143175259750400000000000000000000000000 : ℝ) * a ^ 11 * eta ^ 8
      + (1073407/1900800 : ℝ) * a ^ 11 * eta ^ 10 := by
  rw [EmajEq.EmajTau11_eq]
  unfold MidChainN.hh
  push_cast
  norm_num
  ring

/-! ### Strip 0: `η ∈ [0, 14609/250000]`, τ = 1 -/

noncomputable def box_44_0 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_0.tab Sendov911Box11_44_0.Adata
  D := (Sendov911Box11_44_0.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_0.Dscale]

theorem eq_44_0 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((0 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((0 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((0 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_0.tab Sendov911Box11_44_0.Adata k l : ℝ)
          / (Sendov911Box11_44_0.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_0.tab, Sendov911Box11_44_0.Adata, Sendov911Box11_44_0.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 1: `η ∈ [14609/250000, 14609/125000]`, τ = 1 -/

noncomputable def box_44_1 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_1.tab Sendov911Box11_44_1.Adata
  D := (Sendov911Box11_44_1.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_1.Dscale]

theorem eq_44_1 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((14609/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/250000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_1.tab Sendov911Box11_44_1.Adata k l : ℝ)
          / (Sendov911Box11_44_1.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_1.tab, Sendov911Box11_44_1.Adata, Sendov911Box11_44_1.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 2: `η ∈ [14609/125000, 43827/250000]`, τ = 1 -/

noncomputable def box_44_2 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_2.tab Sendov911Box11_44_2.Adata
  D := (Sendov911Box11_44_2.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_2.Dscale]

theorem eq_44_2 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((14609/125000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/125000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/125000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_2.tab Sendov911Box11_44_2.Adata k l : ℝ)
          / (Sendov911Box11_44_2.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_2.tab, Sendov911Box11_44_2.Adata, Sendov911Box11_44_2.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 3: `η ∈ [43827/250000, 14609/62500]`, τ = 1 -/

noncomputable def box_44_3 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_3.tab Sendov911Box11_44_3.Adata
  D := (Sendov911Box11_44_3.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_3.Dscale]

theorem eq_44_3 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((43827/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((43827/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((43827/250000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_3.tab Sendov911Box11_44_3.Adata k l : ℝ)
          / (Sendov911Box11_44_3.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_3.tab, Sendov911Box11_44_3.Adata, Sendov911Box11_44_3.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 4: `η ∈ [14609/62500, 14609/50000]`, τ = 1 -/

noncomputable def box_44_4 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_4.tab Sendov911Box11_44_4.Adata
  D := (Sendov911Box11_44_4.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_4.Dscale]

theorem eq_44_4 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((14609/62500 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/62500 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/62500 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_4.tab Sendov911Box11_44_4.Adata k l : ℝ)
          / (Sendov911Box11_44_4.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_4.tab, Sendov911Box11_44_4.Adata, Sendov911Box11_44_4.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 5: `η ∈ [14609/50000, 43827/125000]`, τ = 1 -/

noncomputable def box_44_5 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_5.tab Sendov911Box11_44_5.Adata
  D := (Sendov911Box11_44_5.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_5.Dscale]

theorem eq_44_5 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((14609/50000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/50000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/50000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_5.tab Sendov911Box11_44_5.Adata k l : ℝ)
          / (Sendov911Box11_44_5.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_5.tab, Sendov911Box11_44_5.Adata, Sendov911Box11_44_5.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 6: `η ∈ [43827/125000, 102263/250000]`, τ = 1 -/

noncomputable def box_44_6 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_6.tab Sendov911Box11_44_6.Adata
  D := (Sendov911Box11_44_6.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_6.Dscale]

theorem eq_44_6 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((43827/125000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((43827/125000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((43827/125000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_6.tab Sendov911Box11_44_6.Adata k l : ℝ)
          / (Sendov911Box11_44_6.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_6.tab, Sendov911Box11_44_6.Adata, Sendov911Box11_44_6.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 7: `η ∈ [102263/250000, 14609/31250]`, τ = 1 -/

noncomputable def box_44_7 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_7.tab Sendov911Box11_44_7.Adata
  D := (Sendov911Box11_44_7.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_7.Dscale]

theorem eq_44_7 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((102263/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((102263/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((102263/250000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_7.tab Sendov911Box11_44_7.Adata k l : ℝ)
          / (Sendov911Box11_44_7.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_7.tab, Sendov911Box11_44_7.Adata, Sendov911Box11_44_7.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 8: `η ∈ [14609/31250, 131481/250000]`, τ = 1 -/

noncomputable def box_44_8 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_8.tab Sendov911Box11_44_8.Adata
  D := (Sendov911Box11_44_8.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_8.Dscale]

theorem eq_44_8 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((14609/31250 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/31250 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((14609/31250 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_8.tab Sendov911Box11_44_8.Adata k l : ℝ)
          / (Sendov911Box11_44_8.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_8.tab, Sendov911Box11_44_8.Adata, Sendov911Box11_44_8.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

/-! ### Strip 9: `η ∈ [131481/250000, 14609/25000]`, τ = 1 -/

noncomputable def box_44_9 : Box where
  nx := 11
  ny := 10
  A := Sendov911Box11_44_9.tab Sendov911Box11_44_9.Adata
  D := (Sendov911Box11_44_9.Dscale : ℝ)
  hD := by norm_num [Sendov911Box11_44_9.Dscale]

theorem eq_44_9 (U V : ℝ) :
    (1 - ((11/25 : ℝ) + (1/100) * U)) / 11 + ((131481/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 2 / 22
      - MidChainN.hh 10 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((131481/250000 : ℝ) + (14609/250000 : ℝ) * V) ^ 5 / (11 * (1623/2000 : ℝ))
      - Split11.EmajTau CTab11.c11 (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) ((11/25 : ℝ) + (1/100) * U) ((131481/250000 : ℝ) + (14609/250000 : ℝ) * V) (1 : ℝ)
    = ∑ k ∈ Finset.range 12, ∑ l ∈ Finset.range 11,
        ((Sendov911Box11_44_9.tab Sendov911Box11_44_9.Adata k l : ℝ)
          / (Sendov911Box11_44_9.Dscale : ℝ)) * U ^ k * V ^ l := by
  rw [Peq_44_t0]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero,
    Sendov911Box11_44_9.tab, Sendov911Box11_44_9.Adata, Sendov911Box11_44_9.Dscale,
    List.getD_cons_zero, List.getD_cons_succ, zero_add]
  norm_num
  ring

noncomputable def row_44 : List Box :=
  [box_44_0, box_44_1, box_44_2, box_44_3, box_44_4, box_44_5, box_44_6, box_44_7, box_44_8, box_44_9]

theorem mem_44_0 : box_44_0 ∈ row_44 :=
  List.Mem.head _

theorem mem_44_1 : box_44_1 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.head _)

theorem mem_44_2 : box_44_2 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))

theorem mem_44_3 : box_44_3 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))

theorem mem_44_4 : box_44_4 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))

theorem mem_44_5 : box_44_5 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))

theorem mem_44_6 : box_44_6 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))

theorem mem_44_7 : box_44_7 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))

theorem mem_44_8 : box_44_8 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _))))))))

theorem mem_44_9 : box_44_9 ∈ row_44 :=
  List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.head _)))))))))

theorem rowPos_44 : CoveringPositive row_44 := by
  unfold row_44
  refine coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_0.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_1.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_2.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_3.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_4.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_5.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_6.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_7.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_8.box_positive h1 h2 h3 h4)
    (coveringPositive_cons (fun _ _ h1 h2 h3 h4 => Sendov911Box11_44_9.box_positive h1 h2 h3 h4)
    (coveringPositive_nil))))))))))

theorem red_44 (mu : ℂ) (Df : Fin 10 → ℂ) (rr : Fin 10 → ℝ) (a eta sig : ℝ)
    (h0 : (11/25 : ℝ) ≤ a) (h1 : a ≤ (9/20 : ℝ))
    (heta0 : 0 ≤ eta) (hnormSq : Complex.normSq mu = 1 - eta ^ 2)
    (hloc : (10:ℝ) ≤ 10 * a * mu.re + (1 - a ^ 2) * sig)
    (hsigeq : sig = ∑ k, 1 / rr k ^ 2)
    (hrlo : ∀ k, (563/1000 : ℝ) ≤ rr k) (hrhi : ∀ k, rr k ≤ a + 1)
    (hprod : (11:ℝ) ≤ ∏ k, rr k)
    (hz : ∑ j, Df j = 0) (hY1 : ∀ j, ‖mu + Df j‖ ≤ 1)
    (hD2 : ∑ j, ‖Df j‖ ^ 2 ≤ 10 * eta ^ 2)
    (hI : ‖∫ t in (0:ℝ)..a, ∏ j, ((1:ℂ) - (t:ℂ) * (mu + Df j))‖ < a / 11) :
    ∃ b ∈ row_44, ∃ U V : ℝ, 0 ≤ U ∧ U ≤ 1 ∧ 0 ≤ V ∧ V ≤ 1 ∧
      Sendov911Capstone.Box.poly b U V ≤ 0 := by
  have ha0 : (0:ℝ) < a := by linarith
  have ha1 : a ≤ 1 := by linarith
  have hsig : sig ≤ (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) := by
    rw [hsigeq]
    exact Rows11.sigma_row_44 rr hrlo (fun k => le_trans (hrhi k) (by linarith)) hprod
  have hL := Rows11.L_row_44 h0 h1
  have hc := CTab11.cTable11 Df eta heta0 hz hD2
  have hloc' : ((10:ℕ):ℝ) ≤ ((10:ℕ):ℝ) * a * mu.re + (1 - a ^ 2) * sig := by
    push_cast
    exact hloc
  have hkey := MidChainN.key_of_loc ha1 ha0.le hloc' hsig
  have hL' : 0 ≤ (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) * a ^ 2 - ((10:ℕ):ℝ) * (1623/2000 : ℝ) * a + ((10:ℕ):ℝ) - (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ) := by
    push_cast
    exact hL
  have hlamu := MidChainN.lam_le_u (by norm_num) ha0 hkey hL'
  have hmunorm := MidChainN.lam_le_norm mu hlamu
  have hetale := MidChainN.eta_sq_le mu (by norm_num) hnormSq hmunorm
  have hetaY : eta ≤ (14609/25000 : ℝ) :=
    MidChainN.eta_le_Y (by norm_num) heta0 hetale Rows11.Y_row_44
  obtain ⟨j, hj, hja, hjb⟩ := Cover.cover_grid (by norm_num : (0:ℝ) < (14609/250000 : ℝ)) 0 10
    (by norm_num) eta heta0 (by push_cast; linarith)
  interval_cases j
  · -- strip j = 0, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_0, mem_44_0, 100 * (a - (11/25 : ℝ)), (eta - (0 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_0 (100 * (a - (11/25 : ℝ))) ((eta - (0 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (0 : ℝ) + (14609/250000 : ℝ) * ((eta - (0 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 1, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_1, mem_44_1, 100 * (a - (11/25 : ℝ)), (eta - (14609/250000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_1 (100 * (a - (11/25 : ℝ))) ((eta - (14609/250000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (14609/250000 : ℝ) + (14609/250000 : ℝ) * ((eta - (14609/250000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 2, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_2, mem_44_2, 100 * (a - (11/25 : ℝ)), (eta - (14609/125000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_2 (100 * (a - (11/25 : ℝ))) ((eta - (14609/125000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (14609/125000 : ℝ) + (14609/250000 : ℝ) * ((eta - (14609/125000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 3, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_3, mem_44_3, 100 * (a - (11/25 : ℝ)), (eta - (43827/250000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_3 (100 * (a - (11/25 : ℝ))) ((eta - (43827/250000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (43827/250000 : ℝ) + (14609/250000 : ℝ) * ((eta - (43827/250000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 4, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_4, mem_44_4, 100 * (a - (11/25 : ℝ)), (eta - (14609/62500 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_4 (100 * (a - (11/25 : ℝ))) ((eta - (14609/62500 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (14609/62500 : ℝ) + (14609/250000 : ℝ) * ((eta - (14609/62500 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 5, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_5, mem_44_5, 100 * (a - (11/25 : ℝ)), (eta - (14609/50000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_5 (100 * (a - (11/25 : ℝ))) ((eta - (14609/50000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (14609/50000 : ℝ) + (14609/250000 : ℝ) * ((eta - (14609/50000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 6, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_6, mem_44_6, 100 * (a - (11/25 : ℝ)), (eta - (43827/125000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_6 (100 * (a - (11/25 : ℝ))) ((eta - (43827/125000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (43827/125000 : ℝ) + (14609/250000 : ℝ) * ((eta - (43827/125000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 7, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_7, mem_44_7, 100 * (a - (11/25 : ℝ)), (eta - (102263/250000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_7 (100 * (a - (11/25 : ℝ))) ((eta - (102263/250000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (102263/250000 : ℝ) + (14609/250000 : ℝ) * ((eta - (102263/250000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 8, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_8, mem_44_8, 100 * (a - (11/25 : ℝ)), (eta - (14609/31250 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_8 (100 * (a - (11/25 : ℝ))) ((eta - (14609/31250 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (14609/31250 : ℝ) + (14609/250000 : ℝ) * ((eta - (14609/31250 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP
  · -- strip j = 9, τ = 1
    push_cast at hja hjb
    have hP := Split11.split_row_nonpos (alpha := (11/25 : ℝ)) (beta := (9/20 : ℝ))
      (S := (168267187730202318381949471143517965721/21138690807562240000000000000000000000 : ℝ)) (lam := (1623/2000 : ℝ)) (sigma := sig) (tau := (1 : ℝ)) CTab11.c11
      (fun m _ => CTab11.c11_nonneg m) mu Df a eta
      (by norm_num) (by norm_num) (by norm_num) Rows11.lam_row_44
      (by norm_num) (by norm_num) h0 h1 heta0 hnormSq hloc hsig hL hz hY1 hc hI
    refine ⟨box_44_9, mem_44_9, 100 * (a - (11/25 : ℝ)), (eta - (131481/250000 : ℝ)) / (14609/250000 : ℝ),
      by linarith, by linarith, div_nonneg (by linarith) (by norm_num),
      (div_le_one (by norm_num)).mpr (by linarith), ?_⟩
    have heq := eq_44_9 (100 * (a - (11/25 : ℝ))) ((eta - (131481/250000 : ℝ)) / (14609/250000 : ℝ))
    rw [show (11/25 : ℝ) + (1/100) * (100 * (a - (11/25 : ℝ))) = a by ring] at heq
    rw [show (131481/250000 : ℝ) + (14609/250000 : ℝ) * ((eta - (131481/250000 : ℝ)) / (14609/250000 : ℝ)) = eta by field_simp <;> ring] at heq
    exact le_of_eq_of_le heq.symm hP

end SendovN.Red11_44

#print axioms SendovN.Red11_44.Peq_44_t0
#print axioms SendovN.Red11_44.eq_44_0
#print axioms SendovN.Red11_44.eq_44_1
#print axioms SendovN.Red11_44.eq_44_2
#print axioms SendovN.Red11_44.eq_44_3
#print axioms SendovN.Red11_44.eq_44_4
#print axioms SendovN.Red11_44.eq_44_5
#print axioms SendovN.Red11_44.eq_44_6
#print axioms SendovN.Red11_44.eq_44_7
#print axioms SendovN.Red11_44.eq_44_8
#print axioms SendovN.Red11_44.eq_44_9
#print axioms SendovN.Red11_44.rowPos_44
#print axioms SendovN.Red11_44.red_44
