#!/usr/bin/env python3
"""P10 emitter: closed forms  int_{t0}^{t1} v^m (1 + Q1 v + Q2 v^2)^ell dv
as polynomial identities in (t0, t1, Q1, Q2), emitted to SendovNEInt.lean.

Exact rational arithmetic only (fractions).  The (m, ell) pairs are the ones the
degree-10/11 majorants need (ell_m = (N-m)//2 at N = 9 and N = 10), plus (0, 5)
for the degree-11 tau-split tail  a * int_tau^1 (q0^5 + q1^5) dv.

Stating the identities with BOTH limits free subsumes the whole TAU_MENU: the
head integrals are (t0,t1) = (0,tau), the tails are (tau,1), and the plain
majorant integrals are (0,1) -- no per-tau file generation is needed.

Every identity was verified at random rational points before emission (below).
"""
from fractions import Fraction as F
from math import comb, factorial
import random

# (m, ell) pairs: N=9 (deg 10), N=10 (deg 11), and the tau-split tail (0,5)
PAIRS10 = [(m, (9 - m) // 2) for m in range(2, 10)]
PAIRS11 = [(m, (10 - m) // 2) for m in range(2, 11)]
PAIRS = sorted(set(PAIRS10) | set(PAIRS11) | {(0, 5)})

MAXDEG = 10  # max of m + 2*ell over all pairs
assert all(m + 2 * l <= MAXDEG for m, l in PAIRS)


def trinomial_coeffs(l):
    """dict (p,q) -> multinomial coefficient of Q1^p Q2^q in (1+Q1 v+Q2 v^2)^l,
    sitting at v-degree p+2q."""
    out = {}
    for p in range(l + 1):
        for q in range(l - p + 1):
            out[(p, q)] = factorial(l) // (factorial(p) * factorial(q) * factorial(l - p - q))
    return out


def q1q2(p, q):
    fs = []
    if p == 1:
        fs.append("Q1")
    elif p > 1:
        fs.append(f"Q1 ^ {p}")
    if q == 1:
        fs.append("Q2")
    elif q > 1:
        fs.append(f"Q2 ^ {q}")
    return fs


def rat(fr):
    fr = F(fr)
    if fr.denominator == 1:
        return f"({fr.numerator} : ℝ)"
    return f"({fr.numerator}/{fr.denominator} : ℝ)"


def vec_entries(m, l):
    """Fin (MAXDEG+1) coefficient vector of v^m (1+Q1 v+Q2 v^2)^l."""
    tri = trinomial_coeffs(l)
    ent = [[] for _ in range(MAXDEG + 1)]
    for (p, q), c in sorted(tri.items(), key=lambda kv: (kv[0][0] + 2 * kv[0][1], kv[0])):
        deg = m + p + 2 * q
        term = " * ".join([rat(c)] + q1q2(p, q)) if (p or q) else rat(c)
        ent[deg].append(term)
    return ["0" if not e else " + ".join(e) for e in ent]


def rhs_terms(m, l):
    tri = trinomial_coeffs(l)
    terms = []
    for (p, q), c in sorted(tri.items(), key=lambda kv: (kv[0][0] + 2 * kv[0][1], kv[0])):
        d = m + p + 2 * q + 1
        fs = [rat(F(c, d))] + q1q2(p, q) + [f"(t1 ^ {d} - t0 ^ {d})"]
        terms.append(" * ".join(fs))
    return terms


def sanity(m, l, trials=20):
    """Check the identity at random rationals against direct exact integration."""
    tri = trinomial_coeffs(l)
    rng = random.Random(20260806 + 100 * m + l)
    for _ in range(trials):
        t0 = F(rng.randint(-9, 9), rng.randint(1, 9))
        t1 = F(rng.randint(-9, 9), rng.randint(1, 9))
        Q1 = F(rng.randint(-9, 9), rng.randint(1, 9))
        Q2 = F(rng.randint(-9, 9), rng.randint(1, 9))
        # direct: integrate monomial-by-monomial
        direct = F(0)
        for (p, q), c in tri.items():
            d = m + p + 2 * q + 1
            direct += F(c, d) * Q1 ** p * Q2 ** q * (t1 ** d - t0 ** d)
        # re-evaluate the emitted RHS structure (same formula; guards emission bugs)
        rhs = sum(F(c, m + p + 2 * q + 1) * Q1 ** p * Q2 ** q *
                  (t1 ** (m + p + 2 * q + 1) - t0 ** (m + p + 2 * q + 1))
                  for (p, q), c in tri.items())
        # and the vector route: sum_i ent_i * (t1^(i+1)-t0^(i+1))/(i+1)
        vec = [F(0)] * (MAXDEG + 1)
        for (p, q), c in tri.items():
            vec[m + p + 2 * q] += F(c) * Q1 ** p * Q2 ** q
        vroute = sum(vec[i] * (t1 ** (i + 1) - t0 ** (i + 1)) / F(i + 1)
                     for i in range(MAXDEG + 1))
        assert direct == rhs == vroute, (m, l, t0, t1, Q1, Q2)


HEADER = f"""import Mathlib

set_option maxHeartbeats 4000000

/-!
# P10: the `E`-majorant closed forms for degrees 10 and 11

Generated by `emit_eint1011.py`; do not hand-edit.  Exact-rational generation,
identities re-verified at random rational points before emission.

Closed forms `∫_(t0)^(t1) v^m (1 + Q1 v + Q2 v²)^ℓ dv` for the (m,ℓ) pairs of the
degree-10 majorant (`ℓ = ⌊(9−m)/2⌋`, m = 2…9), the degree-11 majorant
(`ℓ = ⌊(10−m)/2⌋`, m = 2…10), and the degree-11 τ-split tail `(m,ℓ) = (0,5)`
(both `q₀⁵` and `q₁⁵` tails are this shape).  Stating them with BOTH limits free
subsumes the whole `TAU_MENU`: heads are `(0,τ)`, tails `(τ,1)`, plain majorant
integrals `(0,1)` — no per-τ generation is needed anywhere downstream.

All integrands have degree `m + 2ℓ ≤ {MAXDEG}`, so the single vector lemma
`integral_vec` (a `Fin {MAXDEG + 1}` coefficient vector) discharges every pair.
-/

namespace SendovN.EInt

open Finset intervalIntegral

/-- `∫_(t0)^(t1) ∑ᵢ cᵢ vⁱ dv = ∑ᵢ cᵢ (t1^(i+1) − t0^(i+1))/(i+1)`, for a degree-{MAXDEG}
coefficient vector — the one lemma behind every closed form below. -/
theorem integral_vec (t0 t1 : ℝ) (c : Fin {MAXDEG + 1} → ℝ) :
    (∫ v in t0..t1, ∑ i : Fin {MAXDEG + 1}, c i * v ^ (i : ℕ))
      = ∑ i : Fin {MAXDEG + 1}, c i * ((t1 ^ ((i : ℕ) + 1) - t0 ^ ((i : ℕ) + 1)) / ((i : ℕ) + 1)) := by
  rw [intervalIntegral.integral_finsetSum]
  · refine Finset.sum_congr rfl fun i _ => ?_
    rw [intervalIntegral.integral_const_mul, integral_pow]
  · intro i _
    exact (by fun_prop :
      Continuous fun v : ℝ => c i * v ^ (i : ℕ)).intervalIntegrable _ _
"""

FOOTER_NAME = "SendovN.EInt"


def emit():
    parts = [HEADER]
    names = ["integral_vec"]
    for m, l in PAIRS:
        sanity(m, l)
        name = f"int_{m}_{l}"
        names.append(name)
        ent = vec_entries(m, l)
        vec = "![" + ", ".join(ent) + "]"
        rhs = "\n      + ".join(rhs_terms(m, l))
        who = []
        if (m, l) in PAIRS10:
            who.append("deg 10")
        if (m, l) in PAIRS11:
            who.append("deg 11")
        if (m, l) == (0, 5):
            who.append("deg-11 τ-tail")
        parts.append(f"""
/-- `∫_(t0)^(t1) v^{m} (1 + Q1 v + Q2 v²)^{l} dv` ({", ".join(who)}). -/
theorem {name} (t0 t1 Q1 Q2 : ℝ) :
    (∫ v in t0..t1, v ^ {m} * (1 + Q1 * v + Q2 * v ^ 2) ^ {l})
      = {rhs} := by
  have hexp : ∀ v : ℝ, v ^ {m} * (1 + Q1 * v + Q2 * v ^ 2) ^ {l}
      = ∑ i : Fin {MAXDEG + 1}, ({vec} : Fin {MAXDEG + 1} → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_vec]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring
""")
    parts.append(f"\nend {FOOTER_NAME}\n\n")
    for nm in names:
        parts.append(f"#print axioms {FOOTER_NAME}.{nm}\n")
    return "".join(parts)


if __name__ == "__main__":
    src = emit()
    out = "SendovNEInt.lean"
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)
    print("pairs:", PAIRS)
    print("wrote", out, len(src), "chars")
