/-
Copyright (c) 2026 PrincipiaAI. Released under Apache 2.0.
-/
import Principia.Common.TernaryGoldbach.RegW
import Principia.Common.TernaryGoldbach.EasyThird
import Principia.Common.TernaryGoldbach.EasyStar
import Principia.Common.TernaryGoldbach.EasySup
import Principia.Common.TernaryGoldbach.MinorSpine

set_option autoImplicit false

/-!
# `RegW`, `OstopHyp` and `PhiL1` on Helfgott's own weights — DISCHARGED

Three links of the integrated EP1054 chain are elementary facts about FIXED functions. Each was
checked numerically first (`scratchpad/integ/integ_numbers.py`), at both asymptotic ends:

* **`regW_helf : RW.RegW η₊ η* η∘`** — `η₊, η* ∈ L¹ ∩ L²`, `η∘` is `C³` off `{0, 2}`,
  `η∘''' ∈ L¹`, `η∘ ∈ L²`.
  - `η₊` is MEASURABLE because `h_H` is a parametric Lebesgue integral of a jointly measurable
    integrand (`measurable_hH`, Mathlib's `StronglyMeasurable.integral_prod_right`); then
    `|η₊| ≤ |η∘| + 0.13·te^{−t²/2}` (`abs_etaPlus_le`, from `BL.band_uniform`) dominates it in
    `L¹`, and `η₊² ≤ 2η∘² + 2·0.13²·t²e^{−t²}` in `L²`.
  - `η*`: `∫η* = √(π/2)/49 ≠ 0` (`EN.int_etaStar`) forces integrability, and `0 ≤ η* ≤ 1.414`
    gives `η*² ≤ 1.414η*`.
  - `η∘`: `C³` on `(0,2)` (it is `G₀(t−1)` there, `EN.etaCirc_ev`) and on `(2,∞)` (it is `0`);
    `|η∘'''| ≤ g₃` a.e. (`EN.third_eq`, `EN.G3_le`) with `g₃` integrable, and `η∘'''` measurable
    because every `deriv` is (`measurable_deriv`).
* **`ostopHyp_helf_full : MinSp.OstopHyp η₊ η* φ`** — the two facts `MinSp.ostopHyp_helf` left:
  - `η₊` is differentiable at every `t > 0` (`diffAt_etaPlus`): `h_H' (t)` is the integral
    of `h'(t/y)F_H(y)/y²`, by differentiation under the integral sign
    (`hasDerivAt_integral_of_dominated_loc_of_deriv_le`) with the majorant
    `M·(200/π)·y⁻²·1_{y > t₀/4}` — `h'` is bounded and vanishes once `t/y > 2`;
  - `η₊(t) → 0` (`tendsto_etaPlus`): past `2`, `|η₊| ≤ 0.13·te^{−t²/2} ≤ 0.13/t`.
* **`phiL1_helf : MinSp.PhiL1 φ`** — `φ ≥ 0` and `∫φ = √(π/2)` (`EN.int_phi`).

Two proofs are GENERATED by counted substitution from verified ones
(`scratchpad/integ/assemble_regwhelf.py`): `abs_etaPlus_le` is the `hpt` step of
`EN.l1_etaPlus_le`, and `third_ae_le` the `hne`/`hpt` steps of `EN.l1_third_le`.
-/

namespace Principia.Common.TernaryGoldbach.RW

open MeasureTheory Set Filter Metric
open scoped Topology

/-! ## `η₊`: measurable, and in `L¹ ∩ L²` -/

/-- **`h_H` is measurable**: `h_H(t) = ∫_0^∞ h(t/y)F_H(y)dy/y` is a parametric integral of a jointly
measurable integrand. -/
theorem measurable_hH (H : ℝ) : Measurable (HW.hH H) := by
  have hj : Measurable fun p : ℝ × ℝ => HW.hFun (p.1 / p.2) * HW.FH H p.2 / p.2 :=
    ((HW.measurable_hFun.comp (measurable_fst.div measurable_snd)).mul
      ((HW.measurable_FH H).comp measurable_snd)).div measurable_snd
  have hm : StronglyMeasurable
      (Function.uncurry fun t y : ℝ => HW.hFun (t / y) * HW.FH H y / y) :=
    hj.stronglyMeasurable
  exact (hm.integral_prod_right (ν := volume.restrict (Ioi (0 : ℝ)))).measurable

/-- `η₊` is measurable. -/
theorem measurable_etaPlus : Measurable HW.etaPlus :=
  ((measurable_hH 200).mul measurable_id).mul
    (by fun_prop : Continuous fun t : ℝ => Real.exp (-t ^ 2 / 2)).measurable

/-- **`|η₊| ≤ |η∘| + 0.13·te^{−t²/2}` on `t > 0`**, from `BL.band_uniform` (GENERATED: the
`hpt` step of `EN.l1_etaPlus_le`). -/
theorem abs_etaPlus_le (t : ℝ) (ht : t ∈ Ioi (0 : ℝ)) :
    |HW.etaPlus t| ≤ |HW.etaCirc t| + 0.13 * (t * Real.exp (-t ^ 2 / 2)) := by
  have ht0 : (0 : ℝ) ≤ t * Real.exp (-t ^ 2 / 2) := mul_nonneg (le_of_lt ht) (Real.exp_pos _).le
  have hsplit : HW.etaPlus t =
      HW.etaCirc t + (HW.hH 200 t - HW.hFun t) * (t * Real.exp (-t ^ 2 / 2)) := by
    rw [HW.etaPlus, HW.etaCirc]
    ring
  have hb := HW.band_all BL.band_uniform t
  rw [hsplit]
  calc |HW.etaCirc t + (HW.hH 200 t - HW.hFun t) * (t * Real.exp (-t ^ 2 / 2))|
      ≤ |HW.etaCirc t| + |HW.hH 200 t - HW.hFun t| * (t * Real.exp (-t ^ 2 / 2)) := by
        rw [← abs_of_nonneg ht0, ← abs_mul, abs_of_nonneg ht0]
        exact abs_add_le _ _
    _ ≤ |HW.etaCirc t| + 0.13 * (t * Real.exp (-t ^ 2 / 2)) :=
        add_le_add_right (mul_le_mul_of_nonneg_right hb ht0) _

/-- **`η₊ ∈ L¹(0,∞)`**. -/
theorem integrable_etaPlus : Integrable HW.etaPlus (volume.restrict (Ioi 0)) := by
  have hA : Integrable (fun t => |HW.etaCirc t|) (volume.restrict (Ioi 0)) :=
    EN.integrableOn_of_cont _ EN.continuous_etaCirc.abs fun t ht => by
      rw [EN.etaCirc_of_two_lt ht, abs_zero]
  refine (hA.add (EN.integrable_t_exp.const_mul 0.13)).mono'
    measurable_etaPlus.aestronglyMeasurable
    (ae_restrict_of_forall_mem measurableSet_Ioi fun t ht => ?_)
  rw [Real.norm_eq_abs]
  exact abs_etaPlus_le t ht

/-- **`η₊ ∈ L²(0,∞)`**: `η₊² ≤ 2η∘² + 2·0.13²·t²e^{−t²}`. -/
theorem memLp_etaPlus_two : MemLp HW.etaPlus 2 (volume.restrict (Ioi 0)) := by
  refine (memLp_two_iff_integrable_sq measurable_etaPlus.aestronglyMeasurable).mpr ?_
  have hA : Integrable (fun t => HW.etaCirc t ^ 2) (volume.restrict (Ioi 0)) :=
    EN.integrableOn_of_cont _ (EN.continuous_etaCirc.pow 2) fun t ht => by
      rw [EN.etaCirc_of_two_lt ht]
      ring
  refine ((hA.const_mul 2).add (EN.integrable_t2_exp.const_mul (2 * 0.13 ^ 2))).mono'
    (measurable_etaPlus.pow_const 2).aestronglyMeasurable
    (ae_restrict_of_forall_mem measurableSet_Ioi fun t ht => ?_)
  change ‖HW.etaPlus t ^ 2‖ ≤ 2 * HW.etaCirc t ^ 2 + 2 * 0.13 ^ 2 * (t ^ 2 * Real.exp (-t ^ 2))
  have h := abs_etaPlus_le t ht
  have e2 : (t * Real.exp (-t ^ 2 / 2)) ^ 2 = t ^ 2 * Real.exp (-t ^ 2) := by
    rw [mul_pow, sq (Real.exp _), ← Real.exp_add]
    congr 2
    ring
  rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _)]
  have hsq : HW.etaPlus t ^ 2 ≤ (|HW.etaCirc t| + 0.13 * (t * Real.exp (-t ^ 2 / 2))) ^ 2 := by
    rw [← sq_abs (HW.etaPlus t)]
    exact pow_le_pow_left₀ (abs_nonneg _) h 2
  have hab : (|HW.etaCirc t| + 0.13 * (t * Real.exp (-t ^ 2 / 2))) ^ 2 ≤
      2 * |HW.etaCirc t| ^ 2 + 2 * 0.13 ^ 2 * (t * Real.exp (-t ^ 2 / 2)) ^ 2 := by
    nlinarith [sq_nonneg (|HW.etaCirc t| - 0.13 * (t * Real.exp (-t ^ 2 / 2)))]
  rw [sq_abs, e2] at hab
  linarith

/-! ## `η*` and `η∘` -/

/-- **`η* ∈ L¹(0,∞)`**: its integral is `√(π/2)/49 ≠ 0`. -/
theorem integrable_etaStar : Integrable HW.etaStar (volume.restrict (Ioi 0)) :=
  Integrable.of_integral_ne_zero (by rw [EN.int_etaStar]; positivity)

/-- **`η* ∈ L²(0,∞)`**: `0 ≤ η* ≤ 1.414` gives `η*² ≤ 1.414·η*`. -/
theorem memLp_etaStar_two : MemLp HW.etaStar 2 (volume.restrict (Ioi 0)) := by
  refine (memLp_two_iff_integrable_sq integrable_etaStar.aestronglyMeasurable).mpr ?_
  refine (integrable_etaStar.const_mul 1.414).mono'
    (integrable_etaStar.aestronglyMeasurable.pow 2)
    (ae_restrict_of_forall_mem measurableSet_Ioi fun t ht => ?_)
  obtain ⟨h0, h1⟩ := EN.etaStar_mem (le_of_lt ht)
  change ‖HW.etaStar t ^ 2‖ ≤ 1.414 * HW.etaStar t
  rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _)]
  nlinarith

/-- **`η∘` is `C³` at every `t ≥ 0` except `0` and `2`**: it is `G₀(t − 1)` near each point of
`(0, 2)` and `0` near each point of `(2, ∞)`. -/
theorem contDiffAt_etaCirc {t : ℝ} (ht : 0 ≤ t) (hS : t ∉ ({0, 2} : Finset ℝ)) :
    ContDiffAt ℝ 3 HW.etaCirc t := by
  simp only [Finset.mem_insert, Finset.mem_singleton, not_or] at hS
  obtain ⟨h0, h2⟩ := hS
  rcases lt_or_gt_of_ne h2 with hlt | hgt
  · have hpos : 0 < t := lt_of_le_of_ne ht (Ne.symm h0)
    have hc : ContDiff ℝ 3 (fun z : ℝ => EN.G0 (z - 1)) := by
      unfold EN.G0 EN.P0
      fun_prop
    exact hc.contDiffAt.congr_of_eventuallyEq (EN.etaCirc_ev hpos hlt)
  · have hev : HW.etaCirc =ᶠ[𝓝 t] fun _ => (0 : ℝ) := by
      filter_upwards [Ioi_mem_nhds hgt] with z hz
      exact EN.etaCirc_of_two_lt hz
    exact contDiffAt_const.congr_of_eventuallyEq hev

/-- **`|η∘'''| ≤ g₃` a.e. on `(0, ∞)`** (off the null point `2`; GENERATED: the `hne`/`hpt`
steps of `EN.l1_third_le`). -/
theorem third_ae_le :
    ∀ᵐ t ∂(volume.restrict (Ioi (0 : ℝ))), |iteratedDeriv 3 HW.etaCirc t| ≤ EN.g3 t := by
  have hne : ∀ᵐ t ∂(volume : Measure ℝ), t ∉ ({2} : Set ℝ) :=
    measure_eq_zero_iff_ae_notMem.mp Real.volume_singleton
  filter_upwards [ae_restrict_mem measurableSet_Ioi, ae_restrict_of_ae hne] with t ht1 ht2
  have ht1' : 0 < t := ht1
  have ht2' : t ≠ 2 := ht2
  rcases lt_or_gt_of_ne ht2' with hlt | hgt
  · rw [EN.third_eq ht1' hlt, EN.g3, if_pos hlt.le]
    exact EN.G3_le ⟨by linarith, by linarith⟩
  · rw [EN.third_zero hgt, EN.g3, if_neg (not_le.mpr hgt)]
    simp

/-- **`η∘''' ∈ L¹(0,∞)`**: measurable (an iterated `deriv`) and dominated by `g₃`. -/
theorem integrable_third : Integrable (iteratedDeriv 3 HW.etaCirc) (volume.restrict (Ioi 0)) := by
  have hmeas : Measurable (iteratedDeriv 3 HW.etaCirc) := by
    change Measurable (iteratedDeriv (2 + 1) HW.etaCirc)
    rw [iteratedDeriv_succ]
    exact measurable_deriv _
  refine EN.integrable_g3.mono' hmeas.aestronglyMeasurable (third_ae_le.mono fun t h => ?_)
  rw [Real.norm_eq_abs]
  exact h

/-- **`η∘ ∈ L²(0,∞)`**: continuous, vanishing past `2`. -/
theorem memLp_etaCirc_two : MemLp HW.etaCirc 2 (volume.restrict (Ioi 0)) := by
  refine (memLp_two_iff_integrable_sq
    EN.continuous_etaCirc.measurable.aestronglyMeasurable).mpr ?_
  exact EN.integrableOn_of_cont _ (EN.continuous_etaCirc.pow 2) fun t ht => by
    rw [EN.etaCirc_of_two_lt ht]
    ring

/-- **`RegW` on Helfgott's own weights, DISCHARGED**. -/
theorem regW_helf : RegW HW.etaPlus HW.etaStar HW.etaCirc :=
  ⟨memLp_one_iff_integrable.mpr integrable_etaPlus, memLp_etaPlus_two,
    memLp_one_iff_integrable.mpr integrable_etaStar, memLp_etaStar_two,
    ⟨{0, 2}, fun _ ht hS => contDiffAt_etaCirc ht hS⟩, integrable_third, memLp_etaCirc_two⟩

/-! ## `OstopHyp`: `η₊` differentiable on `(0, ∞)` and `η₊ → 0` -/

/-- `|h'|` is bounded (`h' = hDP ∘ clamp`, `hDP` continuous on `[0, 2]`). -/
theorem hD_bdd : ∃ M : ℝ, 0 ≤ M ∧ ∀ v : ℝ, |BL.hD v| ≤ M := by
  have hc : Continuous BL.hDP := by
    unfold BL.hDP
    fun_prop
  obtain ⟨M, hM⟩ := (isCompact_Icc (a := (0 : ℝ)) (b := 2)).exists_bound_of_continuousOn
    hc.continuousOn
  refine ⟨max M 0, le_max_right _ _, fun v => ?_⟩
  rw [BL.hD_clamp]
  have hmem : max 0 (min v 2) ∈ Icc (0 : ℝ) 2 :=
    ⟨le_max_left _ _, max_le (by norm_num) (min_le_right _ _)⟩
  have h := hM _ hmem
  rw [Real.norm_eq_abs] at h
  exact h.trans (le_max_left _ _)

/-- **`h_H` is differentiable at every `t₀ > 0`**, with derivative `∫ h'(t₀/y)(1/y)F_H(y)/y dy`
(differentiation under the integral sign; majorant `M(200/π)y⁻²` on `y > t₀/4`, `0` below, since
`h'(t/y) = 0` once `t/y > 2`). -/
theorem hasDerivAt_hH {t₀ : ℝ} (ht₀ : 0 < t₀) :
    HasDerivAt (HW.hH 200)
      (∫ y in Ioi (0 : ℝ), BL.hD (t₀ / y) * (1 / y) * HW.FH 200 y / y) t₀ := by
  obtain ⟨M, hM0, hM⟩ := hD_bdd
  have hq : 0 < t₀ / 4 := by positivity
  have hbint : IntegrableOn (fun y : ℝ => M * (200 / Real.pi) * y ^ (-2 : ℝ)) (Ioi (t₀ / 4)) :=
    (integrableOn_Ioi_rpow_of_lt (by norm_num) hq).const_mul _
  have key := hasDerivAt_integral_of_dominated_loc_of_deriv_le
    (μ := volume.restrict (Ioi (0 : ℝ)))
    (F := fun t y => HW.hFun (t / y) * HW.FH 200 y / y)
    (F' := fun t y => BL.hD (t / y) * (1 / y) * HW.FH 200 y / y)
    (bound := Set.indicator (Ioi (t₀ / 4)) fun y => M * (200 / Real.pi) * y ^ (-2 : ℝ))
    (x₀ := t₀) (ball_mem_nhds t₀ (by positivity : 0 < t₀ / 2))
    (Eventually.of_forall fun t => (((HW.measurable_hFun.comp
      (measurable_const.div measurable_id)).mul (HW.measurable_FH 200)).div
        measurable_id).aestronglyMeasurable)
    (HW.hH_integrable (by norm_num) ht₀)
    ((((BL.continuous_hD.measurable.comp (measurable_const.div measurable_id)).mul
      (measurable_const.div measurable_id)).mul (HW.measurable_FH 200)).div
        measurable_id).aestronglyMeasurable
    ?_ (((integrable_indicator_iff measurableSet_Ioi).mpr hbint).mono_measure
      Measure.restrict_le_self) ?_
  · exact key.2
  · refine ae_restrict_of_forall_mem measurableSet_Ioi fun y hy t ht => ?_
    have hy0 : (0 : ℝ) < y := hy
    rw [mem_ball, Real.dist_eq] at ht
    have htl : t₀ / 2 < t := by linarith [(abs_lt.mp ht).1]
    have hF := HW.abs_FH_le (by norm_num : (0 : ℝ) ≤ 200) y
    by_cases hyq : t₀ / 4 < y
    · rw [indicator_of_mem (show y ∈ Ioi (t₀ / 4) from hyq)]
      change ‖BL.hD (t / y) * (1 / y) * HW.FH 200 y / y‖ ≤ M * (200 / Real.pi) * y ^ (-2 : ℝ)
      have hyr : y ^ (-2 : ℝ) = 1 / y * (1 / y) := by
        rw [show (-2 : ℝ) = -((2 : ℕ) : ℝ) by norm_num, Real.rpow_neg hy0.le, Real.rpow_natCast]
        field_simp
      rw [hyr, Real.norm_eq_abs]
      have e : BL.hD (t / y) * (1 / y) * HW.FH 200 y / y =
          BL.hD (t / y) * HW.FH 200 y * (1 / y * (1 / y)) := by
        field_simp
      rw [e, abs_mul, abs_mul, abs_of_nonneg (by positivity : (0 : ℝ) ≤ 1 / y * (1 / y))]
      have h1 := hM (t / y)
      have hab : |BL.hD (t / y)| * |HW.FH 200 y| ≤ M * (200 / Real.pi) :=
        mul_le_mul h1 hF (abs_nonneg _) hM0
      exact mul_le_mul_of_nonneg_right hab (by positivity)
    · rw [indicator_of_notMem (show y ∉ Ioi (t₀ / 4) from hyq)]
      have hyle : y ≤ t₀ / 4 := not_lt.mp hyq
      have h2 : 2 < t / y := by
        rw [lt_div_iff₀ hy0]
        linarith
      have hz : BL.hD (t / y) = 0 := if_neg fun h => absurd h.2 (not_le.mpr h2)
      rw [hz]
      simp
  · refine ae_restrict_of_forall_mem measurableSet_Ioi fun y _ t _ => ?_
    have h1 : HasDerivAt (fun s : ℝ => s / y) (1 / y) t := (hasDerivAt_id t).div_const y
    exact (((BL.hasDerivAt_hFun (t / y)).comp t h1).mul_const (HW.FH 200 y)).div_const y

/-- **`η₊` is differentiable at every `t > 0`.** -/
theorem diffAt_etaPlus {t : ℝ} (ht : 0 < t) : DifferentiableAt ℝ HW.etaPlus t := by
  have h1 : DifferentiableAt ℝ (HW.hH 200) t := (hasDerivAt_hH ht).differentiableAt
  have h2 : DifferentiableAt ℝ (fun s : ℝ => Real.exp (-s ^ 2 / 2)) t := by fun_prop
  exact (h1.mul differentiableAt_id).mul h2

/-- **`η₊(t) → 0` as `t → ∞`**: for `t > 2`, `|η₊(t)| ≤ 0.13·te^{−t²/2} ≤ 0.13/t`
(`t² ≤ e^{t²/2}`). -/
theorem tendsto_etaPlus : Tendsto HW.etaPlus atTop (𝓝 0) := by
  have hlim : Tendsto (fun t : ℝ => 0.13 * t⁻¹) atTop (𝓝 0) := by
    have h := tendsto_inv_atTop_zero.const_mul (0.13 : ℝ)
    rwa [mul_zero] at h
  refine squeeze_zero_norm' ?_ hlim
  filter_upwards [eventually_gt_atTop (2 : ℝ)] with t ht
  have ht0 : 0 < t := by linarith
  have h := abs_etaPlus_le t ht0
  rw [EN.etaCirc_of_two_lt ht, abs_zero, zero_add] at h
  have hq := Real.quadratic_le_exp_of_nonneg (by positivity : (0 : ℝ) ≤ t ^ 2 / 2)
  have hsq : t ^ 2 ≤ Real.exp (t ^ 2 / 2) := by nlinarith [sq_nonneg (t ^ 2 / 2 - 1)]
  have hE : t * Real.exp (-t ^ 2 / 2) = t / Real.exp (t ^ 2 / 2) := by
    rw [show -t ^ 2 / 2 = -(t ^ 2 / 2) by ring, Real.exp_neg, ← div_eq_mul_inv]
  have hw : t * Real.exp (-t ^ 2 / 2) ≤ t⁻¹ := by
    rw [hE]
    calc t / Real.exp (t ^ 2 / 2) ≤ t / t ^ 2 :=
          div_le_div_of_nonneg_left ht0.le (by positivity) hsq
      _ = t⁻¹ := by field_simp
  rw [Real.norm_eq_abs]
  linarith

/-- **`OstopHyp` on Helfgott's weights, DISCHARGED**: `MinSp.ostopHyp_helf` with `BL.band_uniform`
and the two facts above (`S = {0}`). -/
theorem ostopHyp_helf_full : MinSp.OstopHyp HW.etaPlus HW.etaStar HW.phi :=
  MinSp.ostopHyp_helf BL.band_uniform
    ⟨{0}, fun _ ht h0 => diffAt_etaPlus (lt_of_le_of_ne ht
      (Ne.symm (by simpa using h0)))⟩ tendsto_etaPlus

/-! ## `PhiL1` -/

/-- **`|φ|₁ = √(π/2)` for `φ = t²e^{−t²/2}`, DISCHARGED** (`φ ≥ 0`, `EN.int_phi`). -/
theorem phiL1_helf : MinSp.PhiL1 HW.phi := by
  unfold MinSp.PhiL1 MajSp.l1
  rw [← EN.int_phi]
  exact setIntegral_congr_fun measurableSet_Ioi fun t _ => abs_of_nonneg (HW.phi_nonneg t)

end Principia.Common.TernaryGoldbach.RW
