import Mathlib

set_option maxHeartbeats 4000000

namespace Sendov9.EIntW

open Finset intervalIntegral

/-!
# The seven closed forms, with a variable upper limit

Generated by `emit_eintw.py`; do not hand-edit.

The boundary range `9/10 ≤ a < 1` integrates the SAME integrand as the middle range,
`tᵐ(1 + Q1 t + Q2 t²)^ℓ`, but over `[0, W]` with `W = 1 - x²` instead of `[0,1]`
(equation 5.5 of the paper).  So each bracket in `Cert.bdry_pos` is the corresponding
bracket of `Cert.i<i>_pos` with every term carrying a power of `W` — because
`∫₀^W t^{2+i+2j} dt = W^{3+i+2j}/(3+i+2j)`.

`EIntegrals.lean` is the `W = 1` specialization of this file; it is kept separate
because the middle range's certificates are stated without the `W` powers, and rewriting
with `W := 1` would leave `1 ^ k` litter for `ring` to clear at eighteen use sites.

Sendov's conjecture in degree nine remains unproven.
-/

/-- `∫₀^W ∑ᵢ cᵢ tⁱ dt = ∑ᵢ cᵢ W^{i+1}/(i+1)`. -/
theorem integral_deg8W (W : ℝ) (c : Fin 9 → ℝ) :
    (∫ t in (0:ℝ)..W, ∑ i : Fin 9, c i * t ^ (i : ℕ))
      = ∑ i : Fin 9, c i * W ^ ((i : ℕ) + 1) / ((i : ℕ) + 1) := by
  rw [intervalIntegral.integral_finsetSum]
  · refine Finset.sum_congr rfl fun i _ => ?_
    rw [intervalIntegral.integral_const_mul, integral_pow]
    have h0 : (0:ℝ) ^ ((i : ℕ) + 1) = 0 := zero_pow (Nat.succ_ne_zero _)
    rw [h0]
    push_cast
    ring
  · intro i _
    exact (by fun_prop : Continuous fun t : ℝ => c i * t ^ (i : ℕ)).intervalIntegrable _ _

/-- `∫₀^W t^2 (1 + Q1 t + Q2 t²)^3 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_2_3 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 2 * (1 + Q1 * t + Q2 * t ^ 2) ^ 3)
      = (1/3 : ℝ) * W ^ 3 + (3/5 : ℝ) * Q2 * W ^ 5 + (3/7 : ℝ) * Q2 ^ 2 * W ^ 7 + (1/9 : ℝ) * Q2 ^ 3 * W ^ 9 + (3/4 : ℝ) * Q1 * W ^ 4 + (1 : ℝ) * Q1 * Q2 * W ^ 6 + (3/8 : ℝ) * Q1 * Q2 ^ 2 * W ^ 8 + (3/5 : ℝ) * Q1 ^ 2 * W ^ 5 + (3/7 : ℝ) * Q1 ^ 2 * Q2 * W ^ 7 + (1/6 : ℝ) * Q1 ^ 3 * W ^ 6 := by
  have hexp : ∀ t : ℝ, t ^ 2 * (1 + Q1 * t + Q2 * t ^ 2) ^ 3
      = ∑ i : Fin 9, (![0, 0, (1 : ℝ), (3 : ℝ) * Q1, (3 : ℝ) * Q2 + (3 : ℝ) * Q1 ^ 2, (6 : ℝ) * Q1 * Q2 + Q1 ^ 3, (3 : ℝ) * Q2 ^ 2 + (3 : ℝ) * Q1 ^ 2 * Q2, (3 : ℝ) * Q1 * Q2 ^ 2, Q2 ^ 3] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^3 (1 + Q1 t + Q2 t²)^2 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_3_2 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 3 * (1 + Q1 * t + Q2 * t ^ 2) ^ 2)
      = (1/4 : ℝ) * W ^ 4 + (1/3 : ℝ) * Q2 * W ^ 6 + (1/8 : ℝ) * Q2 ^ 2 * W ^ 8 + (2/5 : ℝ) * Q1 * W ^ 5 + (2/7 : ℝ) * Q1 * Q2 * W ^ 7 + (1/6 : ℝ) * Q1 ^ 2 * W ^ 6 := by
  have hexp : ∀ t : ℝ, t ^ 3 * (1 + Q1 * t + Q2 * t ^ 2) ^ 2
      = ∑ i : Fin 9, (![0, 0, 0, (1 : ℝ), (2 : ℝ) * Q1, (2 : ℝ) * Q2 + Q1 ^ 2, (2 : ℝ) * Q1 * Q2, Q2 ^ 2, 0] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^4 (1 + Q1 t + Q2 t²)^2 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_4_2 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 4 * (1 + Q1 * t + Q2 * t ^ 2) ^ 2)
      = (1/5 : ℝ) * W ^ 5 + (2/7 : ℝ) * Q2 * W ^ 7 + (1/9 : ℝ) * Q2 ^ 2 * W ^ 9 + (1/3 : ℝ) * Q1 * W ^ 6 + (1/4 : ℝ) * Q1 * Q2 * W ^ 8 + (1/7 : ℝ) * Q1 ^ 2 * W ^ 7 := by
  have hexp : ∀ t : ℝ, t ^ 4 * (1 + Q1 * t + Q2 * t ^ 2) ^ 2
      = ∑ i : Fin 9, (![0, 0, 0, 0, (1 : ℝ), (2 : ℝ) * Q1, (2 : ℝ) * Q2 + Q1 ^ 2, (2 : ℝ) * Q1 * Q2, Q2 ^ 2] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^5 (1 + Q1 t + Q2 t²)^1 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_5_1 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 5 * (1 + Q1 * t + Q2 * t ^ 2) ^ 1)
      = (1/6 : ℝ) * W ^ 6 + (1/8 : ℝ) * Q2 * W ^ 8 + (1/7 : ℝ) * Q1 * W ^ 7 := by
  have hexp : ∀ t : ℝ, t ^ 5 * (1 + Q1 * t + Q2 * t ^ 2) ^ 1
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, (1 : ℝ), Q1, Q2, 0] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^6 (1 + Q1 t + Q2 t²)^1 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_6_1 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 6 * (1 + Q1 * t + Q2 * t ^ 2) ^ 1)
      = (1/7 : ℝ) * W ^ 7 + (1/9 : ℝ) * Q2 * W ^ 9 + (1/8 : ℝ) * Q1 * W ^ 8 := by
  have hexp : ∀ t : ℝ, t ^ 6 * (1 + Q1 * t + Q2 * t ^ 2) ^ 1
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, (1 : ℝ), Q1, Q2] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^7 (1 + Q1 t + Q2 t²)^0 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_7_0 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 7 * (1 + Q1 * t + Q2 * t ^ 2) ^ 0)
      = (1/8 : ℝ) * W ^ 8 := by
  have hexp : ∀ t : ℝ, t ^ 7 * (1 + Q1 * t + Q2 * t ^ 2) ^ 0
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, 0, (1 : ℝ), 0] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀^W t^8 (1 + Q1 t + Q2 t²)^0 dt`, in the exact form `Cert.bdry_pos` states. -/
theorem intW_8_0 (W Q1 Q2 : ℝ) :
    (∫ t in (0:ℝ)..W, t ^ 8 * (1 + Q1 * t + Q2 * t ^ 2) ^ 0)
      = (1/9 : ℝ) * W ^ 9 := by
  have hexp : ∀ t : ℝ, t ^ 8 * (1 + Q1 * t + Q2 * t ^ 2) ^ 0
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, 0, 0, (1 : ℝ)] : Fin 9 → ℝ) i * t ^ (i : ℕ) := by
    intro t
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8W]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

end Sendov9.EIntW

#print axioms Sendov9.EIntW.integral_deg8W
#print axioms Sendov9.EIntW.intW_2_3
#print axioms Sendov9.EIntW.intW_3_2
#print axioms Sendov9.EIntW.intW_4_2
#print axioms Sendov9.EIntW.intW_5_1
#print axioms Sendov9.EIntW.intW_6_1
#print axioms Sendov9.EIntW.intW_7_0
#print axioms Sendov9.EIntW.intW_8_0
