import Mathlib

set_option maxHeartbeats 4000000

namespace Sendov9.EInt

open Finset intervalIntegral

/-!
# The seven closed forms behind the `E_S` majorant

Generated by `emit_eint.py`; do not hand-edit.

`IminusJ.norm_I_sub_J_le` delivers the majorant as an INTEGRAL,

    E_S(a,η) = ∑_{m=2}^{8} c_m a^{m+1} η^m ∫₀¹ v^m q_S(a,η;v)^{ℓ_m} dv,

while the certificates in `CertData.lean` are stated against the same quantity with
those integrals already evaluated.  These seven lemmas are the bridge, and the same
seven serve all eighteen rows -- only `Q1 = -(8-S+Sa²)/4` and `Q2 = a²(1-η²)` change.

Each identity was verified symbolically and at random rational points by the generator
before being emitted, and the right-hand sides are transcribed verbatim from
`Sendov9Complete.lean` so the row assembly can rewrite with them directly.

The exponents are `(ℓ₂,…,ℓ₈) = (3,2,2,1,1,0,0)`, the half-integral powers of the paper
rounded DOWN (`q^{5/2} ≤ q²`, `q^{3/2} ≤ q`, `q^{1/2} ≤ 1`) -- which is valid precisely
because `0 ≤ q ≤ 1` at feasible points.  That rounding is why these are the only seven
needed.

Sendov's conjecture in degree nine remains unproven.
-/

/-- `∫₀¹ ∑ᵢ cᵢ vⁱ dv = ∑ᵢ cᵢ/(i+1)`, for a degree-8 coefficient vector.

Every integrand below expands to at most nine monomials (`ℓ ≤ 3`, `m ≤ 8` gives
`m + 2ℓ ≤ 8`), so this one lemma discharges all seven. -/
theorem integral_deg8 (c : Fin 9 → ℝ) :
    (∫ v in (0:ℝ)..1, ∑ i : Fin 9, c i * v ^ (i : ℕ))
      = ∑ i : Fin 9, c i / ((i : ℕ) + 1) := by
  rw [intervalIntegral.integral_finsetSum]
  · refine Finset.sum_congr rfl fun i _ => ?_
    rw [intervalIntegral.integral_const_mul, integral_pow]
    have h0 : (0:ℝ) ^ ((i : ℕ) + 1) = 0 := zero_pow (Nat.succ_ne_zero _)
    rw [h0]
    push_cast
    ring
  · intro i _
    exact (by fun_prop : Continuous fun v : ℝ => c i * v ^ (i : ℕ)).intervalIntegrable _ _

/-- `∫₀¹ v^2 (1 + Q1 v + Q2 v²)^3 dv`, in the exact form `CertData` states. -/
theorem int_2_3 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 2 * (1 + Q1 * v + Q2 * v ^ 2) ^ 3)
      = (1/3 : ℝ) + (3/5 : ℝ) * Q2 + (3/7 : ℝ) * Q2 ^ 2 + (1/9 : ℝ) * Q2 ^ 3 + (3/4 : ℝ) * Q1 + (1 : ℝ) * Q1 * Q2 + (3/8 : ℝ) * Q1 * Q2 ^ 2 + (3/5 : ℝ) * Q1 ^ 2 + (3/7 : ℝ) * Q1 ^ 2 * Q2 + (1/6 : ℝ) * Q1 ^ 3 := by
  have hexp : ∀ v : ℝ, v ^ 2 * (1 + Q1 * v + Q2 * v ^ 2) ^ 3
      = ∑ i : Fin 9, (![0, 0, (1 : ℝ), (3 : ℝ) * Q1, (3 : ℝ) * Q2 + (3 : ℝ) * Q1 ^ 2, (6 : ℝ) * Q1 * Q2 + Q1 ^ 3, (3 : ℝ) * Q2 ^ 2 + (3 : ℝ) * Q1 ^ 2 * Q2, (3 : ℝ) * Q1 * Q2 ^ 2, Q2 ^ 3] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^3 (1 + Q1 v + Q2 v²)^2 dv`, in the exact form `CertData` states. -/
theorem int_3_2 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 3 * (1 + Q1 * v + Q2 * v ^ 2) ^ 2)
      = (1/4 : ℝ) + (1/3 : ℝ) * Q2 + (1/8 : ℝ) * Q2 ^ 2 + (2/5 : ℝ) * Q1 + (2/7 : ℝ) * Q1 * Q2 + (1/6 : ℝ) * Q1 ^ 2 := by
  have hexp : ∀ v : ℝ, v ^ 3 * (1 + Q1 * v + Q2 * v ^ 2) ^ 2
      = ∑ i : Fin 9, (![0, 0, 0, (1 : ℝ), (2 : ℝ) * Q1, (2 : ℝ) * Q2 + Q1 ^ 2, (2 : ℝ) * Q1 * Q2, Q2 ^ 2, 0] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^4 (1 + Q1 v + Q2 v²)^2 dv`, in the exact form `CertData` states. -/
theorem int_4_2 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 4 * (1 + Q1 * v + Q2 * v ^ 2) ^ 2)
      = (1/5 : ℝ) + (2/7 : ℝ) * Q2 + (1/9 : ℝ) * Q2 ^ 2 + (1/3 : ℝ) * Q1 + (1/4 : ℝ) * Q1 * Q2 + (1/7 : ℝ) * Q1 ^ 2 := by
  have hexp : ∀ v : ℝ, v ^ 4 * (1 + Q1 * v + Q2 * v ^ 2) ^ 2
      = ∑ i : Fin 9, (![0, 0, 0, 0, (1 : ℝ), (2 : ℝ) * Q1, (2 : ℝ) * Q2 + Q1 ^ 2, (2 : ℝ) * Q1 * Q2, Q2 ^ 2] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^5 (1 + Q1 v + Q2 v²)^1 dv`, in the exact form `CertData` states. -/
theorem int_5_1 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 5 * (1 + Q1 * v + Q2 * v ^ 2) ^ 1)
      = (1/6 : ℝ) + (1/8 : ℝ) * Q2 + (1/7 : ℝ) * Q1 := by
  have hexp : ∀ v : ℝ, v ^ 5 * (1 + Q1 * v + Q2 * v ^ 2) ^ 1
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, (1 : ℝ), Q1, Q2, 0] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^6 (1 + Q1 v + Q2 v²)^1 dv`, in the exact form `CertData` states. -/
theorem int_6_1 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 6 * (1 + Q1 * v + Q2 * v ^ 2) ^ 1)
      = (1/7 : ℝ) + (1/9 : ℝ) * Q2 + (1/8 : ℝ) * Q1 := by
  have hexp : ∀ v : ℝ, v ^ 6 * (1 + Q1 * v + Q2 * v ^ 2) ^ 1
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, (1 : ℝ), Q1, Q2] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^7 (1 + Q1 v + Q2 v²)^0 dv`, in the exact form `CertData` states. -/
theorem int_7_0 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 7 * (1 + Q1 * v + Q2 * v ^ 2) ^ 0)
      = (1/8 : ℝ) := by
  have hexp : ∀ v : ℝ, v ^ 7 * (1 + Q1 * v + Q2 * v ^ 2) ^ 0
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, 0, (1 : ℝ), 0] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

/-- `∫₀¹ v^8 (1 + Q1 v + Q2 v²)^0 dv`, in the exact form `CertData` states. -/
theorem int_8_0 (Q1 Q2 : ℝ) :
    (∫ v in (0:ℝ)..1, v ^ 8 * (1 + Q1 * v + Q2 * v ^ 2) ^ 0)
      = (1/9 : ℝ) := by
  have hexp : ∀ v : ℝ, v ^ 8 * (1 + Q1 * v + Q2 * v ^ 2) ^ 0
      = ∑ i : Fin 9, (![0, 0, 0, 0, 0, 0, 0, 0, (1 : ℝ)] : Fin 9 → ℝ) i * v ^ (i : ℕ) := by
    intro v
    simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
      Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
    push_cast
    ring
  simp only [hexp]
  rw [integral_deg8]
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, Fin.val_zero, Fin.val_succ]
  push_cast
  ring

end Sendov9.EInt

#print axioms Sendov9.EInt.integral_deg8
#print axioms Sendov9.EInt.int_2_3
#print axioms Sendov9.EInt.int_3_2
#print axioms Sendov9.EInt.int_4_2
#print axioms Sendov9.EInt.int_5_1
#print axioms Sendov9.EInt.int_6_1
#print axioms Sendov9.EInt.int_7_0
#print axioms Sendov9.EInt.int_8_0
