import Mathlib
import Sendov9.RowPrep
import Sendov9.MidCover

set_option maxHeartbeats 4000000

namespace Sendov9.MidRows

open Finset

/-!
# The eighteen middle-range rows, and `RangeMid`

Generated by `emit_rows.py`; do not hand-edit.  `RowPrep.row1` is the hand-validated
pattern; these are the same eleven lines with each row's own constants, which are parsed
straight out of `CertData.lean` so no constant is ever retyped.

Each row supplies five numbers `(α, β, S, λ, Y)` and four banked facts —
`MidTable.row<i>_L`, the row's side conditions (by `norm_num`),
`SigmaRows.sigma_row<i>`, and `Cert.i<i>_pos` — to `MidRow.row_excluded`.  The `hPdef`
obligation is `rfl`, because `P` is *defined* to be the certificate's own expression;
the `cert` obligation is `EmajEq.Emaj_eq` followed by `ring`.

`hsep` (the separation bound `rₖ > m₀ = 681/1000`) and `hprod` (`∏rₖ > 9`) are carried
through every row and into `mid_excluded`.  `hsep` is where Grace–Walsh–Szegő enters,
and it is the campaign's last unproved input; `hprod` is `Instantiate.prod_r_gt_nine`,
which is proved but stated against the other copy of `Counterexample`.

Sendov's conjecture in degree nine remains unproven.
-/

variable (C : Counterexample)

/-- Row 1: `a ∈ [9/20, 19/40]`, `S = 11043/2000`, `λ = 49/50`, `Y = 199/1000`. -/
theorem row1
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (9/20 : ℝ) ≤ C.a) (h1 : C.a ≤ (19/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (59/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (11043/2000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row1 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (9/20 : ℝ)) (beta := (19/40 : ℝ))
    (S := (11043/2000 : ℝ)) (lam := (49/50 : ℝ)) (Y := (199/1000 : ℝ))
    (cconst := (92577811623735141906142997/1610612736000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (11043/2000 : ℝ) x e ^ 4 / (9 * (49/50 : ℝ))
      - MidRow.Emaj (11043/2000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row1_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i1_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 2: `a ∈ [19/40, 1/2]`, `S = 2783/500`, `λ = 239/250`, `Y = 587/2000`. -/
theorem row2
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (19/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (1/2 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (3/2 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (2783/500 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row2 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (19/40 : ℝ)) (beta := (1/2 : ℝ))
    (S := (2783/500 : ℝ)) (lam := (239/250 : ℝ)) (Y := (587/2000 : ℝ))
    (cconst := (1927441872124399/35241984000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (2783/500 : ℝ) x e ^ 4 / (9 * (239/250 : ℝ))
      - MidRow.Emaj (2783/500 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row2_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i2_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 3: `a ∈ [1/2, 21/40]`, `S = 2257/400`, `λ = 1863/2000`, `Y = 91/250`. -/
theorem row3
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (1/2 : ℝ) ≤ C.a) (h1 : C.a ≤ (21/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (61/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (2257/400 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row3 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (1/2 : ℝ)) (beta := (21/40 : ℝ))
    (S := (2257/400 : ℝ)) (lam := (1863/2000 : ℝ)) (Y := (91/250 : ℝ))
    (cconst := (230461995028707141798319/4445291151360000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (2257/400 : ℝ) x e ^ 4 / (9 * (1863/2000 : ℝ))
      - MidRow.Emaj (2257/400 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row3_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i3_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 4: `a ∈ [21/40, 11/20]`, `S = 1151/200`, `λ = 1811/2000`, `Y = 849/2000`. -/
theorem row4
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (21/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (11/20 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (31/20 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (1151/200 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row4 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (21/40 : ℝ)) (beta := (11/20 : ℝ))
    (S := (1151/200 : ℝ)) (lam := (1811/2000 : ℝ)) (Y := (849/2000 : ℝ))
    (cconst := (464523916465076855591/9494855680000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (1151/200 : ℝ) x e ^ 4 / (9 * (1811/2000 : ℝ))
      - MidRow.Emaj (1151/200 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row4_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i4_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 5: `a ∈ [11/20, 23/40]`, `S = 11819/2000`, `λ = 879/1000`, `Y = 477/1000`. -/
theorem row5
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (11/20 : ℝ) ≤ C.a) (h1 : C.a ≤ (23/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (63/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (11819/2000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row5 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (11/20 : ℝ)) (beta := (23/40 : ℝ))
    (S := (11819/2000 : ℝ)) (lam := (879/1000 : ℝ)) (Y := (477/1000 : ℝ))
    (cconst := (3249402479531992864287158533/70786429747200000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (11819/2000 : ℝ) x e ^ 4 / (9 * (879/1000 : ℝ))
      - MidRow.Emaj (11819/2000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row5_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i5_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 6: `a ∈ [23/40, 3/5]`, `S = 764/125`, `λ = 1699/2000`, `Y = 66/125`. -/
theorem row6
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (23/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (3/5 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (8/5 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (764/125 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row6 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (23/40 : ℝ)) (beta := (3/5 : ℝ))
    (S := (764/125 : ℝ)) (lam := (1699/2000 : ℝ)) (Y := (66/125 : ℝ))
    (cconst := (3305267493880583237450540576/87225227616727352142333984375 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (764/125 : ℝ) x e ^ 4 / (9 * (1699/2000 : ℝ))
      - MidRow.Emaj (764/125 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row6_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i6_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 7: `a ∈ [3/5, 5/8]`, `S = 637/100`, `λ = 817/1000`, `Y = 577/1000`. -/
theorem row7
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (3/5 : ℝ) ≤ C.a) (h1 : C.a ≤ (5/8 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (13/8 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (637/100 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row7 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (3/5 : ℝ)) (beta := (5/8 : ℝ))
    (S := (637/100 : ℝ)) (lam := (817/1000 : ℝ)) (Y := (577/1000 : ℝ))
    (cconst := (202516872298527333744738627377/8253140436516864000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (637/100 : ℝ) x e ^ 4 / (9 * (817/1000 : ℝ))
      - MidRow.Emaj (637/100 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row7_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i7_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 8: `a ∈ [5/8, 13/20]`, `S = 13093/2000`, `λ = 401/500`, `Y = 239/400`. -/
theorem row8
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (5/8 : ℝ) ≤ C.a) (h1 : C.a ≤ (13/20 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (33/20 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (13093/2000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row8 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (5/8 : ℝ)) (beta := (13/20 : ℝ))
    (S := (13093/2000 : ℝ)) (lam := (401/500 : ℝ)) (Y := (239/400 : ℝ))
    (cconst := (105764659841805578093552263412670097/8476856156160000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (13093/2000 : ℝ) x e ^ 4 / (9 * (401/500 : ℝ))
      - MidRow.Emaj (13093/2000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row8_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i8_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 9: `a ∈ [13/20, 27/40]`, `S = 13113/2000`, `λ = 81/100`, `Y = 1173/2000`. -/
theorem row9
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (13/20 : ℝ) ≤ C.a) (h1 : C.a ≤ (27/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (67/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (13113/2000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row9 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (13/20 : ℝ)) (beta := (27/40 : ℝ))
    (S := (13113/2000 : ℝ)) (lam := (81/100 : ℝ)) (Y := (1173/2000 : ℝ))
    (cconst := (3096042321090968025085362800832236382277943/342456532992000000000000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (13113/2000 : ℝ) x e ^ 4 / (9 * (81/100 : ℝ))
      - MidRow.Emaj (13113/2000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row9_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i9_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 10: `a ∈ [27/40, 7/10]`, `S = 3289/500`, `λ = 409/500`, `Y = 1151/2000`. -/
theorem row10
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (27/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (7/10 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (17/10 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (3289/500 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row10 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (27/40 : ℝ)) (beta := (7/10 : ℝ))
    (S := (3289/500 : ℝ)) (lam := (409/500 : ℝ)) (Y := (1151/2000 : ℝ))
    (cconst := (5695432798606075648776913558137477041/942336000000000000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (3289/500 : ℝ) x e ^ 4 / (9 * (409/500 : ℝ))
      - MidRow.Emaj (3289/500 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row10_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i10_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 11: `a ∈ [7/10, 29/40]`, `S = 529/80`, `λ = 413/500`, `Y = 141/250`. -/
theorem row11
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (7/10 : ℝ) ≤ C.a) (h1 : C.a ≤ (29/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (69/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (529/80 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row11 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (7/10 : ℝ)) (beta := (29/40 : ℝ))
    (S := (529/80 : ℝ)) (lam := (413/500 : ℝ)) (Y := (141/250 : ℝ))
    (cconst := (55021932470333891031895506582189229891/15224832000000000000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (529/80 : ℝ) x e ^ 4 / (9 * (413/500 : ℝ))
      - MidRow.Emaj (529/80 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row11_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i11_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 12: `a ∈ [29/40, 3/4]`, `S = 6661/1000`, `λ = 1669/2000`, `Y = 1103/2000`. -/
theorem row12
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (29/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (3/4 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (7/4 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (6661/1000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row12 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (29/40 : ℝ)) (beta := (3/4 : ℝ))
    (S := (6661/1000 : ℝ)) (lam := (1669/2000 : ℝ)) (Y := (1103/2000 : ℝ))
    (cconst := (10320801967148305507097523660378169/5488230006784000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (6661/1000 : ℝ) x e ^ 4 / (9 * (1669/2000 : ℝ))
      - MidRow.Emaj (6661/1000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row12_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i12_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 13: `a ∈ [3/4, 31/40]`, `S = 1681/250`, `λ = 843/1000`, `Y = 269/500`. -/
theorem row13
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (3/4 : ℝ) ≤ C.a) (h1 : C.a ≤ (31/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (71/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (1681/250 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row13 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (3/4 : ℝ)) (beta := (31/40 : ℝ))
    (S := (1681/250 : ℝ)) (lam := (843/1000 : ℝ)) (Y := (269/500 : ℝ))
    (cconst := (6769993742652620379407021199535146161/7769088000000000000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (1681/250 : ℝ) x e ^ 4 / (9 * (843/1000 : ℝ))
      - MidRow.Emaj (1681/250 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row13_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i13_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 14: `a ∈ [31/40, 4/5]`, `S = 1701/250`, `λ = 213/250`, `Y = 131/250`. -/
theorem row14
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (31/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (4/5 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (9/5 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (1701/250 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row14 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (31/40 : ℝ)) (beta := (4/5 : ℝ))
    (S := (1701/250 : ℝ)) (lam := (213/250 : ℝ)) (Y := (131/250 : ℝ))
    (cconst := (1525995182936088798318336809/3199338912963867187500000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (1701/250 : ℝ) x e ^ 4 / (9 * (213/250 : ℝ))
      - MidRow.Emaj (1701/250 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row14_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i14_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 15: `a ∈ [4/5, 33/40]`, `S = 2761/400`, `λ = 1723/2000`, `Y = 127/250`. -/
theorem row15
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (4/5 : ℝ) ≤ C.a) (h1 : C.a ≤ (33/40 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (73/40 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (2761/400 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row15 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (4/5 : ℝ)) (beta := (33/40 : ℝ))
    (S := (2761/400 : ℝ)) (lam := (1723/2000 : ℝ)) (Y := (127/250 : ℝ))
    (cconst := (2868145096427379856109762284567757053789/3501356544000000000000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (2761/400 : ℝ) x e ^ 4 / (9 * (1723/2000 : ℝ))
      - MidRow.Emaj (2761/400 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row15_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i15_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 16: `a ∈ [33/40, 17/20]`, `S = 14041/2000`, `λ = 109/125`, `Y = 49/100`. -/
theorem row16
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (33/40 : ℝ) ≤ C.a) (h1 : C.a ≤ (17/20 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (37/20 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (14041/2000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row16 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (33/40 : ℝ)) (beta := (17/20 : ℝ))
    (S := (14041/2000 : ℝ)) (lam := (109/125 : ℝ)) (Y := (49/100 : ℝ))
    (cconst := (268739417466468739054892761819327/185157550080000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (14041/2000 : ℝ) x e ^ 4 / (9 * (109/125 : ℝ))
      - MidRow.Emaj (14041/2000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row16_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i16_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 17: `a ∈ [17/20, 7/8]`, `S = 7161/1000`, `λ = 221/250`, `Y = 187/400`. -/
theorem row17
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (17/20 : ℝ) ≤ C.a) (h1 : C.a ≤ (7/8 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (15/8 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (7161/1000 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row17 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (17/20 : ℝ)) (beta := (7/8 : ℝ))
    (S := (7161/1000 : ℝ)) (lam := (221/250 : ℝ)) (Y := (187/400 : ℝ))
    (cconst := (83873711025795704221754032213513691/32702484971520000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (7161/1000 : ℝ) x e ^ 4 / (9 * (221/250 : ℝ))
      - MidRow.Emaj (7161/1000 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row17_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i17_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- Row 18: `a ∈ [7/8, 9/10]`, `S = 3663/500`, `λ = 359/400`, `Y = 883/2000`. -/
theorem row18
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (7/8 : ℝ) ≤ C.a) (h1 : C.a ≤ (9/10 : ℝ)) : False := by
  have hrle : ∀ k, C.r k ≤ (19/10 : ℝ) := fun k => le_trans (RowPrep.r_le C k) (by linarith)
  have hsig : C.sigma ≤ (3663/500 : ℝ) := by
    rw [RowPrep.sigma_eq C]
    exact SigmaRows.sigma_row18 C.r hsep hrle hprod
  refine MidRow.row_excluded (alpha := (7/8 : ℝ)) (beta := (9/10 : ℝ))
    (S := (3663/500 : ℝ)) (lam := (359/400 : ℝ)) (Y := (883/2000 : ℝ))
    (cconst := (147124769074112896191170363052161677/37005438222336000000000000000000000000 : ℝ))
    C (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num)
    (fun x e => (1 - x) / 9 + e ^ 2 / 18
      - MidAn.hh (3663/500 : ℝ) x e ^ 4 / (9 * (359/400 : ℝ))
      - MidRow.Emaj (3663/500 : ℝ) x e)
    ?_ (fun _ _ => rfl) (by norm_num) (Mid.row18_L h0 h1) hsig h0 h1 hI
  intro U V hU0 hU1 hV0 hV1
  refine le_trans (Cert.i18_pos hU0 hU1 hV0 hV1) (le_of_eq ?_)
  -- NOT `MidRow.Emaj` in this set: unfolding it to the integral form first stops
  -- `Emaj_eq` from firing, and the integrals then never get evaluated.
  simp only [EmajEq.Emaj_eq, MidAn.hh, MidMaj.Q1, MidMaj.Q2]
  ring

/-- **The middle range `9/20 ≤ a ≤ 9/10` is excluded.**

`Cover.mid_cover` is the verified statement that the eighteen intervals tile
`[9/20, 9/10]`; it is applied to `C.a` directly rather than through
`mid_excluded_of_rows`, whose row arguments quantify over an arbitrary real while these
rows are about `C.a`. -/
theorem mid_excluded
    (hsep : ∀ k, (681/1000 : ℝ) ≤ C.r k)
    (hprod : (9:ℝ) ≤ ∏ k, C.r k)
    (hI : ‖∫ t in (0:ℝ)..C.a, ∏ j, ((1 : ℂ) - (t : ℂ) * ((C.a : ℂ) - C.zeta j)⁻¹)‖
      < C.a / 9)
    (h0 : (9/20 : ℝ) ≤ C.a) (h1 : C.a ≤ (9/10 : ℝ)) : False := by
  rcases Cover.mid_cover C.a h0 h1 with
    h1 | h2 | h3 | h4 | h5 | h6 | h7 | h8 | h9 | h10 | h11 | h12 | h13 | h14 | h15 | h16 | h17 | h18
  · exact row1 C hsep hprod hI h1.1 h1.2
  · exact row2 C hsep hprod hI h2.1 h2.2
  · exact row3 C hsep hprod hI h3.1 h3.2
  · exact row4 C hsep hprod hI h4.1 h4.2
  · exact row5 C hsep hprod hI h5.1 h5.2
  · exact row6 C hsep hprod hI h6.1 h6.2
  · exact row7 C hsep hprod hI h7.1 h7.2
  · exact row8 C hsep hprod hI h8.1 h8.2
  · exact row9 C hsep hprod hI h9.1 h9.2
  · exact row10 C hsep hprod hI h10.1 h10.2
  · exact row11 C hsep hprod hI h11.1 h11.2
  · exact row12 C hsep hprod hI h12.1 h12.2
  · exact row13 C hsep hprod hI h13.1 h13.2
  · exact row14 C hsep hprod hI h14.1 h14.2
  · exact row15 C hsep hprod hI h15.1 h15.2
  · exact row16 C hsep hprod hI h16.1 h16.2
  · exact row17 C hsep hprod hI h17.1 h17.2
  · exact row18 C hsep hprod hI h18.1 h18.2

end Sendov9.MidRows

#print axioms Sendov9.MidRows.row1
#print axioms Sendov9.MidRows.row2
#print axioms Sendov9.MidRows.row3
#print axioms Sendov9.MidRows.row4
#print axioms Sendov9.MidRows.row5
#print axioms Sendov9.MidRows.row6
#print axioms Sendov9.MidRows.row7
#print axioms Sendov9.MidRows.row8
#print axioms Sendov9.MidRows.row9
#print axioms Sendov9.MidRows.row10
#print axioms Sendov9.MidRows.row11
#print axioms Sendov9.MidRows.row12
#print axioms Sendov9.MidRows.row13
#print axioms Sendov9.MidRows.row14
#print axioms Sendov9.MidRows.row15
#print axioms Sendov9.MidRows.row16
#print axioms Sendov9.MidRows.row17
#print axioms Sendov9.MidRows.row18
#print axioms Sendov9.MidRows.mid_excluded
