import Mathlib
import Sendov9.Sigma22Gen

set_option maxHeartbeats 4000000

namespace Sendov9.SigmaRows

open Finset

/-!
# The eighteen middle-range σ bounds

Generated by `emit_sigmarows.py`; do not hand-edit.

Table 1 of the paper says only "Lemma 2.2, with `M = 1 + β`, gives `σ ≤ S`".  With
Lemma 2.2 now proved in general form (`Sigma22Gen.sigma_le_of`, free in `m, M, C, ν`),
each row really is three lines: the row's `ν`, the two halves of `ν`'s definition, and
the arithmetic check that the closed form clears `S`.

That is the payoff of generalizing the base case.  `BaseNumerics.lean` needed a
hand-written case analysis in `h` for its ONE instance; there are nineteen instances in
the paper, and this is the other eighteen.

`ν = 7` for rows 1–7 and `ν = 6` for rows 8–18 — the transition is where `M = 1 + β`
grows past the point that six factors at `M` already clear the product constraint.

Margins between the general bound and the tabulated `S` run from `3.6·10⁻⁵` (row 10) to
`4.9·10⁻⁴` (row 12).  Every one was checked in exact rational arithmetic by the
generator before emission.

Each row's hypotheses are exactly what the counterexample supplies: `rₖ > m₀` (the
separation bound, which needs GWS), `rₖ ≤ 1 + a ≤ 1 + β`, and `∏rₖ > 9`.

Sendov's conjecture in degree nine remains unproven.
-/

/-- Row 1: `a ∈ [9/20, 19/40]`, so `M = 1 + β = 59/40`; `ν = 7` gives `σ ≤ 11043/2000`.
Margin over the general bound: `2.143e-04`. -/
theorem sigma_row1 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (59/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (11043/2000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 2: `a ∈ [19/40, 1/2]`, so `M = 1 + β = 3/2`; `ν = 7` gives `σ ≤ 2783/500`.
Margin over the general bound: `1.948e-04`. -/
theorem sigma_row2 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (3/2 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (2783/500 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 3: `a ∈ [1/2, 21/40]`, so `M = 1 + β = 61/40`; `ν = 7` gives `σ ≤ 2257/400`.
Margin over the general bound: `4.340e-04`. -/
theorem sigma_row3 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (61/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (2257/400 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 4: `a ∈ [21/40, 11/20]`, so `M = 1 + β = 31/20`; `ν = 7` gives `σ ≤ 1151/200`.
Margin over the general bound: `3.126e-04`. -/
theorem sigma_row4 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (31/20 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (1151/200 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 5: `a ∈ [11/20, 23/40]`, so `M = 1 + β = 63/40`; `ν = 7` gives `σ ≤ 11819/2000`.
Margin over the general bound: `4.100e-04`. -/
theorem sigma_row5 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (63/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (11819/2000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 6: `a ∈ [23/40, 3/5]`, so `M = 1 + β = 8/5`; `ν = 7` gives `σ ≤ 764/125`.
Margin over the general bound: `3.976e-04`. -/
theorem sigma_row6 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (8/5 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (764/125 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 7: `a ∈ [3/5, 5/8]`, so `M = 1 + β = 13/8`; `ν = 7` gives `σ ≤ 637/100`.
Margin over the general bound: `4.201e-04`. -/
theorem sigma_row7 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (13/8 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (637/100 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 7) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 8: `a ∈ [5/8, 13/20]`, so `M = 1 + β = 33/20`; `ν = 6` gives `σ ≤ 13093/2000`.
Margin over the general bound: `2.472e-04`. -/
theorem sigma_row8 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (33/20 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (13093/2000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 9: `a ∈ [13/20, 27/40]`, so `M = 1 + β = 67/40`; `ν = 6` gives `σ ≤ 13113/2000`.
Margin over the general bound: `2.149e-04`. -/
theorem sigma_row9 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (67/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (13113/2000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 10: `a ∈ [27/40, 7/10]`, so `M = 1 + β = 17/10`; `ν = 6` gives `σ ≤ 3289/500`.
Margin over the general bound: `3.569e-05`. -/
theorem sigma_row10 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (17/10 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (3289/500 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 11: `a ∈ [7/10, 29/40]`, so `M = 1 + β = 69/40`; `ν = 6` gives `σ ≤ 529/80`.
Margin over the general bound: `1.814e-04`. -/
theorem sigma_row11 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (69/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (529/80 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 12: `a ∈ [29/40, 3/4]`, so `M = 1 + β = 7/4`; `ν = 6` gives `σ ≤ 6661/1000`.
Margin over the general bound: `4.879e-04`. -/
theorem sigma_row12 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (7/4 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (6661/1000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 13: `a ∈ [3/4, 31/40]`, so `M = 1 + β = 71/40`; `ν = 6` gives `σ ≤ 1681/250`.
Margin over the general bound: `1.439e-04`. -/
theorem sigma_row13 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (71/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (1681/250 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 14: `a ∈ [31/40, 4/5]`, so `M = 1 + β = 9/5`; `ν = 6` gives `σ ≤ 1701/250`.
Margin over the general bound: `1.800e-04`. -/
theorem sigma_row14 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (9/5 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (1701/250 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 15: `a ∈ [4/5, 33/40]`, so `M = 1 + β = 73/40`; `ν = 6` gives `σ ≤ 2761/400`.
Margin over the general bound: `4.555e-04`. -/
theorem sigma_row15 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (73/40 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (2761/400 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 16: `a ∈ [33/40, 17/20]`, so `M = 1 + β = 37/20`; `ν = 6` gives `σ ≤ 14041/2000`.
Margin over the general bound: `1.448e-04`. -/
theorem sigma_row16 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (37/20 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (14041/2000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 17: `a ∈ [17/20, 7/8]`, so `M = 1 + β = 15/8`; `ν = 6` gives `σ ≤ 7161/1000`.
Margin over the general bound: `2.227e-04`. -/
theorem sigma_row17 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (15/8 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (7161/1000 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

/-- Row 18: `a ∈ [7/8, 9/10]`, so `M = 1 + β = 19/10`; `ν = 6` gives `σ ≤ 3663/500`.
Margin over the general bound: `4.484e-04`. -/
theorem sigma_row18 (r : Fin 8 → ℝ)
    (hlo : ∀ k, (681/1000 : ℝ) ≤ r k) (hhi : ∀ k, r k ≤ (19/10 : ℝ))
    (hprod : (9:ℝ) ≤ ∏ k, r k) :
    ∑ k, 1 / (r k) ^ 2 ≤ (3663/500 : ℝ) := by
  refine SigmaGen.sigma_le_of (nu := 6) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ?_ (by norm_num) r hlo hhi hprod
  intro j hj
  interval_cases j <;> norm_num

end Sendov9.SigmaRows

#print axioms Sendov9.SigmaRows.sigma_row1
#print axioms Sendov9.SigmaRows.sigma_row2
#print axioms Sendov9.SigmaRows.sigma_row3
#print axioms Sendov9.SigmaRows.sigma_row4
#print axioms Sendov9.SigmaRows.sigma_row5
#print axioms Sendov9.SigmaRows.sigma_row6
#print axioms Sendov9.SigmaRows.sigma_row7
#print axioms Sendov9.SigmaRows.sigma_row8
#print axioms Sendov9.SigmaRows.sigma_row9
#print axioms Sendov9.SigmaRows.sigma_row10
#print axioms Sendov9.SigmaRows.sigma_row11
#print axioms Sendov9.SigmaRows.sigma_row12
#print axioms Sendov9.SigmaRows.sigma_row13
#print axioms Sendov9.SigmaRows.sigma_row14
#print axioms Sendov9.SigmaRows.sigma_row15
#print axioms Sendov9.SigmaRows.sigma_row16
#print axioms Sendov9.SigmaRows.sigma_row17
#print axioms Sendov9.SigmaRows.sigma_row18
