/-
Copyright (c) 2026 PrincipiaAI. Released under Apache 2.0.

# MathDB #363496 — Conjecture 3.13 of Dovgoshey is FALSE

MathDB open problem #363496.  Source: Oleksiy Dovgoshey, *Ultrametric-preserving functions as
monoid endomorphisms*, arXiv:2406.07166v2, Conjecture 3.13 (published: Ukrains'kyi Matematychnyi
Visnyk 21(3) (2024) 331–348; transl. J. Math. Sci. 285(5) (2024) 666–680).

Writing `P_PU` for the monoid of pseudoultrametric-preserving self-maps of `ℝ⁺` under composition,
`[A]` for the submonoid generated by `A ⊆ P_PU`, and

  `X = {(ℝ⁺, g ∘ d⁺) : g ∈ A}`,   `d⁺ p q = if p = q then 0 else max p q`,

the conjecture asserts that if the identity lies in `A` then `R̄ ∪ {id} = P_X`, where `R̄` is the
union of the right ideals of `[A]`.

**It is false.**  The counterexample is four elements of `P_PU`:

  `e t = t`,  `u t = [2 ≤ t]`,  `v t = [t ≠ 0]`,  `z t = 0`,   `A = {e, u, v}`.

## The notation caveat, and why both readings are refuted

The source has an internal omission: Lemma 3.10 defines `R_A` as the right ideals `R` of `[A]`
that additionally satisfy `R ⊆ A`, while Proposition 3.12 and Conjecture 3.13 say only "all right
ideals".  The proof of Proposition 3.12 uses the omitted containment, so the intended reading
almost certainly keeps it.  This file refutes **both** readings, since a formalization that picked
one would be answering a question the source did not unambiguously ask:

* `conjecture_false_intended` — with `R ⊆ A`, there is no nonempty such ideal (`Rbar_eq_empty`),
  so the left side is `{e}`, while `v ∈ P_X`.
* `conjecture_false_literal` — without it, `[A]` is a right ideal of itself, so the left side
  contains `z`, while `z ∉ P_X`.

## What is defined rather than assumed

`P_PU` is defined by what it *means* — `Preserves f` says `f ∘ d` is a pseudoultrametric whenever
`d` is, quantified over all carrier types — **not** by the source's Proposition 2.2
characterization.  Only the direction actually needed (`preserves_of_monotone`: increasing and
vanishing at zero implies preserving) is proved, and it is proved rather than assumed.  Nothing in
this file is a hypothesis; the refutation is unconditional.

`P_X = {e, v}` exactly (`PX_eq`), which is the source's stated computation; the refutation itself
needs only `v ∈ P_X` and `z ∉ P_X`.

## A note on the ambient monoid

`[A]` is the closure of `A` under composition together with the identity, defined here as the
inductive predicate `Gen` rather than through `Function.End` and `Submonoid.closure`.  The Mathlib
route costs more than it pays: `Function.End α` is a plain `def`, so `u t` is not even an
application until it is unfolded, and every statement would need a type ascription.  `Gen` says
exactly the same thing about plain functions under `∘`, and `gen_eq` proves it is `{e, u, v, z}`.
-/
import Mathlib.Data.NNReal.Basic
import Mathlib.Order.MinMax
import Mathlib.Data.Set.Basic

namespace Principia.MathDB.P363496

open scoped NNReal

/-! ### Pseudoultrametrics and the monoid `P_PU` -/

/-- A pseudoultrametric: reflexive-at-zero, symmetric, and satisfying the strong (ultrametric)
triangle inequality.  There is no separation axiom — `d x y = 0` does not force `x = y`. -/
structure IsPseudoUltrametric {α : Type} (d : α → α → ℝ≥0) : Prop where
  self : ∀ x, d x x = 0
  symm : ∀ x y, d x y = d y x
  ultra : ∀ x y w, d x w ≤ max (d x y) (d y w)

/-- `f ∈ P_PU`: post-composing with `f` carries pseudoultrametrics to pseudoultrametrics.  This is
the definition, not the source's Proposition 2.2 characterization. -/
def Preserves (f : ℝ≥0 → ℝ≥0) : Prop :=
  ∀ (α : Type) (d : α → α → ℝ≥0), IsPseudoUltrametric d →
    IsPseudoUltrametric fun x y => f (d x y)

/-- **Proposition 2.2 of the source, the direction used here.**  An increasing `f` with `f 0 = 0`
is pseudoultrametric-preserving.  The strong triangle inequality survives because a monotone map
commutes with `max`. -/
theorem preserves_of_monotone {f : ℝ≥0 → ℝ≥0} (hm : Monotone f) (h0 : f 0 = 0) :
    Preserves f := by
  intro α d hd
  refine ⟨fun x => ?_, fun x y => ?_, fun x y w => ?_⟩
  · rw [hd.self x, h0]
  · rw [hd.symm x y]
  · calc f (d x w) ≤ f (max (d x y) (d y w)) := hm (hd.ultra x y w)
      _ = max (f (d x y)) (f (d y w)) := hm.map_max

/-! ### The four functions -/

/-- `e t = t`, the monoid identity. -/
def e : ℝ≥0 → ℝ≥0 := fun t => t

/-- `u = 𝟙_{[2,∞)}`. -/
noncomputable def u : ℝ≥0 → ℝ≥0 := fun t => if 2 ≤ t then 1 else 0

/-- `v = 𝟙_{(0,∞)}`. -/
noncomputable def v : ℝ≥0 → ℝ≥0 := fun t => if t = 0 then 0 else 1

/-- `z`, the zero function. -/
def zf : ℝ≥0 → ℝ≥0 := fun _ => 0

theorem e_eq_id : e = id := rfl

/-- `0 ≤ x` over `ℝ≥0`.  Written once through `first`, because whether the canonically-ordered
`zero_le` takes its argument explicitly has moved between Mathlib versions, and a headless build
cannot be asked. -/
theorem nn_zero_le (x : ℝ≥0) : 0 ≤ x := by
  first
  | exact zero_le x
  | exact zero_le
  | exact zero_le'
  | simp
  | positivity

/-! The numeral facts the table rests on, isolated so that a `norm_num` failure over `ℝ≥0` has a
single repair site. -/

theorem two_not_le_zero : ¬ ((2 : ℝ≥0) ≤ 0) := by norm_num

theorem two_not_le_one : ¬ ((2 : ℝ≥0) ≤ 1) := by norm_num

theorem two_ne_one : (2 : ℝ≥0) ≠ 1 := by norm_num

theorem two_ne_zero' : (2 : ℝ≥0) ≠ 0 := by norm_num

theorem u_zero : u 0 = 0 := if_neg two_not_le_zero

theorem u_one : u 1 = 0 := if_neg two_not_le_one

theorem u_two : u 2 = 1 := if_pos le_rfl

theorem v_zero : v 0 = 0 := if_pos rfl

theorem v_one : v 1 = 1 := if_neg one_ne_zero

theorem v_two : v 2 = 1 := if_neg two_ne_zero'

/-- `u` takes only the values `0` and `1`. -/
theorem u_apply (t : ℝ≥0) : u t = 0 ∨ u t = 1 := by
  unfold u
  split_ifs with h
  · exact Or.inr rfl
  · exact Or.inl rfl

/-- `v` takes only the values `0` and `1`. -/
theorem v_apply (t : ℝ≥0) : v t = 0 ∨ v t = 1 := by
  unfold v
  split_ifs with h
  · exact Or.inl rfl
  · exact Or.inr rfl

/-- `u t = 1` only above the threshold. -/
theorem two_le_of_u_eq_one {t : ℝ≥0} (h : u t = 1) : (2 : ℝ≥0) ≤ t := by
  by_contra hc
  rw [show u t = 0 from if_neg hc] at h
  exact zero_ne_one h

theorem u_monotone : Monotone u := by
  intro a b hab
  rcases u_apply a with h | h
  · rw [h]
    exact nn_zero_le _
  · have hb : u b = 1 := if_pos (le_trans (two_le_of_u_eq_one h) hab)
    exact le_of_eq (h.trans hb.symm)

theorem v_monotone : Monotone v := by
  intro a b hab
  rcases v_apply a with h | h
  · rw [h]
    exact nn_zero_le _
  · have ha : a ≠ 0 := by
      intro hc
      rw [hc, v_zero] at h
      exact zero_ne_one h
    have hb : b ≠ 0 := by
      intro hc
      rw [hc] at hab
      exact ha (le_antisymm hab (nn_zero_le a))
    have hbv : v b = 1 := if_neg hb
    exact le_of_eq (h.trans hbv.symm)

/-! ### The composition table

`f ∘ g` applies `g` first, so the left factor indexes rows exactly as in the source's table. -/

theorem e_comp (f : ℝ≥0 → ℝ≥0) : e ∘ f = f := rfl

theorem comp_e (f : ℝ≥0 → ℝ≥0) : f ∘ e = f := rfl

theorem zf_comp (f : ℝ≥0 → ℝ≥0) : zf ∘ f = zf := rfl

theorem u_comp_u : u ∘ u = zf := by
  funext t
  show u (u t) = zf t
  rcases u_apply t with h | h
  · rw [h]; exact u_zero
  · rw [h]; exact u_one

theorem u_comp_v : u ∘ v = zf := by
  funext t
  show u (v t) = zf t
  rcases v_apply t with h | h
  · rw [h]; exact u_zero
  · rw [h]; exact u_one

theorem u_comp_zf : u ∘ zf = zf := by
  funext t
  show u (zf t) = zf t
  exact u_zero

theorem v_comp_u : v ∘ u = u := by
  funext t
  show v (u t) = u t
  rcases u_apply t with h | h
  · rw [h]; exact v_zero
  · rw [h]; exact v_one

theorem v_comp_v : v ∘ v = v := by
  funext t
  show v (v t) = v t
  rcases v_apply t with h | h
  · rw [h]; exact v_zero
  · rw [h]; exact v_one

theorem v_comp_zf : v ∘ zf = zf := by
  funext t
  show v (zf t) = zf t
  exact v_zero

/-! ### The four functions are distinct -/

theorem zf_ne_e : zf ≠ e := by
  intro h
  have h1 : (0 : ℝ≥0) = 1 := congrFun h 1
  exact zero_ne_one h1

theorem zf_ne_u : zf ≠ u := by
  intro h
  have h1 : (0 : ℝ≥0) = u 2 := congrFun h 2
  rw [u_two] at h1
  exact zero_ne_one h1

theorem zf_ne_v : zf ≠ v := by
  intro h
  have h1 : (0 : ℝ≥0) = v 1 := congrFun h 1
  rw [v_one] at h1
  exact zero_ne_one h1

theorem e_ne_v : e ≠ v := by
  intro h
  have h1 : (2 : ℝ≥0) = v 2 := congrFun h 2
  rw [v_two] at h1
  exact two_ne_one h1

/-! ### `A`, and the monoid `[A]` it generates -/

/-- `A = {e, u, v}`, the source's generating set.  It contains the identity, which is the
conjecture's hypothesis. -/
def A : Set (ℝ≥0 → ℝ≥0) := {e, u, v}

/-- `M = {e, u, v, z}`, which `gen_eq` proves is `[A]`. -/
def M : Set (ℝ≥0 → ℝ≥0) := {e, u, v, zf}

theorem id_mem_A : id ∈ A := Or.inl rfl

theorem e_mem_M : e ∈ M := Or.inl rfl

theorem u_mem_M : u ∈ M := Or.inr (Or.inl rfl)

theorem v_mem_M : v ∈ M := Or.inr (Or.inr (Or.inl rfl))

theorem zf_mem_M : zf ∈ M := Or.inr (Or.inr (Or.inr rfl))

/-- Every member of `A` is pseudoultrametric-preserving — the hypothesis `A ⊆ P_PU`. -/
theorem A_subset_preserves : ∀ f ∈ A, Preserves f := by
  rintro f (rfl | rfl | rfl)
  · exact preserves_of_monotone (fun _ _ h => h) rfl
  · exact preserves_of_monotone u_monotone u_zero
  · exact preserves_of_monotone v_monotone v_zero

/-- `[A]`: the closure of `A` under composition together with the identity. -/
inductive Gen : (ℝ≥0 → ℝ≥0) → Prop
  | base {f} : f ∈ A → Gen f
  | protected id : Gen id
  | comp {f g} : Gen f → Gen g → Gen (f ∘ g)

theorem M_comp_mem {f g : ℝ≥0 → ℝ≥0} (hf : f ∈ M) (hg : g ∈ M) : f ∘ g ∈ M := by
  simp only [M, Set.mem_insert_iff, Set.mem_singleton_iff] at hf hg
  rcases hf with rfl | rfl | rfl | rfl <;> rcases hg with rfl | rfl | rfl | rfl <;>
    simp [M, e_comp, comp_e, zf_comp, u_comp_u, u_comp_v, u_comp_zf,
      v_comp_u, v_comp_v, v_comp_zf]

/-- **`[A] = {e, u, v, z}`.**  Closure adds exactly the zero function, as `z = u ∘ u`. -/
theorem gen_eq (f : ℝ≥0 → ℝ≥0) : Gen f ↔ f ∈ M := by
  constructor
  · intro hf
    induction hf with
    | base hmem =>
      rcases hmem with rfl | rfl | rfl
      · exact e_mem_M
      · exact u_mem_M
      · exact v_mem_M
    | id => exact e_mem_M
    | comp _ _ ihf ihg => exact M_comp_mem ihf ihg
  · intro hf
    simp only [M, Set.mem_insert_iff, Set.mem_singleton_iff] at hf
    rcases hf with rfl | rfl | rfl | rfl
    · exact Gen.base (Or.inl rfl)
    · exact Gen.base (Or.inr (Or.inl rfl))
    · exact Gen.base (Or.inr (Or.inr rfl))
    · rw [← u_comp_u]
      exact Gen.comp (Gen.base (Or.inr (Or.inl rfl))) (Gen.base (Or.inr (Or.inl rfl)))

theorem zf_not_mem_A : zf ∉ A := by
  rintro (h | h | h)
  · exact zf_ne_e h
  · exact zf_ne_u h
  · exact zf_ne_v h

/-! ### `d⁺` and the family `X` -/

/-- `d⁺ p q = 0` if `p = q`, and `max p q` otherwise: the source's pseudoultrametric on `ℝ⁺`. -/
noncomputable def dplus (p q : ℝ≥0) : ℝ≥0 := if p = q then 0 else max p q

/-- `d⁺` is surjective, because `d⁺ 0 t = t` for every `t`.  This is what forces a member of `P_X`
to lie in `A`. -/
theorem dplus_zero_left (t : ℝ≥0) : dplus 0 t = t := by
  unfold dplus
  by_cases h : (0 : ℝ≥0) = t
  · rw [if_pos h]; exact h
  · rw [if_neg h]; exact max_eq_right (nn_zero_le t)

theorem dplus_isPU : IsPseudoUltrametric dplus := by
  refine ⟨fun x => ?_, fun p q => ?_, fun p q r => ?_⟩
  · unfold dplus; rw [if_pos rfl]
  · unfold dplus
    by_cases h : p = q
    · rw [if_pos h, if_pos h.symm]
    · rw [if_neg h, if_neg (Ne.symm h), max_comm p q]
  · unfold dplus
    by_cases hpr : p = r
    · rw [if_pos hpr]; exact nn_zero_le _
    · rw [if_neg hpr]
      by_cases hpq : p = q
      · have hqr : q ≠ r := fun hh => hpr (hpq.trans hh)
        rw [if_pos hpq, if_neg hqr, ← hpq]
        exact le_max_right _ _
      · rw [if_neg hpq]
        by_cases hqr : q = r
        · rw [if_pos hqr, hqr]
          exact le_max_left _ _
        · rw [if_neg hqr]
          refine max_le ?_ ?_
          · exact le_trans (le_max_left p q) (le_max_left _ _)
          · exact le_trans (le_max_right q r) (le_max_right _ _)

/-- `X = {(ℝ⁺, g ∘ d⁺) : g ∈ A}`, recorded by the distance functions themselves. -/
def X : Set (ℝ≥0 → ℝ≥0 → ℝ≥0) := {ρ | ∃ g ∈ A, ρ = fun p q => g (dplus p q)}

/-- Every member of `X` really is a pseudoultrametric — so `X` is a family of pseudoultrametric
spaces, not an empty abstraction. -/
theorem X_isPU : ∀ ρ ∈ X, IsPseudoUltrametric ρ := by
  rintro ρ ⟨g, hg, rfl⟩
  exact A_subset_preserves g hg ℝ≥0 dplus dplus_isPU

/-- `P_X`: the pseudoultrametric-preserving maps that carry `X` into `X`. -/
def PX : Set (ℝ≥0 → ℝ≥0) := {f | Preserves f ∧ ∀ ρ ∈ X, (fun p q => f (ρ p q)) ∈ X}

theorem e_mem_PX : e ∈ PX := by
  refine ⟨preserves_of_monotone (fun _ _ h => h) rfl, ?_⟩
  rintro ρ ⟨g, hg, rfl⟩
  exact ⟨g, hg, rfl⟩

/-- **`v ∈ P_X`.**  The row of `v` in the composition table is `v∘e = v`, `v∘u = u`, `v∘v = v`, all
of which lie in `A`. -/
theorem v_mem_PX : v ∈ PX := by
  refine ⟨preserves_of_monotone v_monotone v_zero, ?_⟩
  rintro ρ ⟨g, hg, rfl⟩
  refine ⟨v ∘ g, ?_, rfl⟩
  rcases hg with rfl | rfl | rfl
  · rw [comp_e]; exact Or.inr (Or.inr rfl)
  · rw [v_comp_u]; exact Or.inr (Or.inl rfl)
  · rw [v_comp_v]; exact Or.inr (Or.inr rfl)

/-- Applying a member of `P_X` to `e ∘ d⁺ ∈ X` and using surjectivity of `d⁺` pins it inside
`A`. -/
theorem mem_A_of_mem_PX {f : ℝ≥0 → ℝ≥0} (hf : f ∈ PX) : f ∈ A := by
  obtain ⟨g, hg, hgeq⟩ := hf.2 (fun p q => e (dplus p q)) ⟨e, Or.inl rfl, rfl⟩
  have hfg : f = g := by
    funext t
    have h := congrFun (congrFun hgeq 0) t
    rw [dplus_zero_left] at h
    exact h
  rw [hfg]
  exact hg

/-- `u ∉ P_X`: it sends `u ∘ d⁺ ∈ X` to `z ∘ d⁺`, and `z ∉ A`. -/
theorem u_not_mem_PX : u ∉ PX := by
  intro hf
  obtain ⟨g, hg, hgeq⟩ := hf.2 (fun p q => u (dplus p q)) ⟨u, Or.inr (Or.inl rfl), rfl⟩
  have hgz : g = zf := by
    funext t
    have h := congrFun (congrFun hgeq 0) t
    rw [dplus_zero_left] at h
    rw [← h]
    exact congrFun u_comp_u t
  rw [hgz] at hg
  exact zf_not_mem_A hg

/-- `z ∉ P_X`: it sends `e ∘ d⁺` to the identically zero pseudoultrametric, which is not in
`X`. -/
theorem zf_not_mem_PX : zf ∉ PX := by
  intro hf
  obtain ⟨g, hg, hgeq⟩ := hf.2 (fun p q => e (dplus p q)) ⟨e, Or.inl rfl, rfl⟩
  have hgz : g = zf := by
    funext t
    have h := congrFun (congrFun hgeq 0) t
    rw [dplus_zero_left] at h
    exact h.symm
  rw [hgz] at hg
  exact zf_not_mem_A hg

/-- **`P_X = {e, v}`**, the source's computation. -/
theorem PX_eq : PX = {e, v} := by
  refine Set.Subset.antisymm (fun f hf => ?_) ?_
  · rcases mem_A_of_mem_PX hf with rfl | rfl | rfl
    · exact Or.inl rfl
    · exact absurd hf u_not_mem_PX
    · exact Or.inr rfl
  · rintro f (rfl | rfl)
    · exact e_mem_PX
    · exact v_mem_PX

/-! ### Right ideals and the two readings of `R̄` -/

/-- A right ideal of `[A]`: a subset closed under right composition by `[A]`. -/
def IsRightIdeal (R : Set (ℝ≥0 → ℝ≥0)) : Prop :=
  R ⊆ M ∧ ∀ r ∈ R, ∀ s ∈ M, r ∘ s ∈ R

/-- Lemma 3.10's `R_A`: the right ideals of `[A]` that are **contained in `A`** — the intended
reading, used in the proof of Proposition 3.12. -/
def RA : Set (Set (ℝ≥0 → ℝ≥0)) := {R | IsRightIdeal R ∧ R ⊆ A}

/-- `R̄` under the intended reading. -/
def Rbar : Set (ℝ≥0 → ℝ≥0) := ⋃₀ RA

/-- `R̄` under the literal "all right ideals" reading. -/
def RbarLiteral : Set (ℝ≥0 → ℝ≥0) := ⋃₀ {R | IsRightIdeal R}

/-- **No nonempty right ideal of `[A]` is contained in `A`.**  Right-composing `e` with `z`, `u`
with `u`, or `v` with `z` produces `z ∉ A` in every case. -/
theorem Rbar_eq_empty : Rbar = ∅ := by
  ext f
  simp only [Set.mem_empty_iff_false, iff_false]
  rintro ⟨R, ⟨⟨-, hRid⟩, hRA⟩, hfR⟩
  have hzf : zf ∈ R := by
    rcases hRA hfR with rfl | rfl | rfl
    · have h := hRid e hfR zf zf_mem_M
      rwa [e_comp] at h
    · have h := hRid u hfR u u_mem_M
      rwa [u_comp_u] at h
    · have h := hRid v hfR zf zf_mem_M
      rwa [v_comp_zf] at h
  exact zf_not_mem_A (hRA hzf)

/-- Hence `R̄ ∪ {id} = {e}` under the intended reading. -/
theorem Rbar_union_id : Rbar ∪ {id} = ({e} : Set (ℝ≥0 → ℝ≥0)) := by
  rw [Rbar_eq_empty, Set.empty_union]
  rfl

/-- Under the literal reading `R̄ = [A]`, since `[A]` is a right ideal of itself. -/
theorem RbarLiteral_eq : RbarLiteral = M := by
  refine Set.Subset.antisymm ?_ ?_
  · rintro f ⟨R, ⟨hRM, -⟩, hfR⟩
    exact hRM hfR
  · intro f hf
    exact ⟨M, ⟨subset_rfl, fun r hr s hs => M_comp_mem hr hs⟩, hf⟩

/-! ### The refutation -/

/-- **MathDB #363496 — Conjecture 3.13 is false, intended reading.**  With `A = {e, u, v} ⊆ P_PU`
containing the identity, `R̄ ∪ {id} = {e}` but `v ∈ P_X`. -/
theorem conjecture_false_intended : Rbar ∪ {id} ≠ PX := by
  intro h
  have hv : v ∈ Rbar ∪ ({id} : Set (ℝ≥0 → ℝ≥0)) := by rw [h]; exact v_mem_PX
  rw [Rbar_union_id, Set.mem_singleton_iff] at hv
  exact e_ne_v hv.symm

/-- **MathDB #363496 — Conjecture 3.13 is false, literal reading.**  With the containment
condition dropped, `R̄ = [A] ∋ z`, but `z ∉ P_X`. -/
theorem conjecture_false_literal : RbarLiteral ∪ {id} ≠ PX := by
  intro h
  have hz : zf ∈ RbarLiteral ∪ ({id} : Set (ℝ≥0 → ℝ≥0)) := by
    refine Or.inl ?_
    rw [RbarLiteral_eq]
    exact zf_mem_M
  rw [h] at hz
  exact zf_not_mem_PX hz

end Principia.MathDB.P363496
